4326 - Fixes multiple bugs in Tabs RTL Uplift
infor-design/enterprise pull request #4346
Opened 2020-09-07 17:19 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes multiple issues on both RTL and LTR in Tabs Component listed below
- Error Icon position in tabs when triggered (RTL Uplift)
- Animation bar inside of modal (RTL Uplift)
- Error icon position (slight misalignment on firefox RTL and LTR)

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/4326

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/tabs/test-modal-error.html?theme=uplift&variant=light&colors=0066D4&locale=ar-SA
- Open `Add Context` button
- Animation bar should align with the selected tab
- Tab out in the required input field to trigger the error icon
- Error icon beside of tab should not overlapped the tab text (Should vertically aligned)
- Test also on LTR, and follow the same steps above
- Test also on multiple browsers (misalignment is noticeable on Firefox) 

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2020-09-08 14:00 UTC, jmacaluso711 requested changes
Looks good in chrome and safari. Firefox tab icon alignment looks slightly off.

![Screen Shot 2020-09-08 at 9 57 54 AM](https://user-images.githubusercontent.com/1084735/92486424-1498f100-f1ba-11ea-9cab-c25aaaec3dd4.png)

2020-09-08 16:02 UTC, ericangeles commented
@jmacaluso711 fixed the issue, thanks!

2020-09-09 15:21 UTC, tmcconechy approved these changes

2020-09-09 20:15 UTC, jmacaluso711 approved these changes

2020-09-09 20:15 UTC, merged