1590 - Add support to disable column buttons with datagrid
infor-design/enterprise pull request #4379
Opened 2020-09-16 18:16 UTC by deep7102

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Added support to disable column buttons with Datagrid.

**Related github/jira issue (required)**:
Closes #1590

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to: http://localhost:4000/components/datagrid/test-icon-buttons.html
- See icon buttons in 2nd and 3rd row for column `Disable Buttons` or `Disable Buttons (as link)`
- The buttons should be disabled

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2020-09-17 13:25 UTC, tmcconechy requested changes
This looks good but

1) can we show the disable link in the test page?
2) can we name the setting `disabled` not `disableButton` ?

2020-09-17 15:56 UTC, deep7102 commented
@tmcconechy updated now, to fix both cases as you found -thanks

2020-09-17 19:50 UTC, tmcconechy approved these changes

2020-09-18 17:29 UTC, jmacaluso711 approved these changes

2020-09-18 17:29 UTC, merged