4398 - Fix color picker for overflow menu with editor
infor-design/enterprise pull request #4449
Opened 2020-10-01 16:12 UTC by deep7102

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixed the color picker was not opening the popup for overflow menu and had name as undefined in list with Editor.

**Related github/jira issue (required)**:
Closes #4398

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to: http://localhost:4000/components/editor/example-index.html
- Make the browser window small so that the button `Text color` NOT fit in toolbar ( can use device toolbar mode in dev tools)
- Click the `...` action button to open menu
- See color picker button name should list as `Text color`
- Click on it and see it should open the color picker popup

**Included in this Pull Request**:
- [x] A note to the change log.

2020-10-01 17:42 UTC, tmcconechy requested changes
I fixed a test here that i fixed on another PR. But i am seeing one problem. This works perfectly to open the color picker from the overflow menu the first time. But if you try it a second time then the option is missing from the menu?

- go mobile so the color is in the dropdown
- open the overflow and pick a color
- try and open the overflow again -> color menu item is gone?

2020-10-02 14:49 UTC, deep7102 commented
Hi @tmcconechy updated now, to fix missing color picker option from menu after 1st time opened

2020-10-02 14:50 UTC, tmcconechy approved these changes

2020-10-05 05:25 UTC, ericangeles approved these changes

2020-10-05 13:06 UTC, merged