4452 - Fix readonly and non-selectable listview should not have hover state
infor-design/enterprise pull request #4494
Opened 2020-10-14 14:40 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Readonly and non-selectable listview should not have hover state.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/4452

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/listview/example-index?theme=uplift&variant=light&colors=0066D4
- Hover the items
- It should not have hover styling
- Test this also on all themes and variants combinations

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2020-10-14 14:52 UTC, tmcconechy requested changes
There is a trick to this to. We still need the focus state and to be focusable (could make that an option tho).

But in the example https://design.infor.com/code/ids-enterprise/latest/demo/components/listview/example-index?theme=uplift&variant=light&colors=0066D4 its correct it gets a blue border on click and its correct that you can use keys to move up and down. The only thing NOT correct is the hover effect since that is only needed if selected.

So we still need focus on http://localhost:4000/components/listview/example-index?theme=uplift&variant=light&colors=0066D4

2020-10-15 14:04 UTC, tmcconechy submitted a review, later dismissed
Cool 👍 
This works as i am expecting now

2020-10-15 19:03 UTC, tmcconechy approved these changes

2020-10-15 19:28 UTC, deep7102 approved these changes

2020-10-15 19:28 UTC, merged