4498-  Automation ids for monthview, weekview, calendar and calendar toolbar
infor-design/enterprise pull request #4508
Opened 2020-10-19 18:13 UTC by tmcconechy

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adds the attributes/automation id / id functionality for dmonthview, weekview, calendar and calendar toolbar. This includes docs and tests.

**Related github/jira issue (required)**:
Part of 4498 but doesnt close it all

**Steps necessary to review your pull request (required)**:
- review the text in the docs
- go to http://localhost:4000/components/calendar/example-index.html check the toolbar and legend items get an id from the settings
- go to http://localhost:4000/components/calendar-toolbar/example-index.html check the toolbar gets an id from the settings
- go to http://localhost:4000/components/week-view/example-index.html check the toolbar get an id from the settings
- go to http://localhost:4000/components/monthview/example-index.html check the toolbar get an id from the settings

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2020-10-20 16:26 UTC, EdwardCoyle approved these changes

2020-10-20 20:23 UTC, jmacaluso711 requested changes
Looks like the legend doesn't have the IDs at smaller breakpoints --http://localhost:4000/components/calendar/example-index.html -- Everything else looks good to me.

![Screen Shot 2020-10-20 at 4 19 57 PM](https://user-images.githubusercontent.com/1084735/96639907-60c66d80-12f0-11eb-808d-718515a7aa9f.png)

![Screen Shot 2020-10-20 at 4 20 22 PM](https://user-images.githubusercontent.com/1084735/96639911-62903100-12f0-11eb-9c58-3cca892b0d11.png)

2020-10-20 21:08 UTC, tmcconechy commented
@jmacaluso711 fixed. added id's for those as well

2020-10-21 13:22 UTC, jmacaluso711 approved these changes
🍌

2020-10-21 13:40 UTC, merged