4498 - Add automation id for Splitter, Switch, Timeline, Timepicker and Signin
infor-design/enterprise pull request #4542
Opened 2020-10-26 14:11 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adds automation id for splitter, switch, timeline, timepicker and signin components. Also includes docs and e2e.

**Related github/jira issue (required)**:

Partial https://github.com/infor-design/enterprise/issues/4498

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app

1.) Splitter
- Go to http://localhost:4000/components/splitter/example-index
- Open developers tool and inspect the element
- `splitter`, `splitter handle` and `splitter icon` should all have id and automation id.
- NOTE: the id of handle and icon should append it's name. e.g `data-automation-id='splitter-automation-id-1-handle'`, `data-automation-id='splitter-automation-id-1-icon'`

2.) Timepicker
- Go to http://localhost:4000/components/timepicker/example-index
- Open developers tool and inspect the element
- `timepicker` and `timepicker trigger` should have id and automation id.
- The `trigger` should append its name on the id. e.g. `timepicker-automation-id-1-trigger`

3.) Signin, Switch, & Timeline
- Go to http://localhost:4000/components/signin/example-index
- Go to http://localhost:4000/components/switch/example-index
- Go to http://localhost:4000/components/timeline/example-index
- Inspect the element
- The main component should have id and automation id
- These three does not need special cases like splitter and timepicker since you can add ids manually

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2020-10-26 14:22 UTC, tmcconechy commented on app/views/components/signin/example-index.html
> +        <form id="signin" data-validate-on="submit" autocomplete="off" data-automation-id="signin-automation-id">
Might want to show data-automation-id on all the inputs

2020-10-26 14:22 UTC, tmcconechy approved these changes

2020-10-26 20:14 UTC, EdwardCoyle requested changes
Just a couple things:
- comments below
- I was getting a JS console error on http://localhost:4000/components/splitter/example-index, however the automation ids are there.  It looks like the splitter is being updated with new settings, and the `destroy().init()` chain in there isn't completing... might be a separate issue?

2020-10-26 20:17 UTC, EdwardCoyle commented on src/components/timepicker/timepicker.js
> +    utils.addAttributes(this.trigger, this, this.settings.attributes, 'trigger');
I think we probably also want to have the individual Dropdowns get ids as well (hours, mins, seconds, day period)

2020-10-27 04:35 UTC, ericangeles commented
@EdwardCoyle yeah, and it seems that the CI does not detect this error though I have error detection on e2e. Yep, a separate issue will do.

2020-10-27 13:19 UTC, EdwardCoyle approved these changes

2020-10-27 13:21 UTC, tmcconechy approved these changes
Probably just need a test like https://github.com/infor-design/enterprise/blob/master/test/components/about/about.e2e-spec.js#L22 inside splitter but most important is to fix

2020-10-27 13:38 UTC, deep7102 commented
looks good, just one thing see the js error http://localhost:4000/components/splitter/example-index

<img width="849" alt="image" src="https://user-images.githubusercontent.com/38439203/97309252-269d2480-1838-11eb-9efa-8564797d73c3.png">

2020-10-27 13:40 UTC, tmcconechy requested changes
Just fix that splitter error then maybe add a test as i mentioned 👍

2020-10-27 19:18 UTC, jmacaluso711 submitted a review, later dismissed

2020-10-27 20:56 UTC, tmcconechy commented on docs/CHANGELOG.md
> +- `[Splitter/Switch/Timeline/Timepicker/Signin]` Added `attributes` setting to set automation ids's and id's. ([#4498](https://github.com/infor-design/enterprise/issues/4498))
Can remove this as i made one entry for all components https://github.com/infor-design/enterprise/pull/4554/files

2020-10-29 14:08 UTC, tmcconechy approved these changes

2020-10-29 20:07 UTC, jmacaluso711 approved these changes

2020-10-30 12:47 UTC, merged