4474 - Fix the last option icon changes when filtering
infor-design/enterprise pull request #4602
Opened 2020-11-12 12:34 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes the last option icon when filtering in dropdown search field. Removing the script that changes the last icon to `icon-empty-circle`.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/4474

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/dropdown/example-icons
- In first element, click on the dropdown and remove the text in the search field
- It should not change the last icon to `icon-empty-circle`
- Try also some combinations to make sure it does not change

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2020-11-16 19:05 UTC, jmacaluso711 submitted a review, later dismissed

2020-11-16 19:33 UTC, tmcconechy requested changes
@ericangeles this is probably acceptable but he idea was that it would change to the circle icon for the search field only. Because it means it didnt find an icon for the search term. But just not change the last item (other item).

So when you backspace it should ideally change to an empty circle just not effect any other items

2020-11-17 12:18 UTC, ericangeles commented
Updated the steps above. Thanks, @tmcconechy.

2020-11-17 19:27 UTC, tmcconechy commented
Looks great now. Nice fix 👍

2020-11-17 19:27 UTC, merged