4550 - Fix click for keyword search on hyperlinks with datagrid
infor-design/enterprise pull request #4604
Opened 2020-11-12 16:57 UTC by deep7102

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixed click event was not fire for hyperlinks keyword search results with Datagrid.

**Related github/jira issue (required)**:
Closes #4550

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to: http://localhost:4000/components/datagrid/example-keyword-search.html
- Open developer tools
- Type `I Love` in keyword search and press enter
- It should come with one row result
- Click anywhere on highlighted part or not highlighted part to hyperlink in column `Product Name`
- See the console should log on clicked

**Included in this Pull Request**:
- [x] A note to the change log.

2020-11-16 19:08 UTC, jmacaluso711 submitted a review, later dismissed

2020-11-16 19:36 UTC, tmcconechy requested changes
If you watch the console the click event now fires twice for when you click the <i> also the event data is different on both.

I think the data should be the same and it should just fire once. Possibly by ensuring the click propagate to the anchor tag or some other solution?

2020-11-16 20:56 UTC, tmcconechy approved these changes

2020-11-17 15:04 UTC, EdwardCoyle approved these changes

2020-11-17 15:04 UTC, merged