4532 - Add optional "More Actions" button to Tabs
infor-design/enterprise pull request #4681
Opened 2020-12-11 21:18 UTC by EdwardCoyle

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR adds in styling support for a "More Actions" button that sits in-line with a horizontal tab set.

**Related github/jira issue (required)**:
Closes #4532

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, run the app.
- Open http://localhost:4000/components/tabs/test-more-actions-button?theme=uplift.  Check the more actions button style against the tabset.  Shrink the page and make sure it works with the "More Tabs" dropdown.
- Also test this with an add button:  http://localhost:4000/components/tabs/test-more-actions-button-add-button.html?theme=uplift
- Test both on RTL, also check Subtle styles.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2020-12-14 14:52 UTC, tmcconechy requested changes
<img width="483" alt="Screen Shot 2020-12-14 at 9 50 35 AM" src="https://user-images.githubusercontent.com/814283/102095703-d5e68880-3df1-11eb-8da8-3495359273fd.png">

1. Seems like the icon sits a little low when focused the bottom border is touching 
2. How does the keyboard work when i have it at this smaller size the overflow keyboard conflicts. I.E. try tabbing vs arrowing to the new button. Should probably be arrow but only tab works?

2020-12-14 21:04 UTC, EdwardCoyle commented
@tmcconechy reworked this and added keyboard support for the new button.

2020-12-15 14:19 UTC, tmcconechy approved these changes

2020-12-15 14:32 UTC, ericangeles approved these changes

2020-12-15 14:43 UTC, merged