4702 - Fix hyperlinks not clickable in readonly state
infor-design/enterprise pull request #4706
Opened 2020-12-22 11:54 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes hyperlinks were not clickable when the editor is in readonly state.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/4702

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/editor/test-readonly.html
- Hyperlink should be clickable

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2020-12-22 14:33 UTC, tmcconechy requested changes
Sorry this isnt related to the fix but i think we can easily fix it. See the top border when readonly here:

![Screen Shot 2020-12-22 at 9 31 02 AM](https://user-images.githubusercontent.com/814283/102899132-795e1b80-4438-11eb-9e6f-9575698170e6.png)

2020-12-22 14:33 UTC, tmcconechy commented
Also @anhallbe can you test this? Seems right but in your videos you have a different background readonly editor? So seems like it could be slightly different

2020-12-22 17:46 UTC, tmcconechy approved these changes

2020-12-23 14:31 UTC, EdwardCoyle approved these changes

2020-12-23 14:35 UTC, merged