4683 - Fix searchfield toolbar unable to focus when tabbing
infor-design/enterprise pull request #4721
Opened 2021-01-06 15:38 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes issue on the searchfield toolbar where unable to focused when tabbing through the page.

Found out that the `tabindex="-1"` adds to the searchfield element after the initialization itself.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/4683

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
- Tab through the page to show each element getting focused
- Searchfield should now be focused

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2021-01-07 14:34 UTC, tmcconechy requested changes
I think the only problem i see is the focus state styling is a bit strange. Can you fix?

1. when you focus the field there is a box shadow and it looks like it makes the field smaller. To fix i think we can just have no focus state for this case or make it white if that looks good?

<img width="394" alt="Screen Shot 2021-01-07 at 9 32 25 AM" src="https://user-images.githubusercontent.com/814283/103904485-520b7d80-50cb-11eb-9677-9eafd7959079.png">

2. when the go button is focs there is an extra line under the input which isnt needed

<img width="389" alt="Screen Shot 2021-01-07 at 9 33 50 AM" src="https://user-images.githubusercontent.com/814283/103904592-78311d80-50cb-11eb-9fea-afd490a26a85.png">

2021-01-07 14:36 UTC, tmcconechy commented on docs/CHANGELOG.md
> +- `[Toolbar Searchfield]` Fixed a bug where the toolbar searchfield were unable to focused when tabbing through the page. ([#4683](https://github.com/infor-design/enterprise/issues/4683))
Should go up in the 4.37 section now

2021-01-07 19:10 UTC, tmcconechy submitted a review, later dismissed

2021-01-11 20:18 UTC, deep7102 submitted a review, later dismissed

2021-01-11 21:18 UTC, merged