Fix for git issue 4725, Process Indicator overlaps fields
infor-design/enterprise pull request #4726
Opened 2021-01-07 00:19 UTC by krishollenbeck

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixes 4725 process indicator layout overlaps fields when placing fields underneath it.

**Related github/jira issue (required)**:
https://github.com/infor-design/enterprise/issues/4725

**Steps necessary to review your pull request (required)**:
1. Checkout branch git-issue-4725
2. Build/run ids project
3. Navigate to http://localhost:4000/components/processindicator/example-labels.html

Fixed examples:
![process-indicator-uplift](https://user-images.githubusercontent.com/1056684/103835341-a242fb00-504b-11eb-919d-9236c156d023.gif)
![process-indicator-subtle](https://user-images.githubusercontent.com/1056684/103835346-a3742800-504b-11eb-89a0-8ed6ab0c58ec.gif)

2021-01-07 12:16 UTC, ericangeles requested changes
LGTM 🍌! Just need to fix the failing visual regress then will re-review.

2021-01-07 14:39 UTC, tmcconechy commented
@krishollenbeck to fix the test you could just leave the example-labels one the way it is and make a new page instead call test-inputs-below.html or something.

2021-01-07 19:11 UTC, tmcconechy submitted a review, later dismissed

2021-01-07 19:25 UTC, tmcconechy approved these changes

2021-01-08 10:41 UTC, ericangeles approved these changes

2021-01-08 15:13 UTC, merged