4708 - Dropdown Virtual scroll
infor-design/enterprise pull request #4792
Opened 2021-01-29 21:10 UTC by tmcconechy

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adds a virtual scrolling feature in basic from to dropdown to help support 5K-15k items. In addition fixed a small bug in disabled dropdowns and updated some font docs. And some small changes for support.

**Related github/jira issue (required)**:
Fixes #4708 
Fixes #4739 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/dropdown/example-virtual-scroll.html
- open the list (it has 12K items and it should render very fast)
- try typeahead for example "Jan" or "2052"
- try arrow up and arrow down
- when open hover an item to see a tooltip
- smoke test as many examples in http://localhost:4000/components/dropdown/ and http://localhost:4000/components/mutiselect as you care to

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-01-29 21:19 UTC, tmcconechy commented
cc @jmacaluso711 are any of the fonts in https://github.com/infor-design/enterprise/tree/master/app/www/fonts used in the design.infor.com site?

2021-02-01 15:43 UTC, EdwardCoyle requested changes
Found a handful of things but otherwise looks good to me:

- http://localhost:4000/components/dropdown/example-virtual-scroll.html: When using the typeahead feature it doesn't appear to be focusing the list when opened.  I keyed "Feb" while closed, and it does show the right results (scrolled to them), but keyboard navigation isn't available.
- http://localhost:4000/components/dropdown/example-index.html - Not really a big deal but I noticed when arrowing up/down, the highlighted state is now always at the top of the list (as opposed to one/two items down from the top).
- http://localhost:4000/components/dropdown/test-blank-option.html - Trying to select a blank option is throwing a JS console error that [breaks here](https://github.com/infor-design/enterprise/blob/4708-virtual-scroll/src/components/dropdown/dropdown.js#L2396)

2021-02-01 19:55 UTC, tmcconechy commented
@EdwardCoyle -> fixed all 3 points - except for point 2. I was only able to easily fix that back for NON virtual-scrolling but it still does it for virtual scrolling

2021-02-01 20:13 UTC, EdwardCoyle approved these changes

2021-02-01 20:15 UTC, deep7102 approved these changes

2021-02-01 21:22 UTC, merged