4539 - Add fixes for lookup select across pages issues
infor-design/enterprise pull request #4880
Opened 2021-02-24 17:51 UTC by tmcconechy

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixed an issues with select across pages.

**Related github/jira issue (required)**:
Fixes #4539

**Steps necessary to review your pull request (required)**:
**Issue 4539**
- go to http://localhost:4000/components/lookup/example-multiselect-paging-serverside
- open the lookup and pick at least one on page 1
- hit apply
- repopen
- unselect the one on page one
- go to page 2 and pick one
- hit apply -> only one should be selected

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-02-25 15:11 UTC, deep7102 approved these changes

2021-02-26 15:24 UTC, EdwardCoyle requested changes
I'm not sure its totally right - if you follow all your steps, but then navigate back to page 1, the previously selected item is still selected:

![IDS-Enterprise-_2_](https://user-images.githubusercontent.com/3249601/109319375-cab1cf00-781c-11eb-990e-167a5d7b5751.gif)

2021-02-26 16:37 UTC, tmcconechy commented
good catch @EdwardCoyle added a fix for that

2021-02-26 20:27 UTC, EdwardCoyle approved these changes

2021-02-26 21:01 UTC, merged