4904/4907/4908 - Fix regression in dropdown scrolling
infor-design/enterprise pull request #4911
Opened 2021-03-03 16:43 UTC by tmcconechy

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fixes an issue where the entire page will scroll when scrolling dropdowns now. Causing issues

**Related github/jira issue (required)**:
Fixes #4904
Fixes #4907
Fixes #4908

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/
- scroll to the dropdowns and then the multiselects and try the following:
  - open and then scroll the page to close
  - open and it shouldnt "jerk" the page
  - open and filter and it shouldnt close
- in multiselect tags select some tags
- ensure http://localhost:4000/components/dropdown/example-virtual-scroll.html works as before
- go to the CAP example
- open it and use the dropdowns
- try the CAP on latest IPAD - dropdowns should work

2021-03-04 17:24 UTC, deep7102 approved these changes

2021-03-04 17:27 UTC, EdwardCoyle requested changes
I'm still seeing the iPad issues on this branch.  Testing an iPad in the simulator on iOS 14.4, it looks like the CAP Dropdowns aren't working, and the in-page Dropdowns work on the first open, but close themselves automatically if they are opened a second time:

![Untitled_-Mar-4-2021-12_21-PM](https://user-images.githubusercontent.com/3249601/110004000-f46b6a00-7ce4-11eb-90b9-fba051ad7bef.gif)

Everything else looked good 👍

2021-03-04 19:55 UTC, tmcconechy commented
ok all fixed for ipad now.. give it a try @EdwardCoyle it was maybe an important addition to this

2021-03-04 19:59 UTC, EdwardCoyle approved these changes
:banana: looks good!

2021-03-05 17:55 UTC, deep7102 approved these changes

2021-03-05 18:25 UTC, merged