3229 - Add support for double click with Bar, Bar Grouped, Bar Stacked
infor-design/enterprise pull request #4959
Opened 2021-03-17 19:00 UTC by deep7102

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Added support for double click with Bar, Bar Grouped, Bar Stacked.

**Related github/jira issue (required)**:
Fixes #3229

**Steps necessary to review your pull request (required)**:
- Pull this branch and build/run the demo app
- Navigate to:
- http://localhost:4000/components/bar/test-double-click.html
- http://localhost:4000/components/bar-grouped/test-double-click.html
- http://localhost:4000/components/bar-stacked/test-double-click.html
- Open developer tools
- Click single/double on any bar
- See logs in console
- Single click `selected` and double `double clicked` event

**Included in this Pull Request**:
- [x] A note to the change log.

2021-03-18 16:27 UTC, deep7102 commented
It's ready to review now

2021-03-19 13:44 UTC, tmcconechy commented on app/views/components/bar-grouped/test-double-click.html
> +    .on('eventdblclick', function (e, args) {
@deep7102 if the event is `dblclick` then how come the examples have `eventdblclick`? Is that a mistake?
I think it should be `dblclick`. See it works so im confused as to why it would?

2021-03-19 13:45 UTC, tmcconechy requested changes
Change event name to match please

2021-03-19 13:45 UTC, tmcconechy commented on src/components/bar/bar.js
> +    self.element.triggerHandler('eventdblclick', [args]);
```suggestion
    self.element.triggerHandler('eventdblclick', [args]);
```

Ok see - yes lets make this dblclick so it matches the names in other components

2021-03-19 15:04 UTC, deep7102 commented on app/views/components/bar-grouped/test-double-click.html
> +    .on('eventdblclick', function (e, args) {
updated as `dblclick` -thanks

2021-03-19 15:05 UTC, deep7102 commented on src/components/bar/bar.js
> +    self.element.triggerHandler('eventdblclick', [args]);
updated now, to be `dblclick`

2021-03-19 15:06 UTC, deep7102 commented
Hi @tmcconechy it updated now to use `dblclick` event name -thanks

2021-03-19 15:29 UTC, tmcconechy approved these changes
🍌

2021-03-19 15:31 UTC, EdwardCoyle approved these changes

2021-03-19 22:00 UTC, merged