4917 - Lightened the colors for disabled breadcrumbs
infor-design/enterprise pull request #4960
Opened 2021-03-17 20:39 UTC by chrisakinrinade

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Disabled breadcrumbs currently have no visual distinction from enabled breadcrumbs - this solves that by making them lighter.

**Related github/jira issue (required)**:
#4917 

**Steps necessary to review your pull request (required)**:
1. Visit /components/breadcrumb/example-add-remove.html
2. Click Add button
3. Click disabled check box
4. Click Add button again
Observe the difference in coloring between the two breadcrumbs
![image](https://user-images.githubusercontent.com/72534276/111534387-504edd80-873e-11eb-946f-780e90a44fe4.png)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-03-18 14:32 UTC, tmcconechy requested changes
A couple comments:

1. whats that empty file with PR info in it
2. whats teh difference between http://localhost:4000/components/breadcrumb/example-add-remove-disabled.html and http://localhost:4000/components/breadcrumb/example-add-remove.html (did we need two identical? examples)
3. in some themes its still not disabled looking enough (bring the color/down/ up a bit?) in themes:
 - classic - dark
 - new - dark
 - classic - contrast
 - new - contrast

2021-03-18 14:32 UTC, tmcconechy commented on +
> +Merge branch 'master' of https://github.com/infor-design/enterprise
Whats this file? Maybe added by mistake? (its wierd it has no name)

2021-03-19 14:33 UTC, EdwardCoyle reviewed
See below:

2021-03-19 14:33 UTC, EdwardCoyle commented on test/components/breadcrumb/breadcrumb.e2e-spec.js
> +        await utils.setPage(`/components/breadcrumb/example-add-remove-disabled?theme=${theme}&mode=${mode}`);
@tmcconechy I'd mentioned to @chrisakinrinade that we didn't have any sample pages that demonstrated a disabled Breadcrumb item that we could easily use for visual regression/aXe testing, hence the duplicate page (used here).

Chris, you probably don't need to have the entire add/remove functionality in the new breadcrumb example page.  Just placing the breadcrumb with the disabled item should be sufficient.  👍

2021-03-19 14:33 UTC, EdwardCoyle commented on test/components/breadcrumb/breadcrumb.e2e-spec.js
> +        await utils.setPage(`/components/breadcrumb/example-add-remove-disabled?theme=${theme}&mode=${mode}`);
Thanks for the added test BTW

2021-03-19 14:38 UTC, tmcconechy commented on test/components/breadcrumb/breadcrumb.e2e-spec.js
> +        await utils.setPage(`/components/breadcrumb/example-add-remove-disabled?theme=${theme}&mode=${mode}`);
Yes thats what i also said to @chrisakinrinade in chat. could make an example-disabled page that is just showing a few disabled tags based on example-index so we can make a test without clicking all the buttons

2021-03-23 13:22 UTC, tmcconechy commented
Looks like you might need to update the test / test link or remove this test https://github.com/infor-design/enterprise/pull/4960/checks?check_run_id=2171627316#step:10:3351

Is the rest ready to review?

2021-03-23 16:01 UTC, chrisakinrinade commented
Ok, I removed one test and tweaked the others. Ready to review! @tmcconechy

2021-03-23 18:49 UTC, tmcconechy submitted a review, later dismissed
Looks good to me now. Fix is correct and tests look good.

2021-03-24 13:39 UTC, tmcconechy approved these changes

2021-03-24 14:11 UTC, EdwardCoyle approved these changes
Looks great!  :banana:

2021-03-24 14:11 UTC, merged