439 changing the chart type doesnt remove old class name issue 3144
infor-design/enterprise pull request #4965
Opened 2021-03-18 15:34 UTC by danielortiz1982

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
I added a destroy method inside of the charts objects that will check the type of chart being used and adjust the class name based on it. This method will run right before the **this.init()** that contains the chart build logic.

**Related github/jira issue (required)**:
https://github.com/infor-design/enterprise/issues/3144

**Steps necessary to review your pull request (required)**:
Include:
- Navigate to the any of the chart components, for this sample I have used the pie chart.
(http://localhost:4000/components/pie/example-index.html)
- Right click and select the inspect, then navigate to the console.  
- Paste in the follow code snippet inside the console to change the chart as outlined by **kvaldillez** in issue #3144
**Code Snippet** 
`var areaData = [{ data: [{ name: 'Component D', value: 10.1, id: 'A', tooltip: 'Component D <b>{{percent}}</b>' }, { name: 'Component E', value: 12.2, id: 'B', tooltip: 'Component E <b>{{percent}}</b>' }] }];
$('#pie-chart-example').chart({type: 'area', dataset: areaData});`
- Press enter, the chart should update along with the DOM classes. 
**Screenshot**
<img width="1233" alt="example-index" src="https://user-images.githubusercontent.com/5215954/111652584-8e4f0e80-87dd-11eb-804e-051d22c9b0b9.png">
<img width="1822" alt="preview" src="https://user-images.githubusercontent.com/5215954/111652592-9018d200-87dd-11eb-9fa3-29597fc67703.png">
<img width="1816" alt="Screen Shot 2021-03-18 at 11 19 11 AM" src="https://user-images.githubusercontent.com/5215954/111652596-9149ff00-87dd-11eb-8545-a4b1d1994406.png">
<img width="1914" alt="Screen Shot 2021-03-18 at 11 19 27 AM" src="https://user-images.githubusercontent.com/5215954/111652601-91e29580-87dd-11eb-809b-eee78eddda2c.png">
<img width="1827" alt="Screen Shot 2021-03-18 at 11 19 40 AM" src="https://user-images.githubusercontent.com/5215954/111652605-91e29580-87dd-11eb-9125-080a75a0315e.png">
<img width="1793" alt="Screen Shot 2021-03-18 at 11 19 51 AM" src="https://user-images.githubusercontent.com/5215954/111652607-91e29580-87dd-11eb-9758-fb383b51c1d0.png">

**Included in this Pull Request**:
- [x] A note to the change log.

2021-03-18 17:49 UTC, tmcconechy approved these changes
Looks good 🍌

2021-03-18 21:01 UTC, deep7102 commented on src/components/charts/charts.js
> +  e.className = 'chart-container';
This looks good approach to handle this issue, only concern about using `className` here will remove all end-user classes if there is any of them in use for some other purpose. So I purpose as below, map the classes we use and remove only them. Modify the `chartClasses` object as you need for which charts to be added or removed.
```
charts.destroy = function destroy(el, s) {
  const e = el[0];
  const chartClasses = {
    'bar': ['bar-chart'],
    'bar-grouped': ['bar-chart', 'bar-chart-grouped'],
    'bar-stacked': ['bar-chart', 'bar-chart-stacked']
  };

  if (e && chartClasses[s.type]) {
    const newClassList = ['chart-container', ...chartClasses[s.type]];
    const chartClassesAll = [].concat(...Object.values(chartClasses));
    e?.classList.remove(...chartClassesAll);
    e?.classList.add(...newClassList);
  }
};
```

2021-03-18 21:45 UTC, danielortiz1982 commented on src/components/charts/charts.js
> +  e.className = 'chart-container';
Hi @deep7102 
Thanks for the feedback... I have tested every scenario for each of the different charts and everything seems to be working as expected. Let's get together sometime tomorrow so I can better understand the concerns you've outlined above along with your proposed solution. I popped in your sample code and the chart-pie class still persist in the DOM. I will ping you tomorrow so we can connect.  
<img width="1798" alt="Screen Shot 2021-03-18 at 5 41 29 PM" src="https://user-images.githubusercontent.com/5215954/111701552-65487100-8811-11eb-8df6-14cd229682ca.png">

2021-03-19 13:45 UTC, deep7102 commented on src/components/charts/charts.js
> +  e.className = 'chart-container';
Hi @danielortiz1982 sure you can ping me if you need, the issue I see if user having any class/es using with this element then it will wipe all of them for example `<div id="bar-example" class="chart-container some-user-class"></div>` here it will wipe off `some-user-class`.

That proposed solution code is just sample in order to use you need to add/remove in `chartClasses` object. So in case of `Pie` need to add as below: 
```
const chartClasses = {
    'bar': ['bar-chart'],
    'bar-grouped': ['bar-chart', 'bar-chart-grouped'],
    'bar-stacked': ['bar-chart', 'bar-chart-stacked'],
    'pie': ['chart-pie']
  };
```

2021-03-19 13:51 UTC, tmcconechy commented on src/components/charts/charts.js
> +  e.className = 'chart-container';
I think deepak is correct. It's probably safer. So instead of removing the className all together just remove each of the N possible class names from there and then add the new one.

There could be other classes added to the root (unrelated to the chart classes in question)

2021-03-19 13:53 UTC, deep7102 requested changes
Hi, I just thought of that way you may use your own way if you have another solution, it was in my mind so save some time for you I just put it in there.

Just make it remove all possible chart class names then add the new one - but don't remove all classNames

2021-03-19 14:00 UTC, danielortiz1982 commented on src/components/charts/charts.js
> +  e.className = 'chart-container';
@deep7102 I see your point, I did not take into count that end users implementation of the chart on their end.  
Thanks for the feedback @deep7102  and @tmcconechy

2021-03-23 13:35 UTC, deep7102 approved these changes

2021-03-23 18:50 UTC, merged