4989 - search x header alignment fixes
infor-design/enterprise pull request #5022
Opened 2021-03-31 14:30 UTC by rob2d

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Should solve most (if not all) of the styling issues with the search fields and toolbar search fields that contain clear buttons.

**Related github/jira issue (required)**:
Closes #4989 

**Steps necessary to review your pull request (required)**:
- Build the demo application and look over components in the places listed below. 
- Type in some content and see an "X" to clear content. 

Previously the "X" would be down into the search field on certain scenarios; this should no longer happen. 

As mentioned in the issue, the components in these sections should be checked locally.
[http://localhost:4000/components/searchfield](http://localhost:4000/components/searchfield)
[http://localhost:4000/components/toolbarsearchfield](http://localhost:4000/components/toolbarsearchfield)
[http://localhost:4000/components/header](http://localhost:4000/components/header)
[http://localhost:4000/components/tabs-module](http://localhost:4000/components/tabs-module)

For reference/sanity check if the PR is merged:
[https://master-enterprise.demo.design.infor.com/components/searchfield](https://master-enterprise.demo.design.infor.com/components/searchfield)
[https://master-enterprise.demo.design.infor.com/components/toolbarsearchfield](https://master-enterprise.demo.design.infor.com/toolbarsearchfield)
[https://master-enterprise.demo.design.infor.com/components/header](https://master-enterprise.demo.design.infor.com/components/header)
[https://master-enterprise.demo.design.infor.com/components/tabs-module](https://master-enterprise.demo.design.infor.com/components/tabs-module)

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [X] A note to the change log.

2021-03-31 14:36 UTC, rob2d commented
Just a note that also in this branch/PR:

- TESTING.md changes: minor clarifications/updates, added a nav/TOC since there's non-sequential topics
- refactored/iterated on specific data grid e2e tests since those were flaking out here and there w some new conventions where we can avoid sleep in this file going forward.

2021-03-31 14:36 UTC, tmcconechy commented on docs/TESTING.md
> +- [Test Stack](#test-stack)
I think we did pretty much the same thing here would you try and put these on https://github.com/infor-design/enterprise/pull/5023 or we might have a merge conflict? thanks

2021-03-31 14:49 UTC, rob2d commented on docs/TESTING.md
> +- [Test Stack](#test-stack)
and yep we did have some conflicts but sorted it out and tried to preserve your changes on it.

2021-04-01 13:20 UTC, tmcconechy approved these changes

2021-04-01 13:31 UTC, EdwardCoyle requested changes
Great PR with all the docs improvements, thanks for this!  Just found one thing below

2021-04-01 13:31 UTC, EdwardCoyle commented on src/components/searchfield/_searchfield.scss
> +      display: flex;
I found one Searchfield example where the close button is still displayed when the input has no contents:  http://localhost:4000/components/tabs-module/example-category-searchfield-go-button.html -- seems to be tied to this rule?  We may have to qualify it somehow with `:empty` or with `.is-empty` coming from the wrapper?

2021-04-01 13:36 UTC, rob2d commented on src/components/searchfield/_searchfield.scss
> +      display: flex;
Good catch Ed, thanks. Checking into it.

2021-04-01 14:53 UTC, rob2d commented on src/components/searchfield/_searchfield.scss
> +      display: flex;
forgot to push there -- just running through CI now

2021-04-02 13:33 UTC, tmcconechy approved these changes

2021-04-02 20:07 UTC, EdwardCoyle submitted a review, later dismissed

2021-04-02 20:16 UTC, merged