5015 - Fix draggable toast message at bottom right position
infor-design/enterprise pull request #5081
Opened 2021-04-14 10:04 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the issue of  where it's unable to drag down the toast message to its current position if the `position` setting is set to `bottom right`.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5015

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/toast/test-bottom-right-draggable-position.html
- Click the button to trigger the toast message
- Drag toast message up then let go
- Grab again and try to drag down
- It should be able to move/drag it down

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2021-04-14 14:09 UTC, tmcconechy requested changes
I Noticed a strange behavior with the saving Try these steps
1. open the toast
2. move it anywhere by dragging
3. reload the page
4. open the toast (should be in the same position)

But i think it can be fixed by adding the option savePosition to the example so we should probably do that

2021-04-14 14:09 UTC, tmcconechy commented on app/views/components/toast/test-bottom-right-draggable-position.html
> +      draggable: true,
```suggestion
      draggable: true,
      savePosition: true,
```

Lets add save position or this example looks like its not working properly when you reload the page or click a toast again as it will go back to the old position.

2021-04-15 13:36 UTC, tmcconechy approved these changes

2021-04-15 14:24 UTC, deep7102 approved these changes

2021-04-15 14:38 UTC, merged