5088 - Fix Alignment on Lookup Close Button
infor-design/enterprise pull request #5109
Opened 2021-04-20 14:35 UTC by rob2d

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Close/"X" button alignment on searchfield in lookup was misaligned in the new theme variant.

**Related github/jira issue (required)**:

Closes #5088.

**Steps necessary to review your pull request (required)**:

- pull `5088-lookup-x-icon-misalignment`
- visit `http://localhost:4000/components/lookup/example-clearable.html`
- type anything in one of the search fields and see that the X icon is not misaligned vertically
![image](https://user-images.githubusercontent.com/1799905/115414083-c0300800-a1c3-11eb-82f2-3e2d8e1b61f1.png)
- repeat for `http://localhost:4000/components/lookup/example-clearable.html?theme=classic`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [X] A note to the change log.

2021-04-20 15:41 UTC, tmcconechy reviewed
A bit picky but i think its 1 or two pixels too high. It looks ok in classic mode.

![Screen Shot 2021-04-20 at 11 39 19 AM](https://user-images.githubusercontent.com/814283/115424930-24a39500-a1cd-11eb-8ebc-0d9be8a4a5c5.png)

Also a question for @EdwardCoyle and could be considered a new issue but should the x be tabbable it skips right be it when you tab in the field to the lookup.

2021-04-20 19:59 UTC, tmcconechy submitted a review, later dismissed

2021-04-21 10:02 UTC, ericangeles requested changes
I saw an issue in RTL

- Go to http://localhost:4000/components/lookup/example-clearable.html?theme=new&mode=light&colors=2578a9&locale=ar-EG
- Open the lookup
- Search something to trigger the clearable 
- Clearable is overlapping the search icon

<img width="691" alt="clearable" src="https://user-images.githubusercontent.com/8839327/115535770-a5e15180-a2cb-11eb-8a98-78c717218404.png">

2021-04-21 10:11 UTC, ericangeles commented on docs/CHANGELOG.md
> +- `[Lookup]` fix close button alignment issue. ([#5088](https://github.com/infor-design/enterprise/issues/5088))
A better changelog perhaps?

2021-04-21 15:22 UTC, rob2d commented
@ericangeles good catch/testing, thanks. Also good point on the changelog -- slightly increased scope but better to just avoid revisiting these buttons 🙂 

(pushed fix)
![rtl-modal-searchfield](https://user-images.githubusercontent.com/1799905/115577709-a5789480-a292-11eb-9a3f-9beaa7030feb.gif)

2021-04-21 15:26 UTC, rob2d commented on docs/CHANGELOG.md
> +- `[Lookup]` fix close button alignment issue. ([#5088](https://github.com/infor-design/enterprise/issues/5088))
think it should be good now -- good point/catch.

2021-04-21 15:38 UTC, tmcconechy approved these changes
This is good for my checks now - thanks @rob2d 👍🏻

2021-04-22 01:34 UTC, ericangeles commented
Looks pretty good now! But another thing that I saw on classic mode

It's not perfectly centered when it is focused.

<img width="549" alt="clearable-classic" src="https://user-images.githubusercontent.com/8839327/115642489-a3bfd700-a34d-11eb-8ace-132bc88bc299.png">

2021-04-22 15:44 UTC, rob2d commented
@ericangeles appreciate the thoroughness. Just went through/caught another case on LTR and retested all of them after these tweaks. Hopefully all in lookup close button cases covered (🤞).

2021-04-22 16:31 UTC, tmcconechy approved these changes

2021-04-23 08:18 UTC, ericangeles approved these changes
Sweet! 🍌 Thanks for the fix, @rob2d.

2021-04-23 13:04 UTC, merged