4503 - Fix unselected items on active page and display counts
infor-design/enterprise pull request #5174
Opened 2021-05-04 12:21 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
 
This PR fixes a bug where unselecting all items in an active page affects other selected items on other pages as well.

There's a line of code that resets the `this._selectedRows` after mapping it.

I also noticed that the selected counts don't reflect immediately. Fixed it too.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/4503

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/lookup/example-multiselect-paging-serverside
- Click the lookup button
- Tick top checkbox to Select all on first page
- Move to Page 2
- Tick top checkbox to Select all on second page
- Tick top checkbox to Unselect all on second page
- It should back to `5 Selected` and not remove the toolbar
- Go Back to page 1
- It should not reset or unselect all the items on Page 1

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2021-05-04 13:41 UTC, tmcconechy submitted a review, later dismissed
Great fix 👍🏻

2021-05-04 14:20 UTC, deep7102 requested changes

2021-05-04 14:20 UTC, deep7102 commented on src/components/datagrid/datagrid.js
> +    const isLookup = $('.lookup');
The fix looked nice but it might mess up if multiple instances on page, not sure what we trying to target why it needs to do that 100%, can see this to find if the grid is in a lookup or any other way to find

https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/datagrid.js#L6681-L6687

2021-05-05 09:08 UTC, ericangeles commented
@tmcconechy @deep7102, I reverted back my initial fix, and tested again the failing e2e and it seems to work now on my local machine. Will wait for travis if it's the same case. But if you have suggestion about this fix, feel free to add.

2021-05-05 09:11 UTC, ericangeles commented
@tmcconechy @deep7102, I reverted back my initial fix, and tested again the failing e2e and it seems to work now on my local machine. Will wait for travis if it's the same case. But if you have suggestions to fix this, feel free to add.

2021-05-05 09:40 UTC, ericangeles commented on src/components/datagrid/datagrid.js
> +    const isLookup = $('.lookup');
Thanks, @deep7102 ! I specified the lookup modal when open instead of if there's a lookup instance only. :)

2021-05-05 13:31 UTC, tmcconechy commented on src/components/datagrid/datagrid.js
> +    const isLookup = $('.lookup-modal.is-visible');
Another case this could go wrong maybe is if a modal is left in the page unopened or there is a nested modal.
Maybe you could try this instead...

```
const isLookup = (this.element.closest('.lookup-modal').length === 1);
````

2021-05-06 14:09 UTC, tmcconechy approved these changes

2021-05-06 16:55 UTC, deep7102 approved these changes
Looks good 🍌 
Thanks! @ericangeles

2021-05-06 17:07 UTC, merged