4962 - Fix animation issue
infor-design/enterprise pull request #5196
Opened 2021-05-14 13:36 UTC by tmcconechy

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Was trimming the backlog and stumbled over a small fix so including it. See steps

**Related github/jira issue (required)**:
Fixes #4962

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/datagrid/test-expandable-row-multiselect.html
- select a row with the checkbox 
- click the +/i icon and watch the animation (see that its not cut)
- try with row unselected ect

**Included in this Pull Request**:
- [x] A note to the change log.

2021-05-14 14:26 UTC, deep7102 submitted a review, later dismissed

2021-05-17 09:43 UTC, ericangeles requested changes

2021-05-17 09:43 UTC, ericangeles commented on docs/CHANGELOG.md
> -- `[Lookup/Datagrid]` Fixed a bug where unselecting all items in an active page affects other selected items on other pages. ([#4503](https://github.com/infor-design/enterprise/issues/4503))
This ticket issue shouldn't be removed?

2021-05-17 09:49 UTC, ericangeles commented
Looks good! 🍌

2021-05-17 13:29 UTC, ericangeles approved these changes

2021-05-17 15:20 UTC, deep7102 approved these changes

2021-05-17 16:13 UTC, merged