5095 - Enable highlighting of blank dropdown options
infor-design/enterprise pull request #5214
Opened 2021-05-20 18:40 UTC by EdwardCoyle

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes a bug in Dropdown where it wasn't possible for the dropdown to highlight blank options in the list when the list opened. This is now possible.

**Related github/jira issue (required)**:
Closes #5095

**Steps necessary to review your pull request (required)**:
- Pull, build, run!
- Open http://localhost:4000/components/dropdown/test-blank-initially.html
- Open the dropdown list.  The first option (which is blank) should be highlighted in blue.
- Press "Enter" on the keyboard.  The blank option should remain selected and the list should close.
- Test this on Virtual Scrolling as well: http://localhost:4000/components/dropdown/test-virtual-scroll-blank-option.html

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-05-24 14:08 UTC, tmcconechy requested changes
@EdwardCoyle found a bit of an issue
- http://localhost:4000/components/dropdown/test-blank-initially.html
- use the keyboard to open
- down arrow to alabama and select
- reopen the dropdown by any means... -> notice the blank option is missing now

2021-05-24 16:29 UTC, EdwardCoyle commented
@tmcconechy I didn't realize this at the time I made this PR, but this sample was pre-existing and intentionally removes the blank option if it's selected once:  https://github.com/infor-design/enterprise/blob/main/app/views/components/dropdown/test-blank-initially.html#L71

I can switch the test page to [this one](http://localhost:4000/components/dropdown/test-blank-option.html) if you like but for the purposes of checking that the blank option is selected when the menu's opened, the current one does the trick

2021-05-24 16:37 UTC, tmcconechy commented
Oh, nice - didnt realize that was part of the example. Yeha maybe change out the link to test in the PR or change that out of the example.

2021-05-24 16:54 UTC, tmcconechy approved these changes

2021-05-25 16:35 UTC, deep7102 submitted a review, later dismissed

2021-05-25 16:47 UTC, merged