5075 - Add support for mobile view and stay on provided date with monthview
infor-design/enterprise pull request #5226
Opened 2021-05-25 22:17 UTC by deep7102

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
- Added support for mobile view with Monthview.
- Fixed selected date was not stay on provided day/month/year.

**Related github/jira issue (required)**:
Closes #5075
Closes #5064

**Steps necessary to review your pull request (required)**:
Pull this branch and build/run the demo app

Test for 5075
- Navigate to:
- http://localhost:4000/components/monthview/example-inpage.html
- http://localhost:4000/components/monthview/test-inpage-variations.html
- Open developer tools
- Check the in-page styles [here](https://www.figma.com/file/ri2Knf3KchdfdzRAeds0Ab/IDS-Mobility-v4.6?node-id=1%3A5739)
- Check for Collapse, Hide Today, Hide Month Year Picker, Legend and No Toggleable
- If clicked the toolbar title or calendar icon will pulse and expand and pushing other content down the page.
- Text color for current month’s dates should be slate-8
- See each date hitbox minimum 40px
- Should be `pulse` animation back in for buttons and dates
- Legends, if single line should be left align and wrapped should center alignment
- Check the style for month and year picker

Test for 5064
- Navigate to: http://localhost:4000/components/calendar/test-provided-date.html
- See the selected date should be 4/21/2021

**Included in this Pull Request**:
- [x] A note to the change log.

2021-05-26 13:44 UTC, tmcconechy requested changes
This is looking really nice just some small suggestions

- instead of inpage call it inPage in the settings
- "No Toggleable" -> "Not Toggleable"
- the toolbar looks a little out of alignment
![Screen Shot 2021-05-26 at 9 41 51 AM](https://user-images.githubusercontent.com/814283/119670472-eb32fa80-be06-11eb-8a4c-c794923fec36.png)
- seeing an extra scrollbar
![Screen Shot 2021-05-26 at 9 42 38 AM](https://user-images.githubusercontent.com/814283/119670515-f38b3580-be06-11eb-8267-a3bec0b57a14.png)
- the colors we use in the legend are quite hard to see can we bring them each up one in the color scale?
<img width="371" alt="Screen Shot 2021-05-26 at 9 46 29 AM" src="https://user-images.githubusercontent.com/814283/119670991-61376180-be07-11eb-99f7-fc4d7c99c01a.png">

2021-05-26 13:44 UTC, tmcconechy commented on src/components/calendar-toolbar/calendar-toolbar.js
> +  inpage: false,
Suggest we call it inPage but thats very minor

2021-05-26 23:29 UTC, deep7102 commented
@tmcconechy Updated now, for all the points you see and there is no markup change only the api settings.

2021-05-27 13:32 UTC, deep7102 commented
It's ready to review now

2021-05-27 14:20 UTC, tmcconechy commented
Just one thing.... It looks like now the icon is quite far away?

<img width="286" alt="Screen Shot 2021-05-27 at 10 18 26 AM" src="https://user-images.githubusercontent.com/814283/119842905-1257fd80-bed5-11eb-824c-36e39282192f.png">

2021-05-27 17:47 UTC, tmcconechy commented
@kevinwhitedesign and had some comments... 

- [x] Remove the tags
- [ ] Make header sticky and scrollable

I fixed the first one but the second one i will do when we add swipe and this is a seperate ticket https://github.com/infor-design/enterprise-wc/issues/133

Please review this live links and if any comments on this please do let us know here:

https://5075-datepicker-mobility-enhancements-enterprise.demo.design.infor.com/components/monthview/test-inpage-variations.html
https://5075-datepicker-mobility-enhancements-enterprise.demo.design.infor.com/components/monthview/example-inpage.html

cc @benfenton

2021-05-27 21:22 UTC, deep7102 commented
@tmcconechy Updated now, spacing icon vs title.

2021-05-28 14:32 UTC, tmcconechy approved these changes

2021-05-31 15:48 UTC, ericangeles commented
Very nice work, @deep7102! Just noticed a small issue on mobile viewport `320px`. If the month text is too long, some of the components gets cut off. Both classic and new themes.


<img width="366" alt="Screen Shot 2021-05-31 at 11 44 13 PM" src="https://user-images.githubusercontent.com/8839327/120216908-2d769480-c26a-11eb-84c9-0b6230bff349.png">

The right carat is missing, and the month text is cut off.

Am okay to pass this and fix it some other time.

2021-06-01 13:48 UTC, EdwardCoyle reviewed
@deep7102 Everything looks good here!  I saw what @ericangeles mentioned as well but seems to be OK on most iOS simulators (see below).  I'd be OK punting on it for now

![Screen Shot 2021-06-01 at 9 46 27 AM](https://user-images.githubusercontent.com/3249601/120334284-840dbe00-c2be-11eb-89ba-48c891fb2aff.png)

2021-06-01 13:49 UTC, EdwardCoyle approved these changes

2021-06-01 13:55 UTC, ericangeles approved these changes

2021-06-01 14:04 UTC, merged