5146 spinbox issue in responsive view
infor-design/enterprise pull request #5243
Opened 2021-05-31 05:46 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the spinbox and its border not properly rendered on responsive view.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5146

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/form/example-inputs.html
- Open Developer Console
- Make it responsive to 1577 x 836 50% or 75%

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2021-05-31 16:22 UTC, ericangeles requested changes
@tjamesallen15 , looks like there's a failing visual regress. We can talk about the fix offline.

2021-06-01 03:19 UTC, ericangeles requested changes

2021-06-01 03:19 UTC, ericangeles commented on src/components/input/_input-mixins.scss
> +  &:not(.spinbox):hover {
This probably causes visual regress. You might want to override it in the spinbox CSS file specifically.

2021-06-01 13:23 UTC, tmcconechy commented
![Screen Shot 2021-06-01 at 9 23 18 AM](https://user-images.githubusercontent.com/814283/120330652-04322480-c2bb-11eb-9b1b-0978767d8db6.png)

Also seeing at this dimension that it has a strange lighter border on the buttons

2021-06-01 14:19 UTC, tjamesallen15 commented
Hello @tmcconechy , 
I will check this one. Thanks!

2021-06-01 15:06 UTC, merged