NG1044 - Fix missing custom attributes in datepicker input and trigger
infor-design/enterprise pull request #5249
Opened 2021-06-01 13:53 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes missing custom attributes when using the `settings.attributes` in datepicker input and trigger button in enterprise and angular wrapper.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise-ng/issues/1044

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datepicker/example-index
- Open the developer tools
- Inspect the datepicker input, and should see data-automation-id="custom-automation-id"
- Then check the datepicker trigger button, and should see data-automation-id="custom-automation-id" and id="custom-id"

Optional Testing on Angular Wrapper
- Open the NG Repo (build and start the app)
- Link the `dist` folder of enterprise to the `node_modules` enterprise dependency to override the build in enterprise
- In `src\app\datepicker\datepicker.demo.html` add `[attributes]="[{ name: 'data-automation-id', value: 'my-custom-dp1' }]` to the Standard Date section of datepicker
- Open http://localhost:4200/ids-enterprise-ng-demo/datepicker
- Inspect the `Standard Date` datepicker
- You should be able to see `data-automation-id="my-custom-dp1"` in input field
- You should be able to see `data-automation-id="my-custom-dp1"` in trigger

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-06-01 13:56 UTC, tmcconechy submitted a review, later dismissed

2021-06-01 14:01 UTC, ericangeles commented
@tmcconechy I made the fix on failing functional test on James' PR https://github.com/infor-design/enterprise/pull/5243

2021-06-01 14:17 UTC, EdwardCoyle requested changes
@ericangeles see below:

2021-06-01 14:17 UTC, EdwardCoyle commented on src/components/datepicker/datepicker.js
> +    utils.addAttributes(this.trigger, this, this.settings.attributes);
@ericangeles I think this might need adjusting.  The automated IDs for each piece of the component need to be different, so that a testing tool targeting elements using this custom ID doesn't accidentally grab the wrong element. The `utils.addAttributes` takes a [fourth argument](https://github.com/infor-design/enterprise/blob/main/src/utils/utils.js#L1307) that acts as a suffix, which can be used to differentiate the two elements.  I'd suggest just adding a `trigger` suffix to the second one:

```suggestion
    utils.addAttributes(this.trigger, this, this.settings.attributes, 'trigger');
```

2021-06-02 13:14 UTC, EdwardCoyle approved these changes

2021-06-02 13:25 UTC, deep7102 approved these changes

2021-06-02 14:42 UTC, merged