5202 lookup attributes not added on buttons
infor-design/enterprise pull request #5264
Opened 2021-06-03 08:31 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes where lookup attributes are not added in the cancel and apply/save button.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5202

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/lookup/example-index.html
- Click on the first lookup so the dialog is opened
- Open dev tools
- Inspect the cancel button

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-06-03 15:49 UTC, tmcconechy submitted a review, later dismissed
Fix looks good. I also am trying to fix the test suite so i put that here...

2021-06-03 16:20 UTC, deep7102 approved these changes

2021-06-03 17:21 UTC, EdwardCoyle requested changes

2021-06-03 17:21 UTC, EdwardCoyle commented on src/components/modal/modal.js
> +          utils.addAttributes(btnItem, self, self.settings.attributes, 'cancel', true);
@tjamesallen15 This has an unexpected effect on Modals that have non-primary buttons that aren't necessarily labelled "close" or "cancel".  We didn't really have a good test for this setup anywhere, so I pushed one to this branch: http://localhost:4000/components/modal/test-inline-buttons.html.  If you open the modal on that page and inspect the first button (non-primary) you can see it labelled as a cancel button.

I was trying to think of a more generic way we can handle this, and realized that the actual ID for all of these Modal buttons is generated here: https://github.com/infor-design/enterprise/blob/main/src/components/modal/modal.js#L533 -- there is a section beneath that attempts to add a close handler for cancel buttons.  It might be better to remove the fix from here and rework it into that logic (you'd be able to accurately identify cancel buttons in this spot).

2021-06-04 03:03 UTC, tjamesallen15 commented on src/components/modal/modal.js
> +          utils.addAttributes(btnItem, self, self.settings.attributes, 'cancel', true);
Hello @EdwardCoyle , will check this one. Thanks for this one!

2021-06-04 05:03 UTC, tjamesallen15 commented on src/components/modal/modal.js
> +          utils.addAttributes(btnItem, self, self.settings.attributes, 'cancel', true);
@EdwardCoyle I saw the code there. We can definitely put the code there. Although the example-index in the lookup don't have a class "btn-cancel" for the Cancel button.

2021-06-07 13:27 UTC, tmcconechy commented on src/components/modal/modal.js
> +          utils.addAttributes(btn.element, this, self.settings.attributes, 'save', true);
I still think we cant assume these are all save buttons. So for an ID name i would suggest something more generic like `primary` for primary. I think we can assume `btn-cancel` is ok as cancel.

2021-06-08 13:37 UTC, tmcconechy commented on src/components/modal/modal.js
> +          console.log('hotdog');
We can remove this...

2021-06-08 13:37 UTC, tmcconechy commented on src/components/modal/modal.js
>            utils.addAttributes(btn.element, this, self.settings.attributes, 'save', true);
Suggest:
```
utils.addAttributes(btn.element, this, self.settings.attributes, 'primary', true);
```

2021-06-09 13:59 UTC, tmcconechy approved these changes
Works for me for now. Thanks @tjamesallen15

2021-06-09 14:09 UTC, tjamesallen15 commented
> Works for me for now. Thanks @tjamesallen15

Welcome @tmcconechy , anytime :)

2021-06-10 13:16 UTC, tmcconechy approved these changes

2021-06-10 14:21 UTC, ericangeles approved these changes

2021-06-11 13:30 UTC, EdwardCoyle approved these changes

2021-06-11 13:56 UTC, merged