5250 - Added card variations (Status, Hyperlink and Photo Card) with improve hitboxes for tapping
infor-design/enterprise pull request #5265
Opened 2021-06-03 08:55 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will add card variations (Status, Hyperlink and Photo Card) with improve hitboxes for tapping

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5250

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/cards/example-variations-hitboxes.html
- Check the cards

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2021-06-03 19:11 UTC, EdwardCoyle submitted a review, later dismissed
LGTM 👍

2021-06-03 20:57 UTC, deep7102 requested changes
Hi @tjamesallen15 looking good, one thing see the status can be different types user can use, so should add all other colors alert, error, info, success -so thinking should use combination of two classes card-content-status and one from any color: alert, error, info, success

```
class="card-content-status error"

class="header-status alert"

2021-06-04 03:03 UTC, tjamesallen15 commented
Hello @deep7102 , Will gladly do that! Thanks for the comment!

2021-06-04 13:32 UTC, tmcconechy requested changes
Looks good But two minor things

2021-06-04 13:32 UTC, tmcconechy commented on app/views/components/cards/example-variations-hitboxes.html
> +                <div class="card-content-status sucess">
Is this used? Wondering as it is spelled wrong should be success so might need a change here for that

2021-06-04 13:32 UTC, tmcconechy commented on app/views/components/cards/example-variations-hitboxes.html
> +    <h2 class="fieldset-title">Status (Item)</h2>
Can you move all the h2 into a column div (this will layout out the titles better)
```
<div class="row">
  <div class="one-third column">
   <h2 class="fieldset-title">Status (Item)</h2>
  </div>
</div>
```

2021-06-04 14:49 UTC, tjamesallen15 commented on docs/CHANGELOG.md
> +- `[Cards]` Added card variations (Status, Hyperlink and Photo Card) with improve hitboxes for tapping. ([#5250](https://github.com/infor-design/enterprise/issues/5250))
@tmcconechy my bad on this one.

2021-06-04 14:50 UTC, tmcconechy approved these changes

2021-06-09 13:54 UTC, deep7102 approved these changes

2021-06-09 14:00 UTC, merged