5219 - Fixed Bug Issue for Highlighted Text in New Light Default Theme Header
infor-design/enterprise pull request #5293
Opened 2021-06-09 15:59 UTC by RiyaTayal20

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the contrast of the highlighted text within the header when using the new light default theme

**Related github/jira issue (required)**:

Closes #5219 

**Steps necessary to review your pull request (required)**:

- Pull this branch down, then build and run the app
- Go to http://localhost:4000/components/personalize and select an example form
- Check if the header looks like the following when highlighted:
<img width="1439" alt="example-form-2-text-selection" src="https://user-images.githubusercontent.com/52171753/121388988-f06d6a80-c919-11eb-974b-e528506cd862.png">

**Included in this Pull Request**:
- [x] A note to the change log.

2021-06-10 14:01 UTC, tmcconechy submitted a review, later dismissed
Looks great to me

2021-06-11 13:42 UTC, EdwardCoyle requested changes
@RiyaTayal20 found a small thing below:

2021-06-11 13:42 UTC, EdwardCoyle commented on src/components/input/_input.scss
> +  background: $ids-color-palette-azure-90;
This color change is affecting the whole document, including some opposite-color text in the page body.  You may want to try keeping the original color overall, and scoping selections of this color strictly to `.header` components:

<img width="1116" alt="Screen Shot 2021-06-11 at 9 36 52 AM" src="https://user-images.githubusercontent.com/3249601/121695330-f63d8a00-ca98-11eb-8187-d631be8b38be.png">

2021-06-11 13:48 UTC, tmcconechy commented on src/components/input/_input.scss
> +  background: $ids-color-palette-azure-90;
good catch -> i think it should be constrained under is-personalize class so the change should be here https://github.com/infor-design/enterprise/blob/main/src/components/personalize/personalize.styles.js#L10

Glad you caught that because i missed it @EdwardCoyle

2021-06-11 14:01 UTC, tmcconechy commented
Also this may be why the visual tests failed as well. So see if you can fix @EdwardCoyle 's comment and then maybe you dont need to do the images

2021-06-14 13:35 UTC, tmcconechy commented on src/components/personalize/personalize.styles.js
> +  background: ${colors.selection} !important;
```suggestion
  background: ${colors.darker} !important;
```

Not sure if this will work better if you just change it for all elements inside a is-personalizable area?

But what is wierd is i dont see it working at all on this page?
http://localhost:4000/components/personalize/example-form.html

2021-06-14 14:14 UTC, EdwardCoyle commented on src/components/personalize/personalize.styles.js
> +  background: ${colors.selection} !important;
@tmcconechy @RiyaTayal20 I think we're still missing a CSS rule for `::selection` to be applied to headers without personalization rules on this PR

2021-06-14 14:16 UTC, EdwardCoyle commented on src/components/personalize/personalize.styles.js
> +  background: ${colors.selection} !important;
Probably need one here somewhere: https://github.com/infor-design/enterprise/blob/main/src/components/header/_header.scss#L15

2021-06-14 15:00 UTC, RiyaTayal20 commented on src/components/personalize/personalize.styles.js
> +  background: ${colors.selection} !important;
Oh this is what I pushed on Friday so you would be able to see what was going on @EdwardCoyle this issue hasn't been finalized yet.

2021-06-14 15:17 UTC, tmcconechy commented
ok @RiyaTayal20 we have a label for WIP we usually put on and then people won't reveiw your PR then we take it off when its ready. Addit for you

2021-06-16 13:52 UTC, tmcconechy commented
@RiyaTayal20 is this ready to review again or not yet?

2021-06-18 19:04 UTC, EdwardCoyle approved these changes
👍  Nice fix, great job @RiyaTayal20!

2021-06-18 19:26 UTC, tmcconechy approved these changes

2021-06-18 19:26 UTC, merged