5252 - Add improvements to the Expandable Cards
infor-design/enterprise pull request #5295
Opened 2021-06-09 19:21 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR improves the expandable cards without any changes to the old one. 

Has ability to:
- rotate the button actions vertically
- use expandable cards (You can still use the old implementation)

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5252

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/cards/example-expandable-cards.html
- Click the header, it should expand the card pane
- Check the look and feel and compare to the design

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2021-06-10 14:08 UTC, tmcconechy requested changes
This looks good only a few PR suggestions

1) Add testing id's api
2) When clicking the buttons im not seeing the "pulse" animation. I see one button is missing the classes so that could be the issue 
```
<button type="button">
                        <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
                          <use href="#icon-caret-right"></use>
                        </svg>
                    </button>
```
3) Could also add a couple tests , maybe just one e2e with the expander open?
4) The text seems to sit lower than the design
<img width="235" alt="Screen Shot 2021-06-10 at 10 08 46 AM" src="https://user-images.githubusercontent.com/814283/121539651-dbeda880-c9d3-11eb-8b21-8e0aeb90a0f7.png">

2021-06-10 14:08 UTC, tmcconechy commented on src/components/cards/cards.js
> +    if (!this.id || this.id === undefined) {
We could add the utils.addAttributes here as it will be needed for id's

2021-06-10 14:19 UTC, ericangeles commented
@tmcconechy just waiting for your feedback before I add some e2e. :)

2021-06-11 13:56 UTC, EdwardCoyle approved these changes
@ericangeles Nicely done 👍

2021-06-11 13:59 UTC, tmcconechy commented
Looks Great!

2021-06-11 13:59 UTC, tmcconechy approved these changes

2021-06-11 13:59 UTC, merged