5284 - Fixed Bug Issue in Mobile View of Weight Range Slider
infor-design/enterprise pull request #5327
Opened 2021-06-17 13:30 UTC by RiyaTayal20

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the problem of overlapping in mobile view regarding the weight range slider

**Related github/jira issue (required)**:
Closes #5284 

**Steps necessary to review your pull request (required)**:
- Pull this branch down, then build and run the app
- Go to http://localhost:4000/components/page-patterns/example-settings-page.html
- Open up mobile view
- Check to make sure that the weight range slider doesn't overlap the sales amount text area. 
<img width="771" alt="Screen Shot 2021-06-17 at 9 16 19 AM" src="https://user-images.githubusercontent.com/52171753/122405606-2f20a780-cf4e-11eb-81b1-a48440b3622f.png">

**Included in this Pull Request**:
- [ ] A note to the change log.

2021-06-17 14:11 UTC, RiyaTayal20 commented on src/components/input/_input.scss
> +  margin-bottom: 36px;
I realize that this is what is causing the tests to fail and I know why so it just requires a change on my part.

2021-06-17 14:13 UTC, tmcconechy commented on src/components/input/_input.scss
> +  margin-bottom: 36px;
Yeah we cant change this it would be problematic. Have to isolate the fix more

2021-06-17 16:25 UTC, ericangeles approved these changes

2021-06-17 16:25 UTC, ericangeles commented on src/components/input/_input.scss
> +#example-settings-page-field {
@RiyaTayal20 I wouldn't recommend to use id as a selector.

2021-06-17 16:25 UTC, ericangeles commented on app/views/components/page-patterns/example-settings-page.html
> +                <div class="field" id="example-settings-page-field">
You might wanna use `top-padding` class and get rid of the the ids.

2021-06-17 16:28 UTC, ericangeles requested changes
I mistakenly select approve instead of request changes. See all the comments.

2021-06-18 07:40 UTC, ericangeles approved these changes
LGTM! 🎉

2021-06-18 14:58 UTC, tmcconechy approved these changes

2021-06-18 14:58 UTC, merged