NG#1046 - Fix unwanted navigation/link after using destroy method
infor-design/enterprise pull request #5356
Opened 2021-06-23 22:00 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes unwanted navigation/link after using the destroy method on popupmenu. Click event should call preventDefault method to stop the browser from setting the hash.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1046

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/popupmenu/test-unwanted-navigation-when-menu-destroyed.html
- Click `Normal Menu` button
- Click the first menu item `Menu Option #1`
- Click again the Popupmenu button
- It should destroy it and should not open
- Hash should not be appended in URL

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2021-06-24 13:25 UTC, tmcconechy requested changes
Can this go at the click event on line 1021? That way it will get detached in the detach event.
 If not can you add a namespace and turn it off in the detatch event?

2021-06-25 13:22 UTC, tmcconechy reviewed
To be safe, I think just need to add `click.btn-menu.${this.id}` to:

 https://github.com/infor-design/enterprise/blob/049220606043b978fe2eb694fd3ae1ee4b80367b/src/components/popupmenu/popupmenu.js#L2334

2021-06-28 13:37 UTC, tmcconechy approved these changes

2021-06-28 16:20 UTC, EdwardCoyle approved these changes

2021-06-28 16:30 UTC, merged