4863 - Fix list not showing on autocomplete when the character type i…
infor-design/enterprise pull request #5359
Opened 2021-06-24 09:12 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes a bug where accordion list will not show again if the character typed on autocomplete input is not available in the words on the list.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/4863

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/applicationmenu/example-personalized.html
- Click inside the search field box and type in "zzzzzz" 
- Remove the word "zzzz" and clear the search.

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2021-06-24 10:45 UTC, ericangeles commented
@tjamesallen15 looks like a couple of pages affect this fix

https://github.com/infor-design/enterprise/pull/5359/checks?check_run_id=2903244916

2021-06-24 10:53 UTC, ericangeles requested changes
@tjamesallen15 looks like a couple of pages were affected by this fix.

https://github.com/infor-design/enterprise/pull/5359/checks?check_run_id=2903244916

2021-06-25 13:30 UTC, tmcconechy requested changes
I see a related bug now. If you type zzz and hit the x the x button no longer is also clearing the app menu

2021-06-28 13:28 UTC, tmcconechy commented
@tjamesallen15 i found one more case that is not working. Maybe we need another or different key event (keypress or input?)

- go in the field and type zzzzzz
- select all text and press cmd+x (cut)

2021-06-29 14:32 UTC, tmcconechy commented on src/components/applicationmenu/applicationmenu.js
> +    $(document).on('input.applicationmenu', () => {
I think we need to add a tear down to https://github.com/infor-design/enterprise/blob/main/src/components/applicationmenu/applicationmenu.js#L717 maybe?

2021-06-29 15:44 UTC, tjamesallen15 commented on src/components/applicationmenu/applicationmenu.js
> +    $(document).on('input.applicationmenu', () => {
Hello @tmcconechy , I added the teardown right under line 741. Did I put it wrong?

2021-06-29 16:20 UTC, tmcconechy approved these changes

2021-06-30 07:04 UTC, ericangeles approved these changes

2021-06-30 07:04 UTC, merged