5351 - Fix close button alignment in multiselect tags
infor-design/enterprise pull request #5360
Opened 2021-06-24 09:59 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the dismissible button icon were not properly aligned in classic mode (all browsers).

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/5351

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/multiselect/example-index.html
- Test/Check on different themes and different modes
- Test/Check on all browsers (Chrome, Firefox, Safari, Edge)
- The dismissible/close icon should properly align with the text

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2021-06-24 13:34 UTC, tmcconechy requested changes
It looks a little out of alignment in classic mode / safari
And a lot more on classic mode / firefox

2021-06-24 14:43 UTC, ericangeles commented
@tmcconechy this is what am getting on safari classic mode

<img width="342" alt="Screen Shot 2021-06-24 at 10 38 13 PM" src="https://user-images.githubusercontent.com/8839327/123282932-7eae3700-d53d-11eb-8b9e-52f15b21d308.png">
<img width="329" alt="Screen Shot 2021-06-24 at 10 38 05 PM" src="https://user-images.githubusercontent.com/8839327/123282951-81a92780-d53d-11eb-8f2c-c69aa96de87e.png">
<img width="323" alt="Screen Shot 2021-06-24 at 10 37 58 PM" src="https://user-images.githubusercontent.com/8839327/123282956-8241be00-d53d-11eb-9b75-5b4d456e3d04.png">

But I verify that firefox still some issues.

2021-06-24 16:19 UTC, tmcconechy commented
Yeah in safari its maybe down 1px? Or could be on my end. Its not as bad as firefox for sure so would be willing to accept that

2021-06-25 13:31 UTC, tmcconechy approved these changes

2021-06-25 16:55 UTC, deep7102 approved these changes

2021-06-28 13:35 UTC, merged