Updated font color to white
infor-design/enterprise pull request #5421
Opened 2021-07-13 14:39 UTC by Jah25

Updated the ids-color-palette to -white in the hover case.

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Previously the font on data grid tags would be black when the row was hovered over in dark mode making it extremely difficult to read. 

![dark-tag](https://user-images.githubusercontent.com/5921264/125470566-0e559b21-b1c8-424e-b758-d7973f3991d1.png)

The font color has been updated to white to resolve this issue

![light-tag](https://user-images.githubusercontent.com/5921264/125470819-1fd6ef86-7ebb-4caa-a23d-6df742dfe3ec.png)

**Related github/jira issue (required)**:

Closes #5289 

**Steps necessary to review your pull request (required)**:

1) Pull this branch, build and run the application
2) navigate to here: http://localhost:4000/components/datagrid/example-alternate-row-shading.html?theme=new&mode=dark&colors=0066D4
3) hover over any of the data grid rows
4) tag background should change color, font color should remain white as depicted above.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-07-13 15:06 UTC, vivz753 approved these changes

2021-07-13 15:29 UTC, ericangeles commented
I see an issue here when you go to high contrast mode.

http://localhost:4000/components/datagrid/example-alternate-row-shading.html?theme=new&mode=contrast&colors=0066D4

<img width="243" alt="high-contrast" src="https://user-images.githubusercontent.com/8839327/125480018-794adf3a-abe1-4128-bde1-1cab4c23c648.png">

If the issue only persists in dark mode, I suggest using the `theme-new-dark.scss` (for the new) and `theme-classic-dark.scss` for classic.

2021-07-13 15:29 UTC, ericangeles requested changes
I see an issue here when you go to high contrast mode.

http://localhost:4000/components/datagrid/example-alternate-row-shading.html?theme=new&mode=contrast&colors=0066D4

<img width="243" alt="high-contrast" src="https://user-images.githubusercontent.com/8839327/125480018-794adf3a-abe1-4128-bde1-1cab4c23c648.png">

If the issue only persists in dark mode, I suggest using the `theme-new-dark.scss` (for the new) and `theme-classic-dark.scss` for classic.

2021-07-13 20:43 UTC, tmcconechy commented on docs/CHANGELOG.md
> +-`[Datagrid]` Fixed a bug where the font color on tags was black when a row was hovered over in dark mode. Font color now white. ([#5289] (https://github.com/infor-design/enterprise/issues/5289))
```suggestion
-`[Datagrid]` Fixed a bug where the font color on tags was black when a row was hovered over in dark mode. Font color now white. ([#5289](https://github.com/infor-design/enterprise/issues/5289))
```

2021-07-13 20:48 UTC, tmcconechy requested changes
@Jah25 reviewing this behavior i think maybe we should fix it another way. 
Can you try to change it so that when you hover the that the tag color doesnt need to change (like the hyperlink column).

So i think to do that you just need to remove the `.tag` part of this nasty selector...

```
.datagrid > tbody > tr.is-hover-row:not(.error):not(.is-rowdisabled):not(.datagrid-virtual-row-bottom):not(.is-selected):not(.is-rowactivated):not(.datagrid-expandable-row) td:not(.is-editing):not(.is-readonly):not(.error) .tag:not(.info):not(.good):not(.error):not(.alert)
```

2021-07-14 12:45 UTC, Jah25 commented
@tmcconechy just to clarify, on hover neither the tag background color or text color will change.

2021-07-14 12:49 UTC, Jah25 commented
oh and should I keep the change for the azure version of the tag or revert that to using the ids-palette-white

2021-07-14 12:58 UTC, tmcconechy commented
Correct, i'm thinking that makes more sense just the row background changes, tag background and text stays as it was.

2021-07-14 13:18 UTC, Jah25 commented
So in testing the new light theme I noticed some contrast issues with the background 

![image](https://user-images.githubusercontent.com/5921264/125627314-15f83351-4b68-4a6f-b67f-c26b160aa757.png)

![image](https://user-images.githubusercontent.com/5921264/125627460-502bba8b-7355-41f0-b321-3adb0afc1434.png)

I'm also seeing similar issue with all the classic themes

![image](https://user-images.githubusercontent.com/5921264/125627888-2d7dfb40-49c7-4518-8825-7f1d172f7d08.png)

![image](https://user-images.githubusercontent.com/5921264/125628004-e4bcae06-8f98-417e-a7ce-99976e01192b.png)

![image](https://user-images.githubusercontent.com/5921264/125628411-eaf10e60-7b51-4bc2-aa8d-274fcc17460c.png)

Do we have leeway to experiment with the row highlight color or is that a locked in design decision?

2021-07-14 13:22 UTC, tmcconechy commented
It would probably be ok to change the contrast highlight color a little but it can't be that drastic of a change. Looking at the screen shots i guess its not that bad but could be better on contrast themes.

This is really just a hover state for selection. But make a suggestion.

2021-07-14 13:55 UTC, tmcconechy commented
Actually thinking about this probably better to fix this the minimal way possible (no design changes just fix the tag).

2021-07-14 14:07 UTC, Jah25 commented
got it so the desired change is: no change to tag background-color or font color on hover.

2021-07-14 14:12 UTC, ericangeles commented
Suggestion: Maybe create a global variable name for the color tag when it hovers and the default color is white, then just change the value of it on dark mode, since the issue is only shown in that particular area.

2021-07-14 14:20 UTC, Jah25 commented
@ericangeles so for the font color I did add a variable $datagrid-badges-hover-font-color; that is defaulted to white in the config and then changed at the theme level.

2021-07-14 14:46 UTC, Jah25 commented
@tmcconechy since this has been merged into main should I leave it be or move forward with the requested change for the tag background color?

2021-07-14 16:03 UTC, tmcconechy commented
@Jah25 that notification your seeing is just that someone merged main on your branch because something else was merged. Just go ahead and continue, nothing was merged into main yet

2021-07-14 17:32 UTC, tmcconechy commented
Minor lint error on https://github.com/infor-design/enterprise/pull/5421/checks?check_run_id=3069038899#step:9:62

Also i see what you mean with the grey tags on Light/New Theme when you hover. This isnt a major issue because of the variations so what i would do for that is just update the example a little.

SO change this line https://github.com/infor-design/enterprise/blob/main/app/views/components/datagrid/example-alternate-row-shading.html#L29

```
ranges: [{'min': 151, 'max': 9999, 'classes': 'azure07'}, {'min': 0, 'max': 150, 'classes': 'slate03'}]
```

So basically change the example to show different colors. As this is only an issue in one single situation.

Also are both new variables used:

```
$datagrid-badges-hover-font-color: $ids-color-palette-black;
$datagrid-badges-azure-font-color: $ids-color-palette-white;
```

If im reading it correctly on one is?

2021-07-14 19:13 UTC, Jah25 commented
@tmcconechy oh yup thanks for pointing that out I forgot to pull the text color variable, I'll update that and update the example for the tag issue.

2021-07-14 20:03 UTC, Jah25 commented
Hey @tmcconechy I'm getting a fail on the build from popup menu button api that I didn't touch is this a known issue?

2021-07-14 20:13 UTC, tmcconechy commented
A couple tests randomly fail. I've seen this one before. Did a rerun - this should fix

2021-07-15 13:31 UTC, tmcconechy approved these changes

2021-07-15 13:39 UTC, EdwardCoyle approved these changes

2021-07-15 15:32 UTC, ericangeles approved these changes

2021-07-15 15:33 UTC, merged