remove comments from PR for issue #5336, adjust the row height of act…
infor-design/enterprise pull request #5433
Opened 2021-07-15 17:53 UTC by vivz753

…ion item for XS and S datagrid

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-07-15 18:32 UTC, vivz753 commented on src/components/datagrid/_datagrid-new.scss
> +      min-height: 42px;
I had to increase the row height by 1px, is this okay? @tmcconechy 

Otherwise the only option was to decrease the button height by 1px

2021-07-15 18:33 UTC, tmcconechy commented on src/components/datagrid/_datagrid-new.scss
> +      min-height: 42px;
Actually probably better to decrease the button height (less possible visual regressions)

2021-07-15 23:25 UTC, vivz753 commented on src/components/datagrid/_datagrid-new.scss
> +      min-height: 42px;
Done.

Fixed it by overriding the btn class min-height, scoped in the datagrid row height as you suggested

2021-07-16 14:02 UTC, tmcconechy requested changes
Something about this change had a pretty big effect on visual regressions https://github.com/infor-design/enterprise/pull/5433/checks?check_run_id=3081733601#step:11:3336

Im thinking that for this maybe we can't add those `datagrid-cell-wrapper` changes? But not seeing what it is. If you can investigate all those changes then maybe this is fine.

But also i would target the more specific button i this case (it could be that as well)

2021-07-16 14:04 UTC, tmcconechy commented on src/components/datagrid/_datagrid-new.scss
> +    [class^='btn'] {
```suggestion
    [class^='btn'] {
```

Target `row-btn` to be safe

Should we

2021-07-16 14:06 UTC, tmcconechy commented on src/components/datagrid/_datagrid.scss
> +$datagrid-small-row-height: 26px;
Actually its probably this change causing the issues. I guess this is ok but its going to need all those images checked / tested and updated.

2021-07-16 14:58 UTC, vivz753 commented on src/components/datagrid/_datagrid.scss
> +$datagrid-small-row-height: 26px;
Done

2021-07-16 15:02 UTC, vivz753 commented on src/components/datagrid/_datagrid-new.scss
> +    [class^='btn'] {
Done

2021-07-16 16:40 UTC, tmcconechy reviewed
I'm not 100% sure about this change given the number of visual regressions https://github.com/infor-design/enterprise/pull/5433/checks?check_run_id=3087816785#step:11:3028

I'm thinking it might be easier to remove all these changes and just change `row-button` heights in each of the 4 row heights (total 4 rules)

2021-07-16 18:13 UTC, vivz753 commented
Just went through and redid all the previous changes--more simple and less visual changes. I think it might still complain about visual regression because for Medium, I moved the button up by 1 px. However for Extra Small and Small, the row inconsistencies have been fixed by reducing button heights and adjusting min-heights. Should be a lot better than the previous changes which edited a lot of padding within the row.

2021-07-16 18:20 UTC, vivz753 commented on src/components/datagrid/_datagrid.scss
> +          height: 24px;
Fixes the XS button height

2021-07-16 18:21 UTC, vivz753 commented on src/components/datagrid/_datagrid.scss
> +          height: 31px;
Fixes the M button height

2021-07-16 18:21 UTC, vivz753 commented on src/components/datagrid/_datagrid.scss
> +          min-height: 24px;
Also XS button height

2021-07-16 18:22 UTC, vivz753 commented on src/components/datagrid/_datagrid.scss
> +        top: 1px;
Centers XS button in middle of row

2021-07-16 18:23 UTC, vivz753 commented on src/components/datagrid/_datagrid.scss
> +      padding: 0px 5px 0;
Fixes row inconsistency for XS

2021-07-16 18:24 UTC, vivz753 commented on src/components/datagrid/_datagrid.scss
> -        top: -1px;
Got rid of this since it was overriding my `top` property in line 1802

2021-07-16 18:25 UTC, vivz753 commented on src/components/datagrid/_datagrid-new.scss
> +      top: 0px;
Push XS button 1px up since New buttons are a little bigger

2021-07-16 18:26 UTC, vivz753 commented on src/components/datagrid/_datagrid-new.scss
> +        min-height: 32px;
Fixes M button height in New

2021-07-19 14:45 UTC, tmcconechy commented
Seems like something changed on these pages compare:
http://localhost:4000/components/datagrid/example-compact-mode.html to https://main-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html

and http://localhost:4000/components/datagrid/test-frozen-columns-with-alert to https://main-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html

As far as i can tell they look similar. Have a look and if you agree i'll just update those images for this

2021-07-20 02:22 UTC, vivz753 commented
I don't see a speck of difference for the `test-frozen-columns-with-alert`

For the `example-compact-mode` the width of the columns are slightly different, but it could also be the fact that the Order Date data differs.

Looks fine to me, I say we go ahead and update the images. Let me know when you've done it, thanks!

2021-07-20 13:57 UTC, tmcconechy approved these changes
Ok Added the updated images. Also approving 👍🏻

2021-07-21 19:39 UTC, EdwardCoyle approved these changes
Nice work @vivz753, looks good now!

2021-07-22 05:27 UTC, ericangeles approved these changes

2021-07-22 05:58 UTC, merged