5332 - Fixed Bug Preventing Right Frozen Column Headers From Being Exported
infor-design/enterprise pull request #5450
Opened 2021-07-22 20:38 UTC by RiyaTayal20

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes the issue preventing the right frozen column headers from being properly exported to excel or csv.

**Related github/jira issue (required)**:

Closes #5332 

**Steps necessary to review your pull request (required)**:

- Pull this branch down, then build and run the app
- Go to http://localhost:4000/components/datagrid/example-frozen-columns.html
- Click on the more button and then select Export to Excel
- Open the excel document and see if "Product Id" and "Product Name" are seen
   <img width="1440" alt="Screen Shot 2021-07-22 at 4 37 01 PM" src="https://user-images.githubusercontent.com/52171753/126706314-4d0e96fd-77a5-4148-bfa7-79e167aa2e1f.png">

**Included in this Pull Request**:
- [x] A note to the change log.

2021-07-23 14:37 UTC, tmcconechy requested changes
@RiyaTayal20 the export is working but it looks like this introduced a bug. if you notice when you do the export the datagrid header disappears.

2021-07-23 14:47 UTC, RiyaTayal20 commented
I'll look into that.

2021-07-26 13:54 UTC, tmcconechy approved these changes

2021-07-27 00:49 UTC, ericangeles approved these changes

2021-07-27 00:49 UTC, merged