5285 - Add required asterisk to fileupload label
infor-design/enterprise pull request #5451
Opened 2021-07-23 01:47 UTC by davidcarlsonberg

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds the "required" asterisk to fileupload labels at page `components/fileupload/test-required`.

**Related github/jira issue (required)**:

Closes #5285 .

**Steps necessary to review your pull request (required)**:

- Pull branch, run app
- Visit http://localhost:4000/components/fileupload/test-required.html
- Ensure the required asterisk appears on required fields.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-07-23 09:38 UTC, ericangeles approved these changes

2021-07-23 10:32 UTC, hemantg05 commented
Is it a just a matter of adding required class to input field in test file?

The bug was discovered at the level on enterprise-ng. 

When we add required=true on label or when we add data-validate="required" on file upload input field, it should automatically show asterisk. It is not showing asterisk. 

```
<div class="field">

  <label
    soho-label
    for="file-upload"
    required="true">
    {{ label }}
  </label>

  <input
    id="file-upload"
    soho-alert
    data-validate="required"
    soho-fileupload
    soho-trackdirty
    (change)="onFileSelected($event)"
    (changeEvent)="onSelectedFileRemoved($event)"
    accept="{{ supportedFileTypes }}"/>

</div>
```

So, does this change on test file by adding a required class manually solve the underlying issue?

Please verify.
cc @tmcconechy, @davidcarlsonberg

2021-07-23 13:46 UTC, tmcconechy requested changes
@davidcarlsonberg as per the comments on https://github.com/infor-design/enterprise/issues/5285 can you try to make it work with a class on the label (the other ones do work this way)


```
 <div class="field">
      <label for="test-required" class="required">Upload a File</label>
      <input type="file" class="fileupload" id="test-required" name="test-required" data-validate="required">
    </div>
```

This part isnt working and maybe needs a code change

2021-07-25 13:59 UTC, davidcarlsonberg commented
Adding `required` class to the original label or `data-validate` to the input now places a `required` class (including asterisk) on the  visible label (`shadowLabel`);

2021-07-26 14:13 UTC, tmcconechy approved these changes

2021-07-27 01:31 UTC, ericangeles approved these changes

2021-07-27 01:31 UTC, merged