5441 - Fix automation ids not showing on legends, text and slices
infor-design/enterprise pull request #5483
Opened 2021-08-03 07:06 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes a bug where automation ids is not properly rendered on legend, text and slices in charts.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5441

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/donut/test-automation-attributes.html
- Open Inspect, check the legends, slices and text for automation ids.

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2021-08-03 14:34 UTC, tmcconechy requested changes
I guess a few tests need to be adjusted to the new id's https://github.com/infor-design/enterprise/pull/5483/checks?check_run_id=3228411132

2021-08-04 11:57 UTC, ericangeles commented
@tjamesallen15 I don't see automation ids for the chart labels.

<img width="714" alt="ids" src="https://user-images.githubusercontent.com/8839327/128176342-68801eb9-9e25-4c9b-97c2-4436d39e3c79.png">

2021-08-04 14:01 UTC, tmcconechy submitted a review, later dismissed
This looks good to me (we can add the ids to the lines too / that wouldnt hurt as @ericangeles says)

2021-08-05 06:57 UTC, ericangeles approved these changes

2021-08-05 13:11 UTC, tmcconechy approved these changes

2021-08-05 13:11 UTC, merged