5391 - Add modal custom tooltip for close button
infor-design/enterprise pull request #5491
Opened 2021-08-05 01:04 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds the ability to have a custom tooltip on modal close button.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5391

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/modal/test-custom-tooltip-close-btn.html
- Hover the close button to see the tooltip.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-08-05 13:26 UTC, tmcconechy requested changes
Seeing brackets around the text this can be removed by adding the setting. Please see comments

2021-08-05 13:26 UTC, tmcconechy commented on src/components/modal/modal.js
> +        <button type="button" class="btn-icon btn-close" title="${Locale.translate(this.settings.closeBtnOptions.closeBtnTooltip)}" aria-hidden="true">
```suggestion
        <button type="button" class="btn-icon btn-close" title="${Locale.translate(this.settings.closeBtnOptions.closeBtnTooltip),  { showAsUndefined: false, showBrackets: false }}" aria-hidden="true">
```

I think this will fix the issue with unneeded brackets 
![Screen Shot 2021-08-05 at 9 25 51 AM](https://user-images.githubusercontent.com/814283/128357540-37d1a340-4de2-4c31-aad4-70a18443d0cd.png)

2021-08-06 15:22 UTC, tmcconechy approved these changes

2021-08-06 15:28 UTC, tmcconechy commented
Oh, oops one lint error to fix 👍🏻

2021-08-09 13:29 UTC, tmcconechy commented
Just needs one image updated https://github.com/infor-design/enterprise/pull/5491/checks?check_run_id=3277690594 or should that have been effected?

2021-08-10 05:17 UTC, tjamesallen15 commented
Hello @tmcconechy 

Not sure if that's been affected by my fix. As I checked it, I can't see any visual changes. I also didn't change a single css file on this branch.

Thanks.

2021-08-10 06:29 UTC, ericangeles commented
I re-run the build, let see if it will fail again the same visual regress.

2021-08-10 10:51 UTC, ericangeles commented
Looks good to me now @tmcconechy @tjamesallen15 

@tmcconechy, I've noticed that the build check doesn't recognize if there's an update in the main anymore. I manually pulled the updates in main instead.

2021-08-10 12:54 UTC, ericangeles approved these changes

2021-08-10 13:15 UTC, tmcconechy approved these changes

2021-08-10 13:15 UTC, merged