5472 - Editor: Added tooltip in fontpicker
infor-design/enterprise pull request #5492
Opened 2021-08-05 07:36 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added tooltip in fontpicker in editor component.

**Related github/jira issue (required)**:

Closes #5472 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app
- Go to: http://localhost:4000/components/editor/example-customize-buttons
- Hover over the dropdown for font picker

**Included in this Pull Request**:
- [ ] A note to the change log.

2021-08-05 09:24 UTC, ericangeles approved these changes

2021-08-05 13:16 UTC, tmcconechy requested changes
Interesting bug here is that its missing the arrow on the tooltip (if you compare to other buttons). It could be related to the fact that that popup doesn't have an arrow but i think we should address that before QA just 
 reports it.

![Screen Shot 2021-08-05 at 9 15 17 AM](https://user-images.githubusercontent.com/814283/128356194-6c0a9457-cfe2-4f3e-9b5f-defb8296cf73.png)

2021-08-09 13:31 UTC, tmcconechy approved these changes

2021-08-09 13:40 UTC, EdwardCoyle approved these changes

2021-08-09 14:50 UTC, merged