5443: Message max-width is hardcoded in modal
infor-design/enterprise pull request #5508
Opened 2021-08-11 15:23 UTC by davidcarlsonberg

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Message max-width is hard-coded in modal so when title size is long the message width does not increase to the size of it's container.

**Related github/jira issue (required)**:

#5443 

**Steps necessary to review your pull request (required)**:

- Pull branch, run app, visit `http://localhost:4000/components/message/example-index.html`
- Click the `Huge title` button
- Notice the message text extends to the full width of it's container.
- Also notice that the modal now resizes toward it's max-width if the message text is long (this may be an undesired side-effect of simply removing the max-width from the message and perhaps we should consider placing a max-width setting option on modal and determine a default there)

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-08-12 13:51 UTC, tmcconechy requested changes
Yeah i dont think that behavior is going to be very good as the message looks "broken" at those lower break points.

I think what seems to work is to set `.modal-content .message` to `max-width: initial`
So maybe we can add a maxWidth setting instead where you can set the maxWidth to initial or any other value and it will override the default 368... then the example would just have maxWidth: 'initial'

Also could do this on a new page in the message folder so you dont need to update the visual regression image

2021-08-16 14:36 UTC, tmcconechy approved these changes

2021-08-16 14:45 UTC, deep7102 approved these changes

2021-08-16 15:08 UTC, tmcconechy approved these changes

2021-08-16 15:08 UTC, merged