Modal test forcustom tooltip for close button
infor-design/enterprise pull request #5515
Opened 2021-08-13 13:58 UTC by janahintal

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Create visual test for cards hitboxes example page from QA

**Related github/jira issue (required)**:

N/A

**Steps necessary to review your pull request (required)**:

1. pull this branch
2. build and run the app
3. run `npm run e2e:puppeteer modal`
4. It should pass.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-08-16 14:40 UTC, tmcconechy requested changes
@janahintal seems to be some lint errors https://github.com/infor-design/enterprise/pull/5515/checks?check_run_id=3322673112#step:9:38

you can run `npm run lint:ci` local

2021-08-23 13:29 UTC, tmcconechy commented on test/jest.config.js
> +  testTimeout: 15000,
15 seconds for single test is quite a lot. I think maybe we need to avoid the timeouts on the test. Should not increase this as it promotes bad habits. Will comment on the other test

2021-08-23 13:31 UTC, tmcconechy commented on test/components/modal/modal.puppeteer-spec.js
> +    await page.waitForTimeout(600);
Instead of these timeouts can you use `await page.waitForSelector('.modal.is-visible.is-active', { visible: true });` instead. We want as few of `waitForTimeout` as possible and only very short ones or the test suite will become very slow. The max for one test should be 6 seconds

2021-08-23 13:31 UTC, tmcconechy commented on test/components/modal/modal.puppeteer-spec.js
> +    await page.waitForTimeout(200);
Are all these waitForTimeouts needed?

2021-08-23 13:57 UTC, janahintal commented on test/components/modal/modal.puppeteer-spec.js
> +    await page.waitForTimeout(600);
Thanks, Tim. I will try this. :)

2021-08-24 13:31 UTC, tmcconechy commented
Just some lint issues to fix 👍🏻  https://github.com/infor-design/enterprise/pull/5515/checks?check_run_id=3409216403#step:9:39

2021-08-25 13:37 UTC, tmcconechy commented on test/components/modal/modal.puppeteer-spec.js
> +    await page.waitForSelector('.modal.is-visible.is-active', { visible:true });
```suggestion
    await page.waitForSelector('.modal.is-visible.is-active', { visible: true });
```

2021-08-25 13:40 UTC, tmcconechy commented on test/components/modal/modal.puppeteer-spec.js
> +
```suggestion
```

2021-08-25 13:44 UTC, janahintal commented on test/components/modal/modal.puppeteer-spec.js
> +    await page.waitForTimeout(200);
Hi Tim, I reduced the timeout. Will push my changes later tonight. Thank you.

2021-08-25 13:45 UTC, tmcconechy approved these changes

2021-08-25 13:45 UTC, tmcconechy commented
Ok good. i fixed a few errors as i thought this was stalled @janahintal

2021-08-25 13:54 UTC, tmcconechy requested changes
One too long running test

2021-08-25 14:02 UTC, janahintal commented
> One too long running test

Hi Tim, I'm currently having timeout error on my last script. I will try another work around.

2021-08-25 14:21 UTC, tmcconechy commented
no problem - sounds good.

2021-09-01 13:35 UTC, tmcconechy approved these changes
Nice! 💯

2021-09-01 14:09 UTC, ericangeles approved these changes
@janahintal 🍌

2021-09-01 14:42 UTC, merged