5325 typography text style
infor-design/enterprise pull request #5523
Opened 2021-08-17 09:24 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds the typography paragraph text style

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5325

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/typography/example-line-height-text.html

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2021-08-17 14:25 UTC, tmcconechy reviewed
Are the styles on https://main-enterprise.demo.design.infor.com/components/emptymessage/example-widgets.html ok? If so that might be the only example we need.

WIth this example sometimes what happens at lower breakpoints is it gets squished.

![Screen Shot 2021-08-17 at 10 22 19 AM](https://user-images.githubusercontent.com/814283/129744053-3e0bb2d3-5533-455a-b128-f48698906bf0.png)

2021-08-18 13:26 UTC, tmcconechy commented on src/components/cards/_cards.scss
> +  &.typography {
This is still not 100% what i expect. Because basically we add a new class `typography` that is never going to be used and an example in http://localhost:4000/components/typography/example-line-height-text.html that has extra scrollbars ect and more for QA to flag.

I'd suggest to try a different approach

1) remove the example and code
2) update http://localhost:4000/components/emptymessage/example-widgets.html so the line height is increased as per the designs
3) add an example section for "paragraph text" at the bottom on  http://localhost:4000/components/typography/example-index.html that uses this line height it will use this rule which you can change https://github.com/infor-design/enterprise/blob/main/src/components/typography/_typography.scss#L99

2021-08-18 13:27 UTC, tmcconechy requested changes
Sorry this design is a little confusing i think i figured out the best thing to do here in this comment https://github.com/infor-design/enterprise/pull/5523/files#r691236299

2021-08-19 06:12 UTC, tjamesallen15 commented
Hopefully, this one I got it right.

2021-08-19 11:37 UTC, tjamesallen15 commented
I'll fix the e2e test issues once this fix is okay.

2021-08-19 14:52 UTC, tmcconechy submitted a review, later dismissed
Looks great now 👍🏻  thanks, go ahead and fix the e2e i think

2021-08-20 13:22 UTC, tmcconechy approved these changes

2021-08-20 14:16 UTC, ericangeles approved these changes

2021-08-20 14:16 UTC, merged