5428 - Datagrid: Title XSS Vulnerability
infor-design/enterprise pull request #5528
Opened 2021-08-17 19:43 UTC by davidcarlsonberg

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This change strips/sanitizes HTML added inside the name property of the columns array.

**Related github/jira issue (required)**:

#5428 

**Steps necessary to review your pull request (required)**:

- Pull branch
- Run app
- Visit http://localhost:4000/components/datagrid/test-xss-prevention.html
- Notice no code is executed when placed inside columns array as value for name property.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-08-18 13:41 UTC, tmcconechy requested changes
One small problem with this is we previously do allow some html in here. For example this fix breaks https://main-enterprise.demo.design.infor.com/components/datagrid/test-two-line-header.html (two line header with a `<br>`).

Try `xssUtils.stripTags = function (html, allowed) {` instead and then we can allow only any text elements to be safe. like maybe

```
xssUtils.stripTags(col.name, `<div><span><a><small><svg><i><b><use><br><strong><em>') : '';
```

2021-08-18 16:46 UTC, davidcarlsonberg commented
This seems like an odd test failure to me. Any ideas?
https://github.com/infor-design/enterprise/pull/5528/checks?check_run_id=3362038751#step:12:673

2021-08-18 16:56 UTC, tmcconechy commented
@davidcarlsonberg that one happens occasionally random. I just reran it and that should work

2021-08-19 14:57 UTC, tmcconechy approved these changes

2021-08-19 15:59 UTC, ericangeles approved these changes

2021-08-19 15:59 UTC, merged