5519 - Added filter mask options in datagrid
infor-design/enterprise pull request #5540
Opened 2021-08-20 03:35 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added filterMask and filterMaskOptions in column settings. Column masks and filter masks are now separate.

**Related github/jira issue (required)**:

Closes #5519 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app
- Go to: http://localhost:4000/components/datagrid/test-filter-mask.html
- Type on search filter row

**Included in this Pull Request**:
- [ ] Change in filter mask example page
- [ ] A note to the change log.

2021-08-20 13:46 UTC, tmcconechy requested changes
The logic for this needs to be such that it still uses col.mask if present or it's going to break for people. The idea is to use the existing mask/logic and add an option to have it different for the filter row if need be.

- if col.mask and no col.filterMask use  col.mask 
- if col.mask and col.filterMask use  col.filterMask for the filter row and col.mask

2021-08-23 10:17 UTC, ericangeles approved these changes
Looks good to me now! 🍌

2021-08-23 14:12 UTC, tmcconechy approved these changes

2021-08-23 14:14 UTC, tmcconechy approved these changes
Approving as this works now. I updated the example and test steps

2021-08-23 15:01 UTC, EdwardCoyle approved these changes

2021-08-23 15:21 UTC, ericangeles approved these changes

2021-08-23 15:21 UTC, merged