3941 deatagrid refresh single column
infor-design/enterprise pull request #5584
Opened 2021-09-07 17:29 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR adds the ability to update values of a specific column on Datagrid.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/3941

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-update-column.html
- Click on the Load Column

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-09-08 12:51 UTC, tmcconechy requested changes
I think this is actually updating every cell by calling updateCell in a loop? But try this:

1. change data to
```
        const dataset2 = [{
            productId: 1,
            productName: 'Bumpers 1',
            activity: 'Assemble Paint 1',
            quantity: 1
          }, {
            productId: 2,
            productName: 'Wheels 2',
            activity: 'Inspect and Repair 2',
            quantity: 2
          }, {
            productId: 3,
            productName: 'Suspension 3',
            activity: 'Cleaning 3',
            quantity: 1
          }
        ];
 ```
 
 1. hit update/load column
 1. would expect the productName column to not refresh only the one column should?

2021-09-08 12:51 UTC, tmcconechy commented on app/views/components/datagrid/test-update-column.html
> +            <span>Load Column</span>
```suggestion
            <span>Update Activity Column</span>
```

2021-09-09 13:49 UTC, tmcconechy submitted a review, later dismissed
Looks like its working as I expect now. Maybe you can add a functional test for this new API?

2021-09-09 15:31 UTC, tjamesallen15 commented
Sure @tmcconechy

2021-09-10 13:01 UTC, tmcconechy approved these changes
Nice test! Thanks!

2021-09-12 17:54 UTC, deep7102 approved these changes

2021-09-13 13:16 UTC, tmcconechy approved these changes

2021-09-13 13:16 UTC, merged