5640 - Fix line position when all values are zero
infor-design/enterprise pull request #5654
Opened 2021-09-24 17:42 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the position of the line chart when all values are zeros. The line chart should not be centered and it should be close to the names.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/5640

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/line/test-all-data-points-are-zero-look.html
- The line chart should be close below with the names and not be centered

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2021-09-27 13:51 UTC, tmcconechy requested changes
I can see one problem with this is that the transform 38% implies one specific height. If you make the widget a different height (for example class="widget double-height") then it wont be on the bottom.

One idea for a fix is maybe if the left side axis should be shown. So maybe if the scale is 0,0 you can default it to 0,100 and it will automatically work and also show something that way on the left side.

2021-09-28 13:58 UTC, ericangeles commented
@tmcconechy I also updated the test page to see both working on standard and double height.

2021-09-28 14:37 UTC, tmcconechy approved these changes
Ok this works 👍🏻

2021-09-29 13:19 UTC, tmcconechy approved these changes

2021-09-30 21:34 UTC, deep7102 approved these changes

2021-10-01 02:50 UTC, merged