Toasts: Created and converted test scripts to puppeteer
infor-design/enterprise pull request #5788
Opened 2021-10-26 13:41 UTC by jbrcna

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
✓ Create and convert toast component to puppeteer
✓ Add example draggable tests
✓ Add convenience functions
✓ Create helper function for drag and drop
✓ Improve simplicity and readability

I tried to explore drag n drop in puppeteer( and decided to convert the toast) and made the function overload. I don't know how to do method overloading  in javascript but it has the same context. you can use it with different types (args).

To verify drag and drop , Add screenshot line 331 and line 348

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

1. pull this branch
2. build and run the app
3. run npm run e2e:puppeteer toast
4. It should pass.
<img width="567" alt="image" src="https://user-images.githubusercontent.com/56722184/138888390-37cb005d-cb5d-4367-99df-4c83b1749023.png">

**Additional Context**
I also tried using drag n drop helper function to tab component. and it works :tada:

![Large GIF (1196x780)](https://user-images.githubusercontent.com/56722184/138889174-23805a73-7316-452b-a55d-add0da12a13d.gif)

![Large GIF (1196x780)](https://user-images.githubusercontent.com/56722184/138889209-a4278b2d-6d34-4897-8499-a7d2ca8ccc82.gif)

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.
- [ ] Drag Drop helper function

2021-11-01 15:40 UTC, tmcconechy approved these changes

2021-11-01 15:40 UTC, tmcconechy commented on test/components/toast/toast.puppeteer.spec.js
> +// const { toMatchImageSnapshot } = require('jest-image-snapshot');
For next time we prefer to not leave commented code in. instead delete it

2021-11-03 06:53 UTC, ericangeles requested changes

2021-11-03 06:53 UTC, ericangeles commented on test/components/toast/toast.puppeteer.spec.js
> +  describe.skip('Visual regression tests', () => {
Can you remove this? The same thing you did to your previous PR.

2021-11-03 06:53 UTC, ericangeles commented on test/components/toast/toast.puppeteer.spec.js
> +// expect.extend({ toMatchImageSnapshot });
Include this thanks

2021-11-03 06:57 UTC, ericangeles commented
Friendly reminder to always update your branch to the main branch to eliminate conflict files.

2021-11-04 00:10 UTC, jbrcna commented on test/components/toast/toast.puppeteer.spec.js
> +// const { toMatchImageSnapshot } = require('jest-image-snapshot');
Hello @tmcconechy  I apologize for the delay; I've been ooo since November 2nd. James also gave me some advice on commented code. I was waiting to see if there were any modifications to the message component PR so I could make any necessary changes to the other PRs. I'm simply curious if you also wish to remove these kinds of comments as well? 
<img width="918" alt="Checks if the Class Name of an element contains the given value" src="https://user-images.githubusercontent.com/56722184/140234689-d972a118-7603-4e73-a0a5-d83f1c01d95b.png">

2021-11-04 00:10 UTC, jbrcna commented on test/components/toast/toast.puppeteer.spec.js
> +  describe.skip('Visual regression tests', () => {
will surely do @ericangeles . I was waiting to see if there were any modifications to the message component PR so I could make any necessary changes to the other PRs

2021-11-04 00:10 UTC, jbrcna commented on test/components/toast/toast.puppeteer.spec.js
> +// expect.extend({ toMatchImageSnapshot });
yup. thanks @ericangeles

2021-11-04 00:11 UTC, jbrcna commented
this is duly noted. thank you @ericangeles

2021-11-04 00:15 UTC, tmcconechy commented on test/components/toast/toast.puppeteer.spec.js
> +// const { toMatchImageSnapshot } = require('jest-image-snapshot');
No problem @jbrcna 
To clarify comments like the methods docs you mentioned with comments to explain are very much encouraged. I just mean commented out JS code lines that we usually remove since they are part of the history or likely never needed.

2021-11-04 13:47 UTC, tmcconechy commented
Seems like other changes in this PR? Is it possible this came from another branch? Also can we try to limit the number of helper functions as these get hard to maintain. It might even be better to add testing patterns. I.E. documentation on how you do a drag operation ect and stick to the puppetteer basics but i'm not totally sure about that?

For now can we make sure only the helpers that are used are in?

2021-11-04 13:54 UTC, jbrcna commented
> Seems like other changes in this PR? Is it possible this came from another branch? Also can we try to limit the number of helper functions as these get hard to maintain. It might even be better to add testing patterns. I.E. documentation on how you do a drag operation ect and stick to the puppetteer basics but i'm not totally sure about that?
> 
> For now can we make sure only the helpers that are used are in?

Hi Tim, I didn't add any more helper function I just  add this comment. Also,I noticed that I named it as toast.puppeteer**.spec** so I rename it to toast.puppet**-spec**. 
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/56722184/140325615-ff1d9aa2-604c-4ea6-8159-32665f649793.png">

I also add the word “have” to line 85, 194, 205, 216, 227, 238, 249

2021-11-04 14:00 UTC, tmcconechy commented
ok, i guess there is a lot of changes from other PRs mixed in here? Maybe you can start a new pull request and close this with just the new test changes? https://github.com/infor-design/enterprise/pull/5788/files

2021-11-04 14:01 UTC, ericangeles commented
It seems that you're still doing the way you update your branch to your previous PR. If you need to update your current branch to the main just simply do `git pull origin main`. Once you update your branch to the remote main branch, those updated files shouldn't be carried over here.

Agree with @tmcconechy to limit the helper functions for now. The primary goal is to convert them first before doing those as we still need to identify what needs to be created.

2021-11-04 14:04 UTC, closed without merging