Toast: Create and convert toast component script to puppeteer
infor-design/enterprise pull request #5824
Opened 2021-11-05 05:27 UTC by jbrcna

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
✓ Create and convert toast component script to puppeteer

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

1. pull this branch
2. build and run the app
3. run npm run e2e:puppeteer toast
4. It should pass.
<img width="556" alt="image" src="https://user-images.githubusercontent.com/56722184/140462577-11a52d93-1ee6-45ab-9de5-89fe1b84eea9.png">

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-11-05 13:22 UTC, tmcconechy commented on test/helpers/e2e-utils.js
> +  checkListItem_1stnLastValue: async (listElement, firstItem, lastItem) => {
Can this util have a better name. I actually dont understand what its doing from the name?

2021-11-05 14:34 UTC, jbrcna commented on test/helpers/e2e-utils.js
> +  checkListItem_1stnLastValue: async (listElement, firstItem, lastItem) => {
Hello @tmcconechy , and thank you for your input. I honestly can't come up with a better name for that function. However, that function only checks the first and last item on the list (which is a <\ul> element). Here are my choices:

- checkListItemValue
- checkList_1stnLast_ItemValue
- checkListItem_1stnLastValue
- check1stnLastListItem
- check1stnLastElement
- check1stnLastElementOnTheList
- checkListElements
- check1standLastElementsOfaList

I've also solicited suggestions from my team and am awaiting responses.

2021-11-05 14:42 UTC, tmcconechy commented on test/helpers/e2e-utils.js
> +  checkListItem_1stnLastValue: async (listElement, firstItem, lastItem) => {
How many times is it being used? It seems like it shouldnt even be a util and should just be the contents of a test that checks the first and last on the list?

2021-11-05 14:51 UTC, jbrcna commented on test/helpers/e2e-utils.js
> +  checkListItem_1stnLastValue: async (listElement, firstItem, lastItem) => {
for the toast component I didn't used it but I was able to use it in `Pager` and `Datagrid`. and it can also be used for components that has a list element <\ul> structure, or if in case you want to check if you're on a certain page.

2021-11-05 14:59 UTC, ericangeles commented on test/helpers/e2e-utils.js
> +  checkListItem_1stnLastValue: async (listElement, firstItem, lastItem) => {
Why does it need to check the first and last?

2021-11-05 15:10 UTC, jbrcna commented on test/helpers/e2e-utils.js
> +  checkListItem_1stnLastValue: async (listElement, firstItem, lastItem) => {
Hi @ericangeles , to check if you're on a certain page.
<img width="669" alt="image" src="https://user-images.githubusercontent.com/56722184/140532568-e376869b-e305-4c52-8f77-48e70fae4e0a.png">
i.e.,to verify if you're on page 1. you check the items on the list. same goes with page 2 and so on

2021-11-05 16:42 UTC, tmcconechy commented on test/helpers/e2e-utils.js
> +  checkListItem_1stnLastValue: async (listElement, firstItem, lastItem) => {
Yeha this seems a little specific for a util. Maybe you just put it in the test itself even tho it repeats a bit. Usually that's what i would do...

2021-11-06 04:29 UTC, jbrcna commented on test/helpers/e2e-utils.js
> +  checkListItem_1stnLastValue: async (listElement, firstItem, lastItem) => {
I see​/​take your point. I'll work on it now. thanks for the advice :slightly_smiling_face:

2021-11-08 10:58 UTC, ericangeles requested changes

2021-11-08 10:58 UTC, ericangeles commented on test/components/toast/toast.puppeteer-spec.js
> +    it('should have Accessibility', async () => {
You can remove all the accessibility tests except in the `example-index`. No need to do it on every single test page.

2021-11-08 10:58 UTC, ericangeles commented on test/components/toast/toast.puppeteer-spec.js
> +    it('should display', async () => {
Can we be more specific? Perhaps `should display toast message`?

2021-11-08 10:58 UTC, ericangeles commented on test/components/toast/toast.puppeteer-spec.js
> +    it('should show the title', async () => {
Can also remove this.

2021-11-08 10:58 UTC, ericangeles commented on test/components/toast/toast.puppeteer-spec.js
> +    it('should show the title', async () => {
Remove this too. Title, accessibility and axe tests in the `example-index` should suffice.

2021-11-08 10:58 UTC, ericangeles commented on test/components/toast/toast.puppeteer-spec.js
> +  describe('Example-positions tests', () => {
`describe('Toast test-position tests', () => {`. We usually add the test page name to search it easily.

2021-11-08 14:23 UTC, tmcconechy commented on test/components/toast/toast.puppeteer-spec.js
> +    it('should display', async () => {
Also doesnt seem to have a check (like an expect()).

2021-11-10 02:26 UTC, jbrcna commented
<img width="550" alt="image" src="https://user-images.githubusercontent.com/56722184/140939162-c9f2e5d0-8c47-4bf3-88ae-34547cab787b.png">

2021-11-10 02:30 UTC, jbrcna commented on test/components/toast/toast.puppeteer-spec.js
> +    it('should have Accessibility', async () => {
this is now applied 🙂. sorry for the delay I was on leave yesterday.

2021-11-10 02:30 UTC, jbrcna commented on test/components/toast/toast.puppeteer-spec.js
> +    it('should display', async () => {
this is now renamed 🙂.

2021-11-10 02:30 UTC, jbrcna commented on test/components/toast/toast.puppeteer-spec.js
> +    it('should show the title', async () => {
this is now removed 🙂

2021-11-10 02:30 UTC, jbrcna commented on test/components/toast/toast.puppeteer-spec.js
> +  describe('Example-positions tests', () => {
this is now renamed 🙂. thanks for your review and suggestions @ericangeles.

2021-11-10 09:24 UTC, ericangeles approved these changes
Good job! 🍌

2021-11-10 15:41 UTC, tmcconechy approved these changes

2021-11-10 15:41 UTC, merged