5728 - Added option to disable primary trigger on field in modal
infor-design/enterprise pull request #5848
Opened 2021-11-10 23:33 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added an attribute that indicates if the primary button in modal will be clicked or not when pressing enter.

**Related github/jira issue (required)**:

Closes #5728 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/modal/example-index.html
- Type anything in "Problem (primary trigger disabled)" and press enter
- Dialog should not exit

**Included in this Pull Request**:
- [ ] A note to the change log.

2021-11-11 18:00 UTC, tmcconechy approved these changes

2021-11-11 18:09 UTC, tmcconechy requested changes
I think it makes more sense to make this as an option on the modal settings as whole. So maybe the name should be `supressEnterKey` or something like that and set it up in the modal settings.

Then maybe need an example based on example-index with the option set.

2021-11-12 08:25 UTC, ericangeles approved these changes

2021-11-12 14:17 UTC, tmcconechy approved these changes

2021-11-12 14:17 UTC, merged