5714 - Fix on Sink Page Tab Alignment
infor-design/enterprise pull request #5860
Opened 2021-11-12 06:32 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix the tab focus indicator in sink page tab alignment.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5714

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/
- Set focus on `Notes` tab

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-11-12 08:12 UTC, yohannahbautista requested changes

2021-11-12 08:12 UTC, yohannahbautista commented on docs/CHANGELOG.md
> +- `[Tabs]` Fix focus indicator in Sink Page. ([#5714](https://github.com/infor-design/enterprise/issues/5714))
I think this should be above Tabs-Vertical

2021-11-12 14:21 UTC, tmcconechy approved these changes
Looks good. And i think this also fixed https://github.com/infor-design/enterprise/issues/5837
So i added it but please also confirm.

2021-11-15 01:21 UTC, tjamesallen15 commented
> Looks good. And i think this also fixed #5837 So i added it but please also confirm.

Yep. I checked the #5837 and it was also fixed.

2021-11-15 08:27 UTC, yohannahbautista approved these changes
Looks good!

2021-11-15 14:16 UTC, merged