Input puppeteer test for #5606
infor-design/enterprise pull request #5862
Opened 2021-11-15 05:54 UTC by janahintal

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Input puppeteer test for #5606

**Related github/jira issue (required)**:

#5606 

**Steps necessary to review your pull request (required)**:

1. pull this branch
2. build and run the app
3. run `npm run e2e:puppeteer input`
4. It should pass.

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-11-15 11:49 UTC, tjamesallen15 requested changes
Looks good although we need to fix the lint issues. You can chat me if you have issues fixing it @janahintal I can help you with that.

2021-11-15 14:22 UTC, tmcconechy commented on test/jest-puppeteer.config.js
> +    slowMo: 30,
Should revert these....

2021-11-16 14:33 UTC, tmcconechy requested changes
Requesting changes as we shouldnt sloMo the tedsts and make them not headless except for testing local

2021-11-19 14:32 UTC, tmcconechy commented
any updates @janahintal ?

2021-11-22 07:19 UTC, janahintal commented
> any updates @janahintal ?

Hi @tmcconechy sorry I was on leave last friday. Will fix this today. Thank you!

2021-11-22 13:30 UTC, ericangeles approved these changes
🍌

2021-11-23 14:42 UTC, EdwardCoyle approved these changes
Looks good, thanks @janahintal

2021-11-24 05:47 UTC, merged