5836 - Accordion protractor to puppeteer tests
infor-design/enterprise pull request #5896
Opened 2021-11-25 06:57 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Converted protractor test cases to puppeteer.

**Related github/jira issue (required)**:

Closes #5836 

**Steps necessary to review your pull request (required)**:

- Pull this branch
- Run puppeteer tests

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.

2021-11-25 08:43 UTC, ericangeles requested changes
I like the simplicity and readability of the script. Please see some of the comments request changes. 🍌

2021-11-25 08:43 UTC, ericangeles commented on test/components/accordion/accordion.puppeteer-spec.js
> +    it('Should only allow one pane open at a time', async () => {
For consistency, we can start the word `should` for all `it() function`. e.g., `it('should only allow one pane open at a time', async () => {})`

2021-11-25 08:43 UTC, ericangeles commented on test/components/accordion/accordion.puppeteer-spec.js
> +  const baseUrl = 'http://localhost:4000/components/accordion';
🍌

2021-11-25 08:43 UTC, ericangeles commented on test/components/accordion/accordion.puppeteer-spec.js
> +    it('Should have panels', async () => {
Can lowercase the first word `should`.

2021-11-25 08:49 UTC, ericangeles commented
Can you also add changelog?

2021-11-25 10:26 UTC, ericangeles approved these changes

2021-11-29 14:39 UTC, EdwardCoyle approved these changes

2021-11-29 14:39 UTC, merged