5832 - Added actionsheet puppeteer tests
infor-design/enterprise pull request #5916
Opened 2021-12-03 00:12 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added actionsheet puppeteer tests.

**Related github/jira issue (required)**:

Closes #5832 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Run puppeteer tests

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-12-03 14:35 UTC, tmcconechy requested changes
Looks good but some small suggestions

2021-12-03 14:35 UTC, tmcconechy commented on test/components/actionsheet/actionsheet.puppeteer-spec.js
> +    afterEach(async () => {
Is this necessary? I dont think it is as your loading the page AFTER the test each finish.

2021-12-03 14:35 UTC, tmcconechy commented on test/components/actionsheet/actionsheet.puppeteer-spec.js
> +    it('should cancel an Action Sheet when pressing the Escape key', async () => {
```suggestion
    it('should hide the Action Sheet when pressing the Escape key', async () => {
```

2021-12-03 14:35 UTC, tmcconechy commented on test/components/actionsheet/actionsheet.puppeteer-spec.js
> +    it('should cancel an Action Sheet when clicking the "cancel" button', async () => {
```suggestion
    it('should hide the Action Sheet when clicking the "cancel" button', async () => {
```

2021-12-06 02:16 UTC, yohannahbautista commented on test/components/actionsheet/actionsheet.puppeteer-spec.js
> +    afterEach(async () => {
I changed it to afterAll, if I don't put back the original size of the page the other suites fail. I used afterEach in case there would be future tests added that needed pages to be the original size.

2021-12-06 20:47 UTC, deep7102 approved these changes

2021-12-07 06:08 UTC, ericangeles approved these changes

2021-12-07 06:11 UTC, merged