5684 - Added focus outline on cards when tabbing
infor-design/enterprise pull request #5922
Opened 2021-12-06 08:37 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added focus outline in css on cards when tabbing.

**Related github/jira issue (required)**:

Closes #5684 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components//cards/example-single-select.html
- Start tabbing
- Selected card should have focus state 

**Included in this Pull Request**:
- [ ] A note to the change log.

2021-12-06 15:42 UTC, tmcconechy requested changes
Is it just me or i am not seeing this working. When i tab the page it looks like before.

2021-12-06 21:30 UTC, deep7102 commented
it apply but not the right style, I think it can use our mixin as:
`@include focus-state();`

2021-12-07 14:47 UTC, tmcconechy approved these changes

2021-12-13 04:47 UTC, ericangeles approved these changes

2021-12-13 14:32 UTC, merged