5713 - Datagrid Row Selection Arrow Keys
infor-design/enterprise pull request #5933
Opened 2021-12-09 06:51 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will add datagrid feature using arrow keys to select.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5713

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-key-row-select.html
- Click one row
- Use Arrow Keys (Up and Down) to move selection

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-12-09 19:39 UTC, tmcconechy requested changes
A couple small things. In addition can you check the events i am not sure if this is 1000% an issue but

- tab into the grid with a row selected -> fires selected
- tab out also fires selected (but this is hard to test with the args[0]) on it

2021-12-09 19:39 UTC, tmcconechy commented on src/components/notification-badge/notification-badge.js
> - * @param {string} [settings.icon] The icon to display.
Did you mean to remove?

2021-12-09 19:39 UTC, tmcconechy commented on app/views/components/datagrid/example-key-row-select.html
> +        if (args[0]) {
Can we remove the args[0] so the console log happens in the test?

2021-12-10 05:10 UTC, tjamesallen15 commented on src/components/notification-badge/notification-badge.js
> - * @param {string} [settings.icon] The icon to display.
Yep. I forgot to remove this on my last change on notification badge. I just happen to notice it while coding. Should I make another PR for this one? My bad.

2021-12-10 05:10 UTC, tjamesallen15 commented
> Also maybe a test for this one?

will do tim!

2021-12-10 15:16 UTC, tmcconechy commented on src/components/notification-badge/notification-badge.js
> - * @param {string} [settings.icon] The icon to display.
No its fine - just wanted to check.

2021-12-10 15:18 UTC, tmcconechy approved these changes
The only thing i see is..

- tab in and arrow down a few rows
- tab out of the grid
- tab back in - event fires when already selected

But i think lets let the app team try this because i think changing that could cause issues so lets leave it. So just making a note 👍🏻

2021-12-13 14:32 UTC, tmcconechy approved these changes

2021-12-14 03:55 UTC, ericangeles approved these changes

2021-12-14 03:55 UTC, ericangeles approved these changes

2021-12-14 03:55 UTC, merged