5851: Button puppeteer tests
infor-design/enterprise pull request #5936
Opened 2021-12-10 12:31 UTC by janahintal

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

5851: Button puppeteer tests

**Related github/jira issue (required)**:

Closes #5851
Related Issue #5568 

**Steps necessary to review your pull request (required)**:
1. pull this branch
2. build and run the app
3. run `npm run e2e:puppeteer button`
4. It should pass.

Go to http://localhost:4000/components/button/example-button-with-hitbox
Button with hitbox should have 44px height, and 44px minimum width
The added hitbox area should be clickable

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2021-12-14 06:36 UTC, ericangeles requested changes
Can you also add a changelog for this? Add it under `## v4.59.0 Features`

2021-12-14 06:36 UTC, ericangeles commented on test/components/button/button.puppeteer-spec.js
> +    await page.waitForTimeout(200);
It looks like this line doesn't need anymore.

2021-12-15 09:18 UTC, ericangeles approved these changes

2021-12-15 11:26 UTC, tjamesallen15 approved these changes

2021-12-15 11:27 UTC, merged