5663 - Updated example page
infor-design/enterprise pull request #5963
Opened 2021-12-20 05:59 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Updated example page to fix previous bug on locale change.

**Related github/jira issue (required)**:

Addresses comments in #5663 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to http://localhost:4000/components/datagrid/example-export-format.html
- Change locale in dropdown

2021-12-20 14:38 UTC, tmcconechy requested changes
@yohannahbautista im ok with the URL changing like this but what im noticing is if you start on http://localhost:4000/components/datagrid/example-export-format.html and pick from the dropdown it doesnt work (when you select from the dropdown nothing happens).

but if you start on http://localhost:4000/components/datagrid/example-export-format.html?locale=en-GB  it works well.

So maybe need a case for default / en-US / no locale?

2021-12-21 14:28 UTC, tmcconechy commented
Now on review im not seeing it change the locale. I see an error `gridApi is not defined` in the console. Which is probably why?

2021-12-22 14:57 UTC, tmcconechy approved these changes

2021-12-27 04:38 UTC, ericangeles approved these changes

2021-12-27 04:38 UTC, merged