5915: Sink Page: Editor Image not shown
infor-design/enterprise pull request #5968
Opened 2021-12-21 19:19 UTC by davidcarlsonberg

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Image is not shown when using image insertion button.

**Related github/jira issue (required)**:

Resolves #5915 

**Steps necessary to review your pull request (required)**:

Pull brach, run app, visit http://localhost:4000/components/editor/example-index.html and use the image insertion button and notice the placeholder image should be visible now.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-12-22 07:51 UTC, ericangeles commented
@davidcarlsonberg can you convert your e2e (protractor) to puppeteer test instead? We are now currently moving all the old tests from protractor to puppeteer. You can check some of the test samples for guidelines and this https://github.com/infor-design/enterprise/blob/main/docs/TESTING.md#puppeteer-e2e-test

2021-12-22 14:59 UTC, tmcconechy commented on test/components/editor/editor.e2e-spec.js
> +  fit('Should insert placeholder image if the image button is clicked and modal confirmed', async () => {
```suggestion
  it('Should insert placeholder image if the image button is clicked and modal confirmed', async () => {
```

2021-12-22 15:01 UTC, tmcconechy reviewed
Looks good. You just left in some `fit`s but also agree with @ericangeles comment we should use puppeteer tests as we are working to convert to these

2021-12-22 15:30 UTC, tmcconechy commented
Also i think some editor tests might be failing. I restarted the tests to confirm

2021-12-22 15:58 UTC, tmcconechy commented
yeah that test is failing https://github.com/infor-design/enterprise/runs/4608596433?check_suite_focus=true#step:12:3008

2021-12-27 14:56 UTC, tmcconechy commented
An idea for a test fix here is to make a new page for automation-id's then make this test point to that page instead. Or try and correct the logic so it works if the ID is changed with automation id's...

2022-01-03 15:15 UTC, tmcconechy commented
Rechecking - still see failing tests but fixed the conflicts for you

2022-01-04 14:50 UTC, tmcconechy requested changes
Looking at this again @davidcarlsonberg i think we should maybe try to fix the logic so that it works if they do change the setting as this could happen.

2022-01-12 02:51 UTC, davidcarlsonberg commented
Apologies but I am not receiving your @ mentions to me in GitHub for some reason. I'm not sure what you're referring to when you mention Automation IDs?

2022-01-12 14:42 UTC, tmcconechy commented
@davidcarlsonberg by the automation id's i mean that when using the `attributes` setting the developer can assign an id or a `data-automation-id` attribute or whatever they like. This case is really just around the ID. So thinking something like..

- get the current id whatever it is however it is set (if you need to can check settings.attributes['id'] is there...)
- use that in the logic

2022-01-12 15:38 UTC, davidcarlsonberg commented
In the latest commit I'm grabbing the ID from attributes. Is that what you had in mind? I can also grab the last item in the attributes array if we want to use whatever the last item is?

2022-01-12 15:42 UTC, tmcconechy commented
yeah i think that makes sense 👍🏻 the final proof is in if the tests do pass there then i think it should be good

2022-01-13 11:23 UTC, davidcarlsonberg commented
Oof. I've run the tests a couple times and the only consistent error is the Blockgrid one. I am unsure how that is related to the work done in this PR?

2022-01-13 11:29 UTC, ericangeles commented
@davidcarlsonberg maybe it has something to do with the chrome version. @tmcconechy made the fixed and it's now merged. Is your branch updated with the main?

2022-01-13 11:59 UTC, davidcarlsonberg commented
Ah! Good to know. Updating to `main` now.

2022-01-13 14:18 UTC, tmcconechy commented
Yes i fixed this one on a PR recently merged 👍🏻  So update with main should work

2022-01-13 14:20 UTC, tmcconechy submitted a review, later dismissed

2022-01-14 06:59 UTC, tjamesallen15 submitted a review, later dismissed

2022-01-14 16:13 UTC, merged