5875 - Fix on Modal Focus with Hidden Display None
infor-design/enterprise pull request #5979
Opened 2021-12-28 11:52 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix modal focus issues with inline display none.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5875 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/modal/example-index.html
- Click `Show Modal`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2021-12-28 14:45 UTC, tmcconechy commented on src/components/modal/modal.js
> +        .not('[style*="display: none"]').first();
```suggestion
        .not(':hidden').first();
```

Will this work? It could catch more cases like it is invisible with css or css visibility. Lets try to see if it solves?

2021-12-28 14:46 UTC, tmcconechy requested changes
Maybe the suggested selector is better. Also can you update the test steps on the PR. I see a new example but wasnt sure how to test

2022-01-03 15:20 UTC, tmcconechy requested changes
I see some problems now with this @tjamesallen15 

1. open the modal
2. focus problem then tab multiple times

Notice that the tab stops on the save button and doesnt loop around anymore to the top of the modal. See https://main-enterprise.demo.design.infor.com/components/modal/example-index.html

Also the reverse is wrong
1. open model
2. focus problem field
3. shift tab

Notice it tabs out of the modal. Instead of looping around.

I guess the logic of finding the first field on the form is also wrong or the fix needs to be adjusted?

2022-01-04 14:52 UTC, tmcconechy approved these changes
Looks good now 👍🏻

2022-01-04 15:10 UTC, deep7102 approved these changes

2022-01-04 15:11 UTC, EdwardCoyle approved these changes

2022-01-04 15:29 UTC, merged