Dropdown Script for Enter key opens dropdown list, when it should onl…
infor-design/enterprise pull request #6000
Opened 2022-01-07 08:17 UTC by janahintal

…y be used to select items within an open list

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Dropdownpuppeteer test for #5842 

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

1. pull this branch
2. build and run the app
3. run `npm run e2e:puppeteer dropdown`
4. It should pass.
Steps:
Scenario 1:
Run http://localhost:4000/components/dropdown/test-allow-custom-keystroke.html
Select the dropdown via tab key.
Press enter key
It should not open the list

Scenario 2:
Run http://localhost:4000/components/dropdown/test-allow-custom-keystroke.html
Select the dropdown via tab key.
Open the dropdown list
Hit enter on a highlighted value
Enter key should work even the enter key stroke doesn't allow

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-01-07 14:49 UTC, tmcconechy requested changes
Just edited some of the test names for clarity. Feel free to adjust as you see fit. Also check out this article that i agree with https://github.com/mawrkus/js-unit-testing-guide#-name-your-tests-properly

2022-01-07 14:49 UTC, tmcconechy commented on test/components/dropdown/dropdown.puppeteer-spec.js
> +  describe('Dropdown for Enter key opens dropdown list, when it should only be used to select items within an open list', () => {
```suggestion
  describe('Supports custom keystrokes', () => {
```

2022-01-07 14:49 UTC, tmcconechy commented on test/components/dropdown/dropdown.puppeteer-spec.js
> +    it('should have the enter key stroke to be disabled  ', async () => {
```suggestion
    it('should support disabling the enter key when closed with the onKeyDown function', async () => {
```

2022-01-07 14:49 UTC, tmcconechy commented on test/components/dropdown/dropdown.puppeteer-spec.js
> +    it('should select value when hovered and press enter', async () => {
```suggestion
    it('should support using the enter key to select while using the onKeyDown function', async () => {
```

2022-01-07 15:23 UTC, ericangeles commented
> Just edited some of the test names for clarity. Feel free to adjust as you see fit. Also check out this article that i agree with https://github.com/mawrkus/js-unit-testing-guide#-name-your-tests-properly
> 
> Also the one test seems to fail still

We can apply this approach. Cc @tjamesallen15 @yohannahbautista see the link.

2022-01-10 11:07 UTC, janahintal commented on test/components/dropdown/dropdown.puppeteer-spec.js
> +    it('should select value when hovered and press enter', async () => {
> should support using the enter key to select while using the onKeyDown function

Noted Tim. Working on this. It's weird that the script is failing in headless. Tried it running in Non-headless and it all passed. Still working for a workaround. Thanks!

2022-01-10 14:12 UTC, tmcconechy commented on test/components/dropdown/dropdown.puppeteer-spec.js
> +    it('should select value when hovered and press enter', async () => {
@janahintal you could try to do something like this:
```
const element = await page.waitForSelector('div[class="dropdown"], { visible: true });
````      

So it waits for that selector to load. Also this is much more preferable to all the `await page.waitForTimeout(200)` as each of these is slowing down the tests the `waitForSelector` will only wait as long as needed.

2022-01-12 13:33 UTC, ericangeles commented
@janahintal I pushed a better fix for getting the aria attributes. Let me know if you still need help.

2022-01-12 14:25 UTC, ericangeles reviewed
A changelog perhaps? @janahintal

2022-01-12 14:50 UTC, tmcconechy commented
Looks good now. I like that you fixed the timeouts to do the waitForselector instead. WIll approve if this all passes

2022-01-13 09:51 UTC, ericangeles approved these changes

2022-01-13 14:45 UTC, merged