5846 - Fix on fileupload value is undefined when trying to upload
infor-design/enterprise pull request #6006
Opened 2022-01-10 08:45 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added a promise that puts a timeout before getting the value so that value won't be undefined when it reaches datagrid. 

**Related github/jira issue (required)**:

Closes #5846 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/test-editable-fileupload.html
- Click on the file upload button on the first column and select a file
- File path should appear on column

**Included in this Pull Request**:
- [ ] A note to the change log.

2022-01-10 14:37 UTC, tmcconechy requested changes
Can you also check the icon alignment on the 4 row heights. It seems like the icon and the x are either not aligned or do not have nice looking spacing between them

![Screen Shot 2022-01-10 at 9 36 06 AM](https://user-images.githubusercontent.com/814283/148783530-295bfb35-e31e-4a53-873e-a95199e6754b.png)

Also would be nice if the icon stayed visible on when you click the dialog to open while selecting the icon would be visible as it sort of looks like nothing was happening

2022-01-12 15:06 UTC, tmcconechy commented
@yohannahbautista sorry this isnt 100% what i was thinking. Now the icon shows all the time. What i meant was it should show when hovering the cell and when clicking the editor to open (during the time while the editor is open).

Also the icon is sitting a bit low, should be centered

2022-01-18 16:15 UTC, tmcconechy approved these changes

2022-01-19 04:50 UTC, ericangeles approved these changes

2022-01-19 04:50 UTC, merged