5673 - Update the color of badges/tags for better accessibility contrast
infor-design/enterprise pull request #6010
Opened 2022-01-11 14:44 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR updates the color of the badges/tags statuses for better accessibility contrast.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/5673

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/badges/example-index.html
- Compare the colors vs in the Figma [file](https://www.figma.com/file/gHmapzCfCqqPRv5RnFfGcE/Q3-Accessibility-Tests?node-id=36%3A568) given
- Test in all three (Light, Dark, Contrast) variants (New Version only)
- Go to http://localhost:4000/components/tag/example-index.html
- Test/Check also the same way in the first example page

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2022-01-11 14:46 UTC, ericangeles commented
Am expecting to fail some tests (visual tests) that will affect the tags/badges changes. Once okay with the approvers, I will update the baseline image (if there is).

2022-01-11 14:58 UTC, tmcconechy requested changes
Looks good i really like these changes. The only thing i see is that the tags are not bold in the design (and i think they look better not bold).

http://localhost:4000/components/tag/example-index.html
vs

<img width="757" alt="Screen Shot 2022-01-11 at 9 57 19 AM" src="https://user-images.githubusercontent.com/814283/148966310-3f7c2b72-27ae-4021-99fa-0200a8255168.png">

2022-01-12 15:06 UTC, tmcconechy commented
Looks good to me now - just need the tests and ll approve

2022-01-13 14:45 UTC, tmcconechy approved these changes

2022-01-14 06:50 UTC, yohannahbautista approved these changes

2022-01-14 08:55 UTC, merged