5830 - Tooltip Puppeteer Test
infor-design/enterprise pull request #6037
Opened 2022-01-18 11:49 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will add puppeteer test for tooltip component

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5830

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Run in terminal `npm run e2e:puppeteer`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-01-19 00:30 UTC, yohannahbautista submitted a review, later dismissed

2022-01-19 04:49 UTC, ericangeles requested changes

2022-01-19 04:49 UTC, ericangeles commented on test/components/tooltip/tooltip.puppeteer-spec.js
> +      await page.waitForTimeout(100);
I think there's a way to work this without using `waitForTimeout`. Try to use `.then()` method to the `waitForSelector()`.  Something like this,

```javascript
await page waitForSelector('#element', { visible: true  }).then(...)
```

2022-01-19 04:49 UTC, ericangeles commented on test/components/tooltip/tooltip.puppeteer-spec.js
> +      await page.waitForTimeout(100);
@yohannahbautista and I have implemented this kind of approach in the other puppeteer tests. Let us know if you need help.

2022-01-20 06:45 UTC, ericangeles commented on test/components/tooltip/tooltip.puppeteer-spec.js
> +  const baseUrl = 'http://localhost:4000/components/tooltip/';
You have an extra `/` that causes the tests to fail.

2022-01-20 07:12 UTC, ericangeles commented on test/components/tooltip/tooltip.puppeteer-spec.js
> +    const url = `${baseUrl}/tooltip/example-index?theme=classic&layout=nofrills`;
Remove also the `tooltip` since the baseUrl have this in the path.

2022-01-20 08:13 UTC, ericangeles approved these changes
Great work! 🍌

2022-01-20 09:40 UTC, yohannahbautista approved these changes

2022-01-20 09:44 UTC, merged