5768 - Implement actionable button card
infor-design/enterprise pull request #6038
Opened 2022-01-18 16:22 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR implements an actionable button in the card component. It will behave like a button (hover, focus, press) for the card.

**Related github/jira issue (required)**:

Closes #5768

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- http://localhost:4000/components/cards/example-actionable
- When clicking the button, it should behave like a button component (ripple effect)
- Do tab through the page
- It should have border blue, and effect like the button component
- Hovering will change the font color to darker, and should have a cursor
- Width should be 100%
- Text should be vertically centered

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-01-18 16:26 UTC, ericangeles commented
Once the design is okay for the approvers, I will create an e2e for this.

2022-01-18 16:27 UTC, tmcconechy requested changes
Looks almost perfect the only thing a bit wierd is the `<hr>` when you look in dark mode. We have some classes like `<hr class="fieldset-hr"/>` you could use for this example but might have to update the padding.

Or just take the `<hr>` out...

2022-01-19 20:27 UTC, tmcconechy approved these changes

2022-01-20 01:10 UTC, yohannahbautista approved these changes

2022-01-20 07:07 UTC, merged