5937 - Rich Text Editor Row Height Issue after typing
infor-design/enterprise pull request #6050
Opened 2022-01-21 02:51 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug which changes the approach intended by the user after typing in editor.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5937

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/editor/example-index.html
- Clear the existing content with the rich text component
- Rapidly type into the text editor several characters then the enter key (repeat for a couple of lines) then stop
- Go to http://localhost:4000/components/editor/test-modal.html
- Click on `Show Modal`
- Do the same as the above.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-01-21 14:30 UTC, tmcconechy requested changes
Sorry i think i see why that code might be there. But maybe there is another place we can add it to update the buttons.

http://localhost:4000/components/editor/example-index.html
- select Cross and make it bold (notice the B button is highlighted)
- select platform  (notice the B button is highlighted still when its not bold)
- make it italic (correct now)
- select Cross again  (notice the I button is highlighted still when its not bold)

Compare to https://main-enterprise.demo.design.infor.com/components/editor/example-index.html

I think maybe some other event logic when selecting still needs to call checkSelect. Either that or we could consider removing the fact it highlights the button? But that seems like it may get pushback.

2022-01-25 10:02 UTC, tjamesallen15 commented
I brought back the bindSelect but with little bit of twist. @tmcconechy

2022-01-25 15:06 UTC, EdwardCoyle approved these changes

2022-01-25 17:54 UTC, ericangeles approved these changes

2022-01-25 17:54 UTC, merged