5735 - datagrid modal unable to tab fields
infor-design/enterprise pull request #6058
Opened 2022-01-25 10:06 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug in datagrid where filterable headers cannot be tab through in modal.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5735 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-modal-datagrid-tabbing.html
- Click `Open Modal`
- Perform a shift-tab (or tab) until focus is on a field in the filter row
- Continue to hit shift-tab (or tab) and notice that focus does not move across the filter row fields

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-01-25 14:36 UTC, tmcconechy requested changes
This looks like it solved it but i see something wierd with the tab order:

- open the modal
- shift tab until you hit the first filter button
- shift tab again -> jumps up to the x not the toolbar
- but the reverse case seems to work

2022-01-26 14:45 UTC, tmcconechy approved these changes

2022-01-27 01:15 UTC, yohannahbautista approved these changes

2022-01-27 07:10 UTC, ericangeles approved these changes

2022-01-27 07:10 UTC, merged