5817 - Fix translation issue  in french locales
infor-design/enterprise pull request #6078
Opened 2022-01-31 14:13 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes translation issues in french locales where there should be no trailing space before the colon.

**Related github/jira issue (required)**:

Closes #5817

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/about/example-index.html?locale=fr-CA & http://localhost:4000/components/about/example-index.html?locale=fr-FR
- Open the modal
- Check the labels in the device specs
- Expected result e.g., `Système d'exploitation: Mac OS` and not `Système d'exploitation : Mac OS`
- There should be no space before the colon
- Check the rest of the device specs
- Go to http://localhost:4000/components/about/example-index.html (not french locales)
- Open the modal and check the device specs
- Expected result `Système d'exploitation : Mac OS`
- It should have space before the colon
- Check the rest of the device specs
- Go to http://localhost:4000/components/form/example-labels.html?locale=fr-FR & http://localhost:4000/components/form/example-labels.html?locale=fr-CA
- Check the `Data Label (Left)` section
- You should be able to see `Shipping to: Los Angeles, California 90001 USA` (it should not have space before colon)
- Go to http://localhost:4000/components/form/example-labels.html
- Check the `Data Label (Left)` section
- You should be able to see `Shipping to : Los Angeles, California 90001 USA` (it should have space before colon)

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2022-01-31 14:38 UTC, tmcconechy approved these changes

2022-01-31 17:06 UTC, EdwardCoyle reviewed
@ericangeles I think the data labels example may be backwards?

![Screen Shot 2022-01-31 at 12 03 58 PM](https://user-images.githubusercontent.com/3249601/151839239-db83b640-fc65-4ea2-8ba3-01747d3fd58d.png)
![Screen Shot 2022-01-31 at 12 04 07 PM](https://user-images.githubusercontent.com/3249601/151839242-b5b09665-ddbe-47b9-9052-08e9356f177b.png)

2022-02-02 14:52 UTC, tmcconechy requested changes
Think its backwards now

2022-02-02 15:02 UTC, cpinatel7 commented
This is how it should be in French (France) and French (Canada).

Examples (French government website: https://www.gouvernement.fr/)

![image](https://user-images.githubusercontent.com/66057969/152179324-18802bb8-f355-4b4e-bc34-96610a3d53b5.png)

2022-02-03 16:51 UTC, ericangeles commented
> 

Is this the same in the about modal device specs?

2022-02-03 17:08 UTC, ericangeles commented
Apologies @EdwardCoyle for the confusing PR description. I have updated it now and pushed the correct fix (Assuming that this is correct).

2022-02-04 15:30 UTC, tmcconechy approved these changes

2022-02-07 14:45 UTC, tmcconechy approved these changes

2022-02-07 15:43 UTC, deep7102 approved these changes

2022-02-07 16:03 UTC, merged