6076 - datagrid issue when choosing 12 in timepicker resets to 0
infor-design/enterprise pull request #6124
Opened 2022-02-15 02:03 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug in timepicker inside datagrid where hours is reset 0 when changing it to 12.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6076

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-02-15 15:17 UTC, tmcconechy requested changes
@tjamesallen15 when i try this in the different row heights

xs - looks good
sm - ui is out of alignment
md - ui is out of alignment
lg - looks good

So could you check all 4 row heights out?

2022-02-15 19:10 UTC, s-werking commented
Hi @tjamesallen15,
I checked out your branch and followed the suggested steps to review and typing '1200' in a timepicker cell works well, but I am still seeing one instance when a time is selected via the timepicker that 12PM changes to 12AM:
![Scenario of 12PM to 12AM on timepicker](https://user-images.githubusercontent.com/76002134/154131781-bb85bef6-59d9-4c37-aa90-b0608dc0a0ba.gif)

Do you see this issue? Thanks

2022-02-16 06:44 UTC, tjamesallen15 commented
> Hi @tjamesallen15, I checked out your branch and followed the suggested steps to review and typing '1200' in a timepicker cell works well, but I am still seeing one instance when a time is selected via the timepicker that 12PM changes to 12AM: ![Scenario of 12PM to 12AM on timepicker](https://user-images.githubusercontent.com/76002134/154131781-bb85bef6-59d9-4c37-aa90-b0608dc0a0ba.gif)
> 
> Do you see this issue? Thanks

will be checking on this one.

2022-02-16 14:50 UTC, tmcconechy submitted a review, later dismissed

2022-02-18 18:31 UTC, s-werking approved these changes

2022-02-18 18:34 UTC, awbuboltz submitted a review, later dismissed

2022-02-21 05:02 UTC, ericangeles commented on src/components/datagrid/datagrid.formatters.js
> +      if (timeString.indexOf('AM') > -1 || timeString.indexOf('PM') > -1) {
My only concern here is when you're in a different locale e.g., http://localhost:4000/components/datagrid/test-timepicker-24.html?locale=ar-EG. Try to change the period to `م`. It will go back to `ص`.

2022-02-22 15:05 UTC, tmcconechy approved these changes

2022-02-23 14:43 UTC, tmcconechy commented
I still see some minor movement of the icons in edit mode in the 4 row heights but willing to let that go for now. The most important remaining issue seems to be @ericangeles 's point

http://localhost:4000/components/datagrid/test-timepicker-24.html?locale=ar-EG
- click in the seconds editor (notice some movement of the editor and icon)
- open the picker and pick م. and hit enter and it will go back to ص.

2022-02-23 18:38 UTC, tjamesallen15 commented
> Reference in

Fix in my new push.

2022-02-23 18:38 UTC, tjamesallen15 commented
> I still see some minor movement of the icons in edit mode in the 4 row heights but willing to let that go for now. The most important remaining issue seems to be @ericangeles 's point
> 
> http://localhost:4000/components/datagrid/test-timepicker-24.html?locale=ar-EG
> 
> * click in the seconds editor (notice some movement of the editor and icon)
> * open the picker and pick م. and hit enter and it will go back to ص.

Hopefully this is fixed now with my updated fix. :)

2022-02-23 19:22 UTC, tmcconechy approved these changes

2022-02-24 14:19 UTC, tmcconechy commented
Looks like this is working @tjamesallen15 but need some images to be updated https://github.com/infor-design/enterprise/runs/5318561875?check_suite_focus=true#step:11:2986 (or changed to use puppetteer)

2022-02-28 14:18 UTC, tmcconechy submitted a review, later dismissed

2022-03-01 14:26 UTC, tmcconechy approved these changes

2022-03-01 15:29 UTC, ericangeles approved these changes

2022-03-01 15:29 UTC, merged