6015 - Fix for add hyperlink modal via CTRL-H
infor-design/enterprise pull request #6125
Opened 2022-02-15 12:14 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug in editor where CTRL-H (add hyperlink) breaks the interface.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6015

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/editor/example-index.html
- Resize the browser window such that the add hyperlink option is not visible
- Press ctrl-H to open the add hyperlink modal
- Attempt to add the hyperlink (press 'insert' button)

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-02-15 15:22 UTC, tmcconechy requested changes
Is the debounce needed? (Just a general thought/question). But the only problem i see with the fix is..

- resize the page so the link button is in the .. menu
- hit ctl-h
- hit enter
- and the modal overlay stays around
![Screen Shot 2022-02-15 at 10 20 14 AM](https://user-images.githubusercontent.com/814283/154092586-1c53aafe-716c-49f6-9d00-010ab65219f5.png)

2022-02-16 05:15 UTC, tjamesallen15 commented
> 

From what I saw handling editor tickets, debounce is the one that checks the states of the buttons in the editor, like bold, if the current selected is currently bold or not, similar to italics and underlined.

I'll check on the bug.

2022-02-16 06:35 UTC, tjamesallen15 commented
> Is the debounce needed? (Just a general thought/question). But the only problem i see with the fix is..
> 
> * resize the page so the link button is in the .. menu
> * hit ctl-h
> * hit enter
> * and the modal overlay stays around
>   ![Screen Shot 2022-02-15 at 10 20 14 AM](https://user-images.githubusercontent.com/814283/154092586-1c53aafe-716c-49f6-9d00-010ab65219f5.png)

How did you reproduce the issue? It seems I can't reproduce it. I followed your steps but nowhere to be found.

2022-02-16 14:31 UTC, tmcconechy commented
@tjamesallen15 this seems to get the results.

1. Pull this branch, run and go to http://localhost:4000/components/editor/example-index.html
1. Resize the page so that the toolbar is this wide (seems related to whats hidden/shown)
<img width="499" alt="Screen Shot 2022-02-16 at 9 30 13 AM" src="https://user-images.githubusercontent.com/814283/154285697-cbd322a8-c135-44c0-a896-b376c96df6cb.png">
1. Hard Reload the page (shift + reload)
1. Click some text and hit CTRL+F and hit insert
1. Click some text and hit CTRL+F and hit insert again

2022-02-17 14:39 UTC, tmcconechy approved these changes

2022-02-21 05:15 UTC, ericangeles approved these changes

2022-02-22 06:17 UTC, merged