6008. Initial
infor-design/enterprise pull request #6136
Opened 2022-02-21 12:39 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug in datagrid where datepicker range having an exception when having values before changing to range type.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6008

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-filter.html
- Set any date for any date column with operator equals
- Change the operator to range
- Open the date picker
- Try to select the range dates

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-02-22 01:56 UTC, yohannahbautista approved these changes

2022-02-22 06:17 UTC, ericangeles approved these changes
Nice fix! 🍌

2022-02-22 15:22 UTC, tmcconechy requested changes
I see one issue with this. If you follow the steps on the Order Date (Custom Format) column you end up with "NaN/NaN/NaN - NaN/NaN/NaN" in the field. But it works on the other column.

I'm guessing to might be this (or related)

https://github.com/infor-design/enterprise/pull/6136/files#diff-13c32b0c73b40992aa6d376fb22d6746845a3b7d6d2545e19bd30687bcabb5a5R1452

2022-02-23 14:51 UTC, tmcconechy approved these changes
Looks good now thanks @tjamesallen15  👍🏻

2022-02-23 15:36 UTC, ericangeles commented on docs/CHANGELOG.md
> +- `[Datagrid]` Fix a bug in datagrid where datepicker range having an exception when having values before changing to range type. ([#6008](https://github.com/infor-design/enterprise/issues/6008))
Arrange in alphabetical order @tjamesallen15 :) thanks

2022-02-23 18:40 UTC, tjamesallen15 commented on docs/CHANGELOG.md
> +- `[Datagrid]` Fix a bug in datagrid where datepicker range having an exception when having values before changing to range type. ([#6008](https://github.com/infor-design/enterprise/issues/6008))
> Arrange in alphabetical order @tjamesallen15 :) thanks

I just fixed the changelog in alphabetical order. This was caused by merging the main branch to this branch. I didn't bother to check the changelogs that time since not merge conflicts was found. My bad!

2022-02-23 18:50 UTC, tmcconechy commented on docs/CHANGELOG.md
> +- `[Datagrid]` Fix a bug in datagrid where datepicker range having an exception when having values before changing to range type. ([#6008](https://github.com/infor-design/enterprise/issues/6008))
Maybe my bad :)

2022-02-23 18:51 UTC, tmcconechy approved these changes

2022-02-24 06:51 UTC, ericangeles approved these changes

2022-02-24 06:51 UTC, merged