6003 - Additional check for commitCellEdit on focus
infor-design/enterprise pull request #6139
Opened 2022-02-23 10:22 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added check for when cell is focused: will not commit cell edits if browser is safari.

**Related github/jira issue (required)**:

Closes #6003 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- In Safari, go to: http://localhost:4000/components/datagrid/example-list-lookup.html
- Click on one of the "Product Id" fields
- Click on search icon
- Select a record in popped up modal
- Should have the record's value in the datagrid cell

**Included in this Pull Request**:
- [ ] A note to the change log.

2022-02-23 14:58 UTC, tmcconechy requested changes
@yohannahbautista this is working well except can you fix the layout when you click in the cell...

<img width="180" alt="Screen Shot 2022-02-23 at 9 57 24 AM" src="https://user-images.githubusercontent.com/814283/155344935-ee8915bc-fa11-4db0-9770-6f7290d9d659.png">

(also check all 4 row heights)

2022-02-24 11:56 UTC, ericangeles approved these changes

2022-02-24 14:22 UTC, tmcconechy commented
Still looks out of alignment in edit mode... (showing normal mode only)

<img width="173" alt="Screen Shot 2022-02-24 at 9 21 45 AM" src="https://user-images.githubusercontent.com/814283/155541981-77dbc659-d66b-479b-adf6-77bf23262263.png">

2022-02-28 14:25 UTC, tmcconechy approved these changes
Looks good 👍🏻

2022-02-28 17:12 UTC, ericangeles approved these changes

2022-02-28 17:12 UTC, merged