6024 - Changed maximum modal width
infor-design/enterprise pull request #6147
Opened 2022-03-01 08:42 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

Maximum width in modal is set to full width so that there won't be a gap on the right side.

**Steps necessary to review your pull request (required)**:

Closes #6024 

**Included in this Pull Request**:
- [ ] Updated example page.
- [ ] A note to the change log.

2022-03-01 14:40 UTC, tmcconechy reviewed
I think this looks good. But pinging @EdwardCoyle to test as im not sure what `frameWidth` is for?

2022-03-03 14:39 UTC, tmcconechy approved these changes

2022-03-03 14:56 UTC, deep7102 submitted a review, later dismissed

2022-03-03 15:27 UTC, EdwardCoyle requested changes
@yohannahbautista The fix in this PR does address the excess padding, but I think it might need some more work.  See my comment below:

2022-03-03 15:27 UTC, EdwardCoyle commented on src/components/modal/modal.js
> -      calcWidth = ($(window).width() * 1) - this.settings.frameWidth;
I'm not sure about the change here -- This code path with `frameWidth` is for when `fullsize` isn't active, so I don't think it's fully addressing the original issue.  The padding is gone for sure, but this completely removes the `frameWidth` setting from the component which could break some functionality.

I think what might be better here is:
- Definitely remove any `width/min-width/max-width` attributes that were previously applied when the IF block above is hit
- I think we need to keep the size adjustments done in this codepath to prevent any API breakage.  If there are still padding issues on non-fullsize, maybe we need to consider defaulting `frameWidth` to 0.

2022-03-07 14:04 UTC, tmcconechy approved these changes

2022-03-08 07:13 UTC, tjamesallen15 approved these changes

2022-03-08 15:31 UTC, EdwardCoyle approved these changes
Looks great now, thanks @yohannahbautista 🎉

2022-03-08 15:31 UTC, merged