Locale test for PH translation
infor-design/enterprise pull request #6150
Opened 2022-03-01 11:41 UTC by janahintal

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Locale test for PH translation

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-03-01 14:42 UTC, tmcconechy requested changes
Just need some lint fixes. Also not sure if an await is needed or not (@ericangeles added this)

2022-03-01 14:42 UTC, tmcconechy commented on test/components/locale/locale.puppeteer-spec.js
> +    expect(img).toMatchImageSnapshot(config);
@ericangeles does `toMatchImageSnapshot` need an await?

2022-03-01 15:28 UTC, ericangeles commented on test/components/locale/locale.puppeteer-spec.js
> +    expect(img).toMatchImageSnapshot(config);
@tmcconechy it doesn't need `await` as far as I know (if you mean in line 16).

2022-03-01 15:53 UTC, tmcconechy commented on test/components/locale/locale.puppeteer-spec.js
> +    expect(img).toMatchImageSnapshot(config);
ok then never mind.. Thanks for confirming

2022-03-03 05:52 UTC, tjamesallen15 approved these changes

2022-03-03 10:25 UTC, ericangeles approved these changes

2022-03-03 10:25 UTC, merged