Cards visual test for actionable button
infor-design/enterprise pull request #6169
Opened 2022-03-07 11:11 UTC by janahintal

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-03-07 14:36 UTC, tmcconechy requested changes
@janahintal i think you also need to push the new image snap shot or else this will fail if merged

2022-03-08 08:51 UTC, ericangeles commented
@janahintal can you also update the PR description? Thanks!

2022-03-08 15:44 UTC, tmcconechy approved these changes

2022-03-08 15:45 UTC, tmcconechy commented
Seems like the new diff is out of sync already https://github.com/infor-design/enterprise/runs/5461695001?check_suite_focus=true#step:10:133 ?

2022-03-08 18:15 UTC, merged