5839 - Bar-Grouped: Convert Protractor tests to Puppeteer
infor-design/enterprise pull request #6176
Opened 2022-03-07 21:09 UTC by davidcarlsonberg

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

Resolves #5839 

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-03-07 22:27 UTC, tmcconechy approved these changes

2022-03-08 03:05 UTC, yohannahbautista submitted a review, later dismissed

2022-03-08 06:42 UTC, ericangeles commented on test/components/bar/bar-grouped.puppeteer-spec.js
> +    it('Should not select bar on click', async () => {
We make a pattern where the `it` function will start in lowercase.  E.g., `it('should not select bar on click')`

2022-03-08 06:43 UTC, ericangeles commented on test/components/bar/bar-grouped.puppeteer-spec.js
> +    it('Should not be able to tab through the legends', async () => {
It should start in lowercase for all `it` function.

2022-03-08 06:46 UTC, ericangeles commented on test/components/bar/bar-grouped.puppeteer-spec.js
> +      await utils.checkForErrors();
The `checkForErrors` method is working but it needs some adjustments to work in puppeteer properly so I did not include this when converting the protractor to puppeteer.

2022-03-08 15:51 UTC, tmcconechy requested changes
Requesting changes to address @ericangeles comments

- lower case
- dont need checkforerrors

2022-03-09 17:50 UTC, davidcarlsonberg commented
Looks like a ton of visual regression test issues after pulling in latest `main`. Will this be fixed by #6181 ?

2022-03-09 17:54 UTC, tmcconechy commented
Yes trying to... Its a big mess

2022-03-09 19:00 UTC, tmcconechy submitted a review, later dismissed

2022-03-10 03:54 UTC, ericangeles commented on test/components/bar/bar-grouped.puppeteer-spec.js
> +    it('Should not visual regress', async () => {
I think you missed this

2022-03-10 03:55 UTC, ericangeles commented on test/components/bar/bar-grouped.puppeteer-spec.js
> +    it('Should not visual regress', async () => {
Same here

2022-03-10 05:34 UTC, ericangeles approved these changes

2022-03-10 15:30 UTC, merged