6100 - Fix maxWidth setting in tooltip
infor-design/enterprise pull request #6190
Opened 2022-03-11 09:09 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-03-14 09:09 UTC, tjamesallen15 submitted a review, later dismissed

2022-03-15 13:57 UTC, tmcconechy requested changes
@ericangeles i moved the example to popover and updated it a bit. But i see why it doesnt have arrows and that i think needs addressing.

When looking at https://github.com/infor-design/enterprise/blob/main/src/components/tooltip/tooltip.js#L970 the code is adding a no-arrow class. So i think the max-width needs to be set before this test happens (either that or the demo needs a css width?)

2022-03-15 13:58 UTC, ericangeles commented
@tmcconechy was about to change the test page but I see you pushed it already. :) With regards to the missing arrow, I think it's because of this line https://github.com/infor-design/enterprise/blob/main/src/components/tooltip/tooltip.js#L970.

2022-03-15 14:05 UTC, tmcconechy commented
Sorry - i tried to help but couldnt get it all very quickly

2022-03-17 03:53 UTC, yohannahbautista approved these changes

2022-03-17 05:09 UTC, merged