Spinbox: puppeteer test for enhancement 1384
infor-design/enterprise pull request #6197
Opened 2022-03-15 03:28 UTC by jbrcna

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

Closes #5843 
Related to #1384

**Steps necessary to review your pull request (required)**:

1. pull this branch
2. build and run the app
3. run `npm run e2e:puppeteer spinbox`
4. It should pass.

Steps

- Given I am using a Google Chrome browser in an Android device
- And I go to http://main-enterprise.demo.design.infor.com/components/form/test-spinbox-compound-field.html
- When I check the width of the two Spinbox fields placed side-by-side
- Then the width of two Spinbox fields should be equal
- And the width of the second Spinbox should be aligned with the width of the other input fields

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-03-16 05:39 UTC, tjamesallen15 submitted a review, later dismissed
Looks good to me.

2022-03-16 13:25 UTC, tmcconechy commented on test/components/spinbox/spinbox.puppeteer-spec.js
> +      const iPhone = puppeteer.devices['iPhone X'];
One thing i see that could be an issue is if you look at the test result image the xs field is focused.

I think we should try to change the example so it does not focus, as sometimes this can cause the focus state to give false results

2022-03-17 04:26 UTC, jbrcna commented on test/components/spinbox/spinbox.puppeteer-spec.js
> +      const iPhone = puppeteer.devices['iPhone X'];
the focus is caused by the click event before the screenshot. will update this now. thanks @tmcconechy

2022-03-18 13:30 UTC, tmcconechy submitted a review, later dismissed
@jbrcna looks good - is this still draft?

2022-03-21 05:10 UTC, tjamesallen15 approved these changes

2022-03-21 05:10 UTC, tjamesallen15 commented
Approving again. :)

2022-03-21 06:03 UTC, jbrcna commented
thank you @tjamesallen15 @tmcconechy , making this ready now

2022-03-21 06:50 UTC, ericangeles requested changes

2022-03-21 06:50 UTC, ericangeles commented on test/components/spinbox/spinbox.puppeteer-spec.js
> +      const iPhone = puppeteer.devices['iPhone X'];
I don't think we really need this. Configuring the width and height in `beforeAll` is fine for now.

2022-03-21 06:50 UTC, ericangeles commented on test/components/spinbox/spinbox.puppeteer-spec.js
> +      await page.emulate(iPhone);
Can remove this one too.

2022-03-21 06:50 UTC, ericangeles commented on test/components/spinbox/spinbox.puppeteer-spec.js
> +      await page.goto('http://localhost:4000/components/spinbox/example-sizes.html?theme=uplift&variant=light', { waitUntil: ['domcontentloaded', 'networkidle0'] });
This one too.

2022-03-21 06:50 UTC, ericangeles commented on test/components/spinbox/spinbox.puppeteer-spec.js
> +        height: 480,
Set the height around 1200-1250 to accommodate all the spinboxes perhaps?

2022-03-21 06:50 UTC, ericangeles commented on test/components/spinbox/spinbox.puppeteer-spec.js
> +const puppeteer = require('puppeteer');
Remove this too.

2022-03-21 06:50 UTC, ericangeles commented
Once you have access to the VM, please generate the spinbox image. Thanks!

2022-03-21 08:52 UTC, jbrcna commented on test/components/spinbox/spinbox.puppeteer-spec.js
> +      const iPhone = puppeteer.devices['iPhone X'];
this is now removed.

2022-03-21 08:52 UTC, jbrcna commented on test/components/spinbox/spinbox.puppeteer-spec.js
> +      await page.emulate(iPhone);
this is now removed.

2022-03-21 08:52 UTC, jbrcna commented on test/components/spinbox/spinbox.puppeteer-spec.js
> +      await page.goto('http://localhost:4000/components/spinbox/example-sizes.html?theme=uplift&variant=light', { waitUntil: ['domcontentloaded', 'networkidle0'] });
this is now removed.

2022-03-21 08:53 UTC, jbrcna commented on test/components/spinbox/spinbox.puppeteer-spec.js
> +        height: 480,
as discussed, I set the height to 1250 and add 200 timeout bcoz the image is not clear

2022-03-21 08:54 UTC, jbrcna commented on test/components/spinbox/spinbox.puppeteer-spec.js
> +const puppeteer = require('puppeteer');
I also removed this, thank you for your assistance 👍

2022-03-21 11:16 UTC, ericangeles approved these changes
Looks good now! Thanks! 🍌

2022-03-21 11:29 UTC, jbrcna commented
> Looks good now! Thanks! 🍌

wow thank you @ericangeles

2022-03-21 13:32 UTC, tmcconechy approved these changes

2022-03-21 13:32 UTC, merged