6048 - Added closeButton method
infor-design/enterprise pull request #6201
Opened 2022-03-16 02:58 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added closeButton method that defaults to immediately close even when there are subcomponents still opened.

**Related github/jira issue (required)**:

Closes #6048 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/popupmenu/test-modal.html
- Open the modal
- Click one of the Menu Buttons to open the Popupmenu
- With the popupmenu still open, click the Cancel or Save buttons

**Included in this Pull Request**:
- [ ] A note to the change log.

2022-03-16 13:31 UTC, tmcconechy requested changes
@yohannahbautista - I think we should fix this within the existing `close` function and not add a new method. So this always works correctly. So i think we just need to alter the behavior to work not make a new thing you have to remember to call.

cc @EdwardCoyle for suggestion

2022-03-18 13:32 UTC, tmcconechy approved these changes

2022-03-21 12:37 UTC, ericangeles approved these changes

2022-03-21 13:33 UTC, tmcconechy approved these changes

2022-03-21 13:33 UTC, merged