Icon: puppeteer test for enhancement 5595 & 6144
infor-design/enterprise pull request #6202
Opened 2022-03-16 03:19 UTC by jbrcna

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:
closes #5854 , related to #5595 
closes #6199 , related to #6144 

**Steps necessary to review your pull request (required)**:

1. pull this branch
2. build and run the app
3. run npm run e2e:puppeteer icon
4. It should pass.

Result should be

`Mobile icon`
<img width="145" alt="image" src="https://user-images.githubusercontent.com/56722184/158509812-4e060369-3603-460e-a066-6282de95dbad.png">

`Launch icon`
_the image below shows the diff_
<img width="101" alt="image" src="https://user-images.githubusercontent.com/56722184/158509920-87fc54c2-dafa-47ea-b904-15d7e17c278d.png">

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-03-16 13:27 UTC, tmcconechy requested changes
I think you need to push the new image as well for the test?

2022-03-21 07:28 UTC, ericangeles commented
If this is now open for review, please make your PR readable for the reviewers. You can check other PRs for references.

2022-03-21 12:32 UTC, ericangeles commented
Can you add the changelog for the two tickets? Once added, I'll approve this PR.

2022-03-21 13:34 UTC, tmcconechy submitted a review, later dismissed

2022-03-22 07:00 UTC, ericangeles commented on docs/CHANGELOG.md
> +- `[Icon]` Create a puppeteer script for new icons. ([#6202](https://github.com/infor-design/enterprise/pull/6202))
Make it in alphabetical order, then good to go.

2022-03-22 07:22 UTC, jbrcna commented
> Can you add the changelog for the two tickets? Once added, I'll approve this PR.

change log added 👍

2022-03-22 07:23 UTC, ericangeles requested changes

2022-03-22 07:23 UTC, ericangeles commented on docs/CHANGELOG.md
> +- `[Icon]` Create a puppeteer script for new icons. ([#6202](https://github.com/infor-design/enterprise/pull/6202))
The ticket numbers and the links should be the ticket issues, not the PR.

- `[Icon]` Create a puppeteer script for the new launch icon. ([#5854](https://github.com/infor-design/enterprise/issues/5854))
- `[Icon]` Create a puppeteer script for the new mobile icon. ([#6199](https://github.com/infor-design/enterprise/issues/6199))

2022-03-22 07:41 UTC, jbrcna commented
change log updated. and change Create to Created as discussed in our chat. :grin:

2022-03-22 13:10 UTC, tmcconechy approved these changes

2022-03-23 06:04 UTC, ericangeles approved these changes

2022-03-23 06:04 UTC, merged