NG1261 - Added legend load for datepicker
infor-design/enterprise pull request #6239
Opened 2022-03-29 11:36 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will add legend load for datepicker. This will partially fix the issue in NG. The fix still needs to be applied in NG after this EP fix is packaged.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1261

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datepicker/test-legend-loaded.html
- Open datepicker
- Change the month to `February`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-03-29 13:52 UTC, tmcconechy requested changes
From this example i think maybe 

a) that the beforemonthrendered should also fire the first time the list opens as a month is rendering there
b) lets add the listclosed too so we can see it in the test page

Will need the types added laster as well to NG?

2022-03-29 15:09 UTC, tjamesallen15 commented
> From this example i think maybe
> 
> a) that the beforemonthrendered should also fire the first time the list opens as a month is rendering there b) lets add the listclosed too so we can see it in the test page
> 
> Will need the types added laster as well to NG?

yes i will add the types later to NG after this one was merged. I'm having issues on the NG side because its not reflecting if I paste it directly on its dependencies. cc @ericangeles

2022-03-29 15:12 UTC, tmcconechy approved these changes

2022-03-29 18:40 UTC, ericangeles commented
@tmcconechy, we've been encountering that issue for quite some time now, and for some reason, the way we test the EP fix to NG doesn't work anymore even if it's just a CSS solution.

2022-03-30 00:32 UTC, yohannahbautista approved these changes

2022-03-30 13:53 UTC, merged