6229 - Added close button on file error message
infor-design/enterprise pull request #6258
Opened 2022-04-05 06:57 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added close button in file error message based on this: https://www.figma.com/file/fhvZFNoM63LUwJgve8ToJz/file-upload-error-fix?node-id=0%3A1

**Related github/jira issue (required)**:

Addresses an issue in #6229 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/fileupload-advanced/test-max-files.html
- Upload 3 or more files
- Error message should have a close button
- Go to: http://localhost:4000/components/fileupload-advanced/example-failed.html
- Upload a file
- Click the Set Failed button
- Error message should have a close button

**Included in this Pull Request**:
- [ ] A note to the change log.

2022-04-05 21:10 UTC, tmcconechy requested changes
I tried http://localhost:4000/components/fileupload-advanced/example-failed.html and when i clicked the button nothing happened? I double checked and i had the right branch.

Also could you change the button to secondary on that page?

2022-04-05 21:10 UTC, tmcconechy commented on docs/CHANGELOG.md
> +- `[File Upload]` Added close button on file error message ([#6229](https://github.com/infor-design/enterprise/issues/6229))
Should be a new section for 4.63.0 now please

2022-04-07 01:57 UTC, yohannahbautista commented
> I tried http://localhost:4000/components/fileupload-advanced/example-failed.html and when i clicked the button nothing happened? I double checked and i had the right branch.
> 
> Also could you change the button to secondary on that page?

@tmcconechy Hi, you'll need to upload a file first so that an error message will appear, then you can click the fail button while the upload is in progress.

2022-04-07 21:08 UTC, tmcconechy approved these changes

2022-04-08 12:08 UTC, tjamesallen15 approved these changes

2022-04-08 13:22 UTC, merged