NG1262 - Fix on dropdown not moving when pressing key down
infor-design/enterprise pull request #6285
Opened 2022-04-07 01:20 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Add an event handler in body that watches for keydown in dropdown.

**Related github/jira issue (required)**:

Addresses issue in: https://github.com/infor-design/enterprise-ng/issues/1262

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/dropdown/test-label
- Click on a dropdown
- Use arrow up and down
- Selection should update

**Included in this Pull Request**:
- [ ] A note to the change log.

2022-04-07 21:27 UTC, tmcconechy requested changes
@yohannahbautista this case works but seems to have broken this functionality on this test https://github.com/infor-design/enterprise/runs/5865980895?check_suite_focus=true#step:8:2868

Also the alignment looks bad on the example they gave us -> i know its an example but maybe we can make it look a bit better so QA doesnt complain

2022-04-08 13:29 UTC, tmcconechy submitted a review, later dismissed

2022-04-11 03:10 UTC, tjamesallen15 approved these changes

2022-04-11 13:39 UTC, tmcconechy approved these changes

2022-04-11 13:39 UTC, merged