NG1240 - Fix on too wide minimum width when close button is enabled
infor-design/enterprise pull request #6295
Opened 2022-04-11 11:28 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Change minimum width only if screen size is greater than 400.

**Related github/jira issue (required)**:

Addresses issue in: https://github.com/infor-design/enterprise-ng/issues/1240

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Use any device with screen width more narrow than 400 pixels. Or Inspect element and switch to mobile
- Go to: http://localhost:4000/components/modal/example-close-btn.html
- Click Show Modal (Full)
- Content should fit in screen

**Included in this Pull Request**:
- [ ] A note to the change log.

2022-04-11 13:55 UTC, tmcconechy reviewed
Looks good. But maybe we can make all the fields stretch across the modal usisng the respsonsive form classes https://main-enterprise.demo.design.infor.com/components/form/example-inputs-simple.html

Also see one unrelated test fail? Maybe it just needs an image update to pass?

2022-04-12 13:28 UTC, tmcconechy requested changes
One thing i noticed with this solution is now if you go down below 400px you get the same issue. This is around 345px. We probably should flex it so it works in either case

![Screen Shot 2022-04-12 at 9 27 18 AM](https://user-images.githubusercontent.com/814283/162973109-c80d905d-7a78-4331-b9a0-2cec88ed3ddd.png)

2022-04-13 13:17 UTC, tmcconechy submitted a review, later dismissed

2022-04-13 14:33 UTC, tjamesallen15 approved these changes

2022-04-14 13:25 UTC, merged