6304 - allow product developers to add custom class in event labels
infor-design/enterprise pull request #6305
Opened 2022-04-14 18:57 UTC by edinfor

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-04-15 13:25 UTC, tmcconechy requested changes
Looks like a small problem in the log and two tests failing

1. https://github.com/infor-design/enterprise/runs/6029328273?check_suite_focus=true#step:8:2870 -> could be anything you did?
2. Can you try and update with main. I think i fixed this one https://github.com/infor-design/enterprise/runs/6029328273?check_suite_focus=true#step:8:2874 . If it doesnt work after then you can skip this test for now and i'll fix it later? (by changing it to`xit`)

2022-04-15 13:25 UTC, tmcconechy commented on docs/CHANGELOG.md
> +- `[Listview]` Change the font size of heading, subheading, and micro in Listview Component. ([#4996](https://github.com/infor-design/enterprise/issues/4996))
Maybe some merge conflict here? Also please keep alphabatized

2022-04-18 13:19 UTC, tmcconechy commented
Something seems to have happened with the tests https://github.com/infor-design/enterprise/runs/6062552276?check_suite_focus=true#step:8:2938 @edinfor

2022-04-18 14:23 UTC, tmcconechy commented
ok the masthead one is "flaky" can you set it to skip (xit) for now and i'll look later? Thanks

2022-04-18 16:24 UTC, edinfor commented
https://github.com/infor-design/enterprise/runs/6064274729?check_suite_focus=true#step:11:74

any idea why this failed?

2022-04-18 16:38 UTC, tmcconechy commented
Also flaky intermittent i guess

2022-04-18 16:41 UTC, ericangeles commented
Looks like a flaky test, I re-run the build btw.

2022-04-19 13:43 UTC, tmcconechy approved these changes

2022-04-19 13:47 UTC, ericangeles approved these changes

2022-04-19 13:48 UTC, merged