6233 - fix misaligned lookup icon button upon click
infor-design/enterprise pull request #6310
Opened 2022-04-18 07:34 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the misaligned lookup icon button upon clicking/editing.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/6233

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-list-lookup.html
- Click on any `Product Id` cells
- Lookup icon should not be properly aligned and not moving
- Test in Classic and different modes
- Test on Firefox (Issue was produced on Firefox browser)

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2022-04-18 13:33 UTC, tmcconechy requested changes
@ericangeles can you take another look at the xs, sm, and medium row heights they still have the issue (but large looks good now)

2022-04-18 13:38 UTC, ericangeles commented
@tmcconechy oh yeah, I forgot about that!

2022-04-19 13:58 UTC, tmcconechy reviewed
I happened to test this in Firefox and its off there in all the row heights. For chrome it seems ok but f fixing i would check the xs row height again as the border is below the field (sm  moves the icon a bit in edit mode but this is an acceptable amount but could be more perfect 👍🏻 )

2022-04-21 18:54 UTC, tmcconechy approved these changes

2022-04-22 04:43 UTC, yohannahbautista approved these changes

2022-04-22 07:20 UTC, merged