5126 - Field Filter Short: text is not displayed in dropdown
infor-design/enterprise pull request #6330
Opened 2022-04-22 10:58 UTC by iamjamesreyracho

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug on field filter short that the text does not displayed in dropdown.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5126

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go http://localhost:4000/components/field-filter/example-short.html?theme=new&mode=light&colors=0066D4
- Click on dropdown and select an item

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-04-22 16:43 UTC, tmcconechy submitted a review, later dismissed

2022-04-25 08:40 UTC, ericangeles submitted a review, later dismissed

2022-04-25 13:57 UTC, tmcconechy requested changes
Looks good - this is minor but i think the width is off a pixel or two on the right side
![Screen Shot 2022-04-25 at 9 57 21 AM](https://user-images.githubusercontent.com/814283/165104190-543f5060-f449-4c07-87d3-b6ee3a38b055.png)
![Screen Shot 2022-04-25 at 9 57 13 AM](https://user-images.githubusercontent.com/814283/165104191-3383bf0a-bae5-4d63-99b1-be26e6f20e22.png)

2022-04-26 01:31 UTC, yohannahbautista reviewed
There's an empty file in this PR named "git", is this needed?
https://github.com/infor-design/enterprise/pull/6330/files#diff-9a881b9b9f23849475296a8cd768ea1965bc3152df7118e60c145975af6aa58a

2022-04-26 03:47 UTC, tjamesallen15 commented
I think  the empty git file should be removed.

2022-04-26 15:53 UTC, tmcconechy approved these changes

2022-04-27 02:48 UTC, tjamesallen15 approved these changes

2022-04-27 07:49 UTC, merged