5866 field filter field and filter icon issues
infor-design/enterprise pull request #6344
Opened 2022-04-26 08:00 UTC by sesbrenosienna

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR will fix a bug in the alignment of filter icons and text fields and the border radius of the dropdown field in Firefox and Safari. 

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5866

**Steps necessary to review your pull request (required)**:
1st Issue
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/field-filter/example-short.html on Firefox
- Click on the dropdown

2nd Issue
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/field-filter/example-short.html on Safari
- See field for Datepicker/Timepicker/Lookup

3rd Issue 
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/field-filter/example-short.html on Safari
- See the dropdown field 

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-04-26 16:57 UTC, ericangeles requested changes

2022-04-26 16:57 UTC, ericangeles commented on src/components/datepicker/_datepicker.scss
> +      margin-top: 2px;
It's in the main already. I believe this was part of your previous PR.

2022-04-26 16:57 UTC, ericangeles commented on src/components/dropdown/_dropdown.scss
> -  div.dropdown,
Same in here

2022-04-26 17:23 UTC, tmcconechy commented
@sesbrenosienna - as same as @ericangeles i was wondering about the changes to the individual components in the css. Seems out of scope and that they should be isolated to field filter scss. Is it just that we arent updated with main?

2022-04-27 05:44 UTC, yohannahbautista reviewed
Not sure if it should be in this issue, but something to note: the icons "twitch" when you expand the dropdowns in Chrome, Safari, and Firefox (and in Firefox one of them disappears). It works fine in Edge so I'm basing it on that.

2022-04-27 13:50 UTC, tmcconechy commented
One thing to note is the field filter isn't very commonly used and we deprecated it. So maybe leave any remaining issues as its not super important to get 100% right.

2022-04-27 13:50 UTC, tmcconechy approved these changes

2022-04-27 13:58 UTC, ericangeles approved these changes

2022-04-27 14:02 UTC, merged