6400 - TargetedAchievement: Icon is cut off in firefox
infor-design/enterprise pull request #6411
Opened 2022-05-13 01:32 UTC by sesbrenosienna

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes a bug where the icon is cut off in Firefox.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6400

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/targeted-achievement/example-index.html
- Switch to classic theme
- See icon

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-05-13 04:13 UTC, yohannahbautista commented
Hi, it still looks a little bit chopped
<img width="1035" alt="Screen Shot 2022-05-13 at 12 12 33 PM" src="https://user-images.githubusercontent.com/85279127/168209928-dca1ab98-12f3-4429-93e3-df4f3cf46970.png">

2022-05-13 13:28 UTC, tmcconechy submitted a review, later dismissed

2022-05-13 13:29 UTC, tmcconechy approved these changes

2022-05-16 13:36 UTC, tmcconechy approved these changes

2022-05-16 14:02 UTC, ericangeles requested changes
@sesbrenosienna can we fix the pixel cut off on a classic theme as @yohannahbautista mentioned?

2022-05-17 05:52 UTC, ericangeles commented
@yohannahbautista it looks okay on version `100.1` (latest version).

2022-05-17 05:52 UTC, ericangeles approved these changes

2022-05-17 09:41 UTC, merged