6449 - button badge toggle pptr test
infor-design/enterprise pull request #6509
Opened 2022-05-31 06:46 UTC by jbrcna

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

closes  https://github.com/infor-design/enterprise/issues/6449
related to https://github.com/infor-design/enterprise-ng/issues/1241

**Steps necessary to review your pull request (required)**:

1. pull this branch
2. build and run the app
3. run npm run e2e:puppeteer button
4. It should pass.
Given I am on  http://localhost:4000/components/button/test-badge-toggle.html
When no filter is applied
Then the notification badge does not show
And when a filter is applied
Then the notification badge is shown
 

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-05-31 07:33 UTC, yohannahbautista requested changes

2022-05-31 13:31 UTC, jbrcna commented on test/components/button/button.puppeteer-spec.js
> -  const baseUrl = 'http://localhost:4000/components/button';
Hi @yohannahbautista , absolutely. thank you for review

2022-05-31 14:09 UTC, tmcconechy commented on test/components/button/button.puppeteer-spec.js
> +  describe('Button notifBadge test', () => {
```suggestion
  describe('Button notifBadge test', () => {
```

Not sure what was meant here ? Notification badge?

2022-05-31 14:10 UTC, tmcconechy commented on test/components/button/button.puppeteer-spec.js
> +      const notifbadgeContainer = () => page.$eval('#primary-action-one > span.notification-badge-container', element => element.innerHTML);
I think this needs an await

2022-05-31 14:10 UTC, tmcconechy commented on test/components/button/button.puppeteer-spec.js
> +      const elem = () => page.evaluate(() => !!document.querySelector('#primary-action-one > span.notification-badge-container'));
This too needs an await

2022-05-31 14:11 UTC, tmcconechy requested changes
Few small corrections with missing awaits and spelling

2022-06-01 00:00 UTC, yohannahbautista commented on test/components/button/button.puppeteer-spec.js
> +      const elem = () => page.evaluate(() => !!document.querySelector('#primary-action-one > span.notification-badge-container'));
@tmcconechy Hi, there's no need to add await for elem() and notifbadgeContainer() as they're called later with an await: https://github.com/infor-design/enterprise/blob/bc60e484558f9bcf27370b296a5924f9f66f1941/test/components/button/button.puppeteer-spec.js#L52

2022-06-01 00:37 UTC, yohannahbautista commented on test/components/button/button.puppeteer-spec.js
> +      const elem = () => page.evaluate(() => !!document.querySelector('#primary-action-one > span.notification-badge-container'));
Though would it better to use the check toBeFalsy/toBeTruthy instead of having to use "!!" in elem()?

2022-06-01 03:07 UTC, jbrcna commented on test/components/button/button.puppeteer-spec.js
> +      const elem = () => page.evaluate(() => !!document.querySelector('#primary-action-one > span.notification-badge-container'));
> This too needs an await

hi @tmcconechy , @yohannahbautista is correct. If I use await, I get a parsing error.. I insert await as the variable (notifbadgeContainer, elem) gets called

2022-06-01 03:08 UTC, jbrcna commented on test/components/button/button.puppeteer-spec.js
> +      const elem = () => page.evaluate(() => !!document.querySelector('#primary-action-one > span.notification-badge-container'));
Thank you @yohannahbautista  and  @tmcconechy  for the review

2022-06-01 03:09 UTC, jbrcna commented on test/components/button/button.puppeteer-spec.js
> +  describe('Button notifBadge test', () => {
yep, will update this as "Button Notification Badge toggle test"

2022-06-01 03:47 UTC, yohannahbautista approved these changes

2022-06-01 13:46 UTC, tmcconechy commented on test/components/button/button.puppeteer-spec.js
> +      const elem = () => page.evaluate(() => !!document.querySelector('#primary-action-one > span.notification-badge-container'));
ok thanks - i only just glance for the awaits and didnt see that. The problem is if they are missed the tests can be unstable

2022-06-01 13:46 UTC, tmcconechy submitted a review, later dismissed

2022-06-02 14:15 UTC, tmcconechy approved these changes

2022-06-02 15:14 UTC, ericangeles approved these changes

2022-06-02 15:14 UTC, merged