6625 - Fix on max fileupload limit
infor-design/enterprise pull request #6637
Opened 2022-07-07 06:43 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Completed files are not included in the file upload limit

**Related github/jira issue (required)**:

Closes #6625

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/fileupload-advanced/test-max-files.html
- Add two files
- Remove one file
- Add another file

**Included in this Pull Request**:
- [ ] A note to the change log.

2022-07-07 06:45 UTC, ericangeles commented
@yohannahbautista can we add an e2e for this? Thanks! :)

2022-07-07 13:54 UTC, tmcconechy requested changes
@yohannahbautista take care that the is two settings to test [filesmax and filesmaxinprohre](https://github.com/infor-design/enterprise/blob/main/src/components/fileupload-advanced/fileupload-advanced.js#L19-L20)

Aside from this note (maybe add both to the example?) now after this fix i can add as many as like now. (one after the other)

<img width="405" alt="Screen Shot 2022-07-07 at 9 54 25 AM" src="https://user-images.githubusercontent.com/814283/177790791-3c818528-d937-4014-b511-e936432822f8.png">

2022-07-08 13:31 UTC, tmcconechy approved these changes

2022-07-10 23:18 UTC, ericangeles approved these changes

2022-07-10 23:18 UTC, merged