6588 - Fix on edit outline in textarea not filling the entire cell
infor-design/enterprise pull request #6647
Opened 2022-07-11 05:36 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Border is moved to gridcell instead of wrapper so it appears in the entire cell.

**Related github/jira issue (required)**:

Closes #6588 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/test-text-area-with-editor.html
- Click on first Activity cell
- Border should be in the whole cell

**Included in this Pull Request**:
- [ ] A note to the change log.

2022-07-12 00:50 UTC, ericangeles submitted a review, later dismissed

2022-07-12 17:52 UTC, tmcconechy requested changes
I think the reason i had the border on the inner part is because of this problem you can see on http://localhost:4000/components/datagrid/example-editable.html when editing the last row.
![Screen Shot 2022-07-12 at 1 49 54 PM](https://user-images.githubusercontent.com/814283/178559550-90a6ad90-6aad-4f2a-8f93-ad29f0f5f342.png)

Also on http://localhost:4000/components/datagrid/test-text-area-with-editor.html if you edit the first cell the editing goes from centered vertically to top vertically. Maybe we can add a class for this type of editor to the editing input.

So i think we should fix the editing alignment and maybe find a different fix that leaves the border on the inside?

2022-07-14 13:44 UTC, tmcconechy commented
@yohannahbautista yeah i see the complication with centering the text. I noticed with your fix for that it isnt 100% centered and if you open the cell with enter it is not centered.

Maybe just revert that part and we can leave it as it was?

2022-07-15 13:04 UTC, tmcconechy submitted a review, later dismissed

2022-07-18 13:50 UTC, tmcconechy submitted a review, later dismissed

2022-07-20 09:46 UTC, ericangeles approved these changes

2022-07-20 13:48 UTC, merged