6632 - Datepicker Increment/Decrement Settings
infor-design/enterprise pull request #6648
Opened 2022-07-11 09:17 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will add a setting for to allow keyboard hotkeys for increment and decrement of days in datepicker.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6632

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datepicker/test-increment-decrement-day.html
- In the first date field, press `t` to enter todays date
- While in the date field, press the `+` key
- The date should be incremented
- While in the date field, press the `-` key
- The date should be decremented

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-07-12 04:03 UTC, yohannahbautista approved these changes

2022-07-12 04:42 UTC, ericangeles submitted a review, later dismissed

2022-07-12 17:54 UTC, tmcconechy commented on src/components/datepicker/datepicker.js
> + * @param {boolean} [settings.updateWithKeyboard=true] If true, enables increment/decrement of day by using +/- in the keyboard.
```suggestion
 * @param {boolean} [settings.updateWithKeyboard=false] If true, enables increment/decrement of day by using +/- in the keyboard.
```

2022-07-12 17:57 UTC, tmcconechy requested changes
Something a little off here

a) what should the default be? (im fine with it off but should go in "important changes"
b) http://localhost:4000/components/datepicker/example-index.html you can still press "t" but not +/-
c) but http://localhost:4000/components/datepicker/test-increment-decrement-day.html does work as advertised

2022-07-12 17:59 UTC, tmcconechy reviewed
Maybe we could make two settings: `incrementWithKeyboard` `todayWithKeyboard` noting that https://github.com/infor-design/enterprise/issues/6653 is very similar (having a hard idea with the name so open to suggestions).

cc @EdwardCoyle

2022-07-13 15:15 UTC, tmcconechy commented
@tjamesallen15 Can we go ahead and fix https://github.com/infor-design/enterprise/issues/6653 as well with the additional today setting for "t"? Seems closely related

2022-07-13 16:21 UTC, tjamesallen15 commented
> @tjamesallen15 Can we go ahead and fix #6653 as well with the additional today setting for "t"? Seems closely related

Sure. Will do!

2022-07-14 13:46 UTC, tmcconechy approved these changes
Nice 👍🏻

2022-07-18 05:13 UTC, yohannahbautista approved these changes

2022-07-18 13:22 UTC, merged