6587 - Updated filter phrases for datepicker
infor-design/enterprise pull request #6649
Opened 2022-07-12 03:00 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Filter phrases are different for date

**Related github/jira issue (required)**:

Closes #6587 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/example-custom-filter-conditions.html
- Click on filter for date column
- Phrases for the greater and lesser options should be different

**Included in this Pull Request**:
- [ ] A note to the change log.

2022-07-13 15:19 UTC, tmcconechy requested changes
Looks good - but just checking on the phrasing https://github.com/infor-design/enterprise/issues/6587#issuecomment-1183356904

I sort of think what you did might be right but it wasn't what was mentioned by the translation team - so double checking on that comment

2022-07-13 16:56 UTC, tmcconechy commented
@yohannahbautista can you make the options say:
```
Earlier Than
Earlier Than Or Equals
Later Than
Later Than Or Equals
```

Instead? I think maybe the until ect doesn't "flow" as good

2022-07-14 05:50 UTC, ericangeles approved these changes

2022-07-14 10:28 UTC, tjamesallen15 submitted a review, later dismissed

2022-07-14 13:48 UTC, tmcconechy submitted a review, later dismissed

2022-07-15 13:20 UTC, merged