6521 - Editor Paste not working when copied from Windows PDF Reader
infor-design/enterprise pull request #6664
Opened 2022-07-19 06:39 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix bug where paste function is not working on editor when copied from Windows Adobe Reader.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6521

**Steps necessary to review your pull request (required)**:
- Use a Windows PC
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/editor/example-index.html
- Download the pdf in http://www.africau.edu/images/default/sample.pdf
- Open the PDF File
- Copy any line from the PDF File
- Paste it in the Editor

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-07-19 14:06 UTC, tmcconechy requested changes
@tjamesallen15 it seems like this breaks the ability to paste formatted word docs in the editor.
Try to make a word doc that has formatting like bold/fonts and copy paste and you can see its not working anymore.

- is there some way to detect the PDF text in the paste? 
- or figure out why its getting "stripped"?
- we did already have this option to paste as text http://localhost:4000/components/editor/test-paste-as-plain-text.html so what you added seems like the same thing as turning that on. last case we could tell them that they need this on?

2022-07-21 09:47 UTC, tjamesallen15 commented
> 

Hello @tmcconechy ,
When I try to copy from Acrobat Reader (Windows PDF Reader) all I get is text/html and text/rtf types, there are no text/html types which we need to get the bold/italics. See the image below.
![copied from acrobat](https://user-images.githubusercontent.com/34049950/180183482-ccba98ce-84c8-4a07-a664-cdbc335ee919.PNG)

I tried copying from MS Word and I get  the text/html fine. 
![copied from word](https://user-images.githubusercontent.com/34049950/180184158-43a31cd2-d3c9-4eca-a2f5-57c21705d796.PNG)

So what I did is just check if the text/html is there. Now it is working with bold text copied from other sources.

2022-07-21 14:48 UTC, tmcconechy submitted a review, later dismissed
Ok i think this will work. Thanks!

2022-07-22 03:10 UTC, ericangeles commented on docs/CHANGELOG.md
> +- `[Editor]` Fixed a bug where paste function is not working on editor when copied from Windows Adobe Reader. ([#6521](https://github.com/infor-design/enterprise/issues/6521))
I see some duplicate logs. Can you fix it @tjamesallen15 ?

2022-07-22 04:16 UTC, ericangeles approved these changes

2022-07-22 04:20 UTC, merged