6533 - calendar show legend
infor-design/enterprise pull request #6732
Opened 2022-08-12 00:51 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug where listview is not rendering properly when dataset has zero integer value.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6640

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/listview/test-listview-zero.html

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-08-15 13:42 UTC, tmcconechy requested changes
This looks good but maybe we need a button on the example so you can see that you can toggle it on and off.

Suggest replacing the + icon with a hide/show legend text button so we can make sure this works.

2022-08-17 18:43 UTC, tmcconechy approved these changes

2022-08-22 13:46 UTC, tmcconechy approved these changes

2022-08-23 09:41 UTC, ericangeles approved these changes

2022-08-23 09:42 UTC, merged