Ng1347 - badges for buttons with label
infor-design/enterprise pull request #6733
Opened 2022-08-15 01:56 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will add notification badges for buttons with labels.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1347

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/button/example-badge.html

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-08-15 06:20 UTC, tjamesallen15 commented
After this branch is merged, I'll be making an example in NG

2022-08-15 13:43 UTC, tmcconechy requested changes
Seems to be a couple problems in RTL mode. The top icons are invisible and the text ones have the red one slightly out of alignment 

http://localhost:4000/components/button/example-badge.html?locale=ar-SA

2022-08-16 13:51 UTC, tmcconechy submitted a review, later dismissed

2022-08-17 18:43 UTC, tmcconechy approved these changes

2022-08-18 11:11 UTC, yohannahbautista approved these changes

2022-08-18 13:17 UTC, merged