6685 - Fix for Editor Background Color
infor-design/enterprise pull request #6774
Opened 2022-08-24 10:22 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix bug in editor where background color is not rendering properly

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6685

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/editor/example-with-backcolor.html
- Highlight a text
- Change the background color using the tooltip button

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-08-24 15:57 UTC, tmcconechy requested changes
Im seeing an issue if you use both the back color feature and then use the fore color or vise versa, it then resets the previous one. So you can't seta backcolor and then change the forecolor

Thats probably worth a look

2022-08-30 13:51 UTC, tmcconechy approved these changes

2022-08-30 14:11 UTC, ericangeles commented on src/components/editor/editor.js
> +              console.log('bind', value);
Please remove the log @tjamesallen15

2022-08-31 13:33 UTC, deep7102 approved these changes
LGTM 🍌

2022-08-31 13:36 UTC, tmcconechy approved these changes

2022-08-31 13:36 UTC, merged