NG1349 - popupmenu getselected
infor-design/enterprise pull request #6796
Opened 2022-09-02 08:21 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug in popupmenu where getSelected() is not working on multiselectable.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1349

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/popupmenu/example-multi-selectable.html
- Hit the `Popup Menu` and select some items.
- Open `Developer Console`
- Hit the `Get Selected` Button
- See the Selected Items in the `Console`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-09-02 10:03 UTC, ericangeles approved these changes

2022-09-02 14:17 UTC, tmcconechy commented
@tjamesallen15 a couple of minor suggestions

- can make that he button secondary in the example (primary is for forms)
- could make the example log .getSelected()so we can see the results are correct in the log ( i did verify)
- could change the id name (says single select but it isnt)
- could add a test?

2022-09-02 14:24 UTC, ericangeles commented
+1 on testing

2022-09-06 13:37 UTC, tmcconechy requested changes
Marking as request changes to please fix https://github.com/infor-design/enterprise/pull/6796#issuecomment-1235560719

2022-09-07 13:18 UTC, tmcconechy approved these changes

2022-09-07 13:18 UTC, merged