6686 - Searchfield visual fixes on go button
infor-design/enterprise pull request #6824
Opened 2022-09-15 09:25 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjusted heights of category and go buttons. Add additional go button width in buttonset if buttonset width is too small so it won't be cut off.

To note: Using flex toolbar with category and go button in searchfield results in weird visual bugs, still a work in progress as of now.

**Related github/jira issue (required)**:

Closes #6686 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html

On uneven searchfield height:
- Click on the searchfield to focus it
- Click anywhere else on the page

On cut off go button:
- Resize the window small enough where the searchfield collapses
- Expand the window with the maximize button

**Included in this Pull Request**:
- [ ] A note to the change log.

2022-09-15 11:38 UTC, ericangeles commented
@yohannahbautista can we add unit testing? (More on visual test)

2022-09-15 13:35 UTC, tmcconechy requested changes
@yohannahbautista when i focus the search field i still see it grow in size on the top and bottom? I think that was part of what should be fixed?

2022-09-16 03:15 UTC, yohannahbautista commented
> @yohannahbautista when i focus the search field i still see it grow in size on the top and bottom? I think that was part of what should be fixed?

@tmcconechy  @ericangeles 
Hello, sorry I might have misunderstood. I based the growing and shrinking on this example page: https://main-enterprise.demo.design.infor.com/components/header/example-non-collapsible-searchfield.html
The searchfield expands on focus. I assumed the main issue was that the input field and the category/go buttons don't have the same height. Should the searchfield not expand at all on focus when it's in header?

2022-09-16 04:36 UTC, ericangeles commented
@yohannahbautista that should also need to fix. The correct behavior is there should be no border before and after typing anything. I see another related page that needs to be fixed too http://localhost:4000/components/tabs-module/example-category-searchfield-go-button.html

These are the test pages that need to look out
- http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
- http://localhost:4000/components/tabs-module/example-category-searchfield-go-button.html
- http://localhost:4000/components/header/example-toolbar-flex-with-basic-searchfield.html
- http://localhost:4000/components/header/example-non-collapsible-searchfield.html

Please check other test pages as I may have missed them.

This is the correct one
- http://localhost:4000/components/header/example-toolbar-flex-with-categories.html (try to see if you can fix the moving part when clicking the searchfield?)

2022-09-16 04:38 UTC, ericangeles commented
Figma file for more information https://www.figma.com/file/gS5jIE14am8hYEvmtIAXLv/IDS-Search?node-id=209%3A2536

2022-09-23 10:04 UTC, ericangeles commented
@yohannahbautista am still seeing some grey-ish border (combination of hovering and clicking)

2022-09-26 13:58 UTC, tmcconechy commented on app/views/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html
> +  .no-frills {
Is this needed? I dont see this class anywhere. But if it fixes something in searchfield it should probably go there.

2022-09-27 08:53 UTC, yohannahbautista commented on app/views/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html
> +  .no-frills {
Hello, there's padding that happens when the page is in classic and the layout is no frills. It also happens in the main branch. I added it because a visual test fails
<img width="1792" alt="Screen Shot 2022-09-27 at 4 50 06 PM" src="https://user-images.githubusercontent.com/85279127/192480423-1774eabf-ef91-41a0-a2be-bbd1deaa8912.png">

2022-09-27 14:14 UTC, tmcconechy commented
![Screen Shot 2022-09-27 at 10 13 50 AM](https://user-images.githubusercontent.com/814283/192550704-74289e9c-f3e5-4afb-ba30-2e8bee3c5914.png)

Still looks a little off in mobile mode. Also a test seems to be failing (not sure if its a flaky test or not)

2022-09-28 12:20 UTC, ericangeles commented
@yohannahbautista I notice that the go button height changed from `38px` to `36px`?

2022-09-29 04:37 UTC, yohannahbautista commented
> @yohannahbautista I notice that the go button height changed from `38px` to `36px`?

I changed the go button height when the searchfield is a searchfield toolbar because it looks bigger in its usual height
<img width="447" alt="Screen Shot 2022-09-29 at 12 36 58 PM" src="https://user-images.githubusercontent.com/85279127/192940040-77fd3cfa-55ec-4be0-b196-69a081e2233a.png">

2022-09-29 04:57 UTC, ericangeles commented
I think we should stick on 38px. You just need to adjust the searchfields height.

2022-09-29 05:00 UTC, ericangeles commented
Check if there's any border top and bottom (searchfield) to adjust its height?

2022-09-30 13:51 UTC, tmcconechy commented
sorry @yohannahbautista still seeing an issue on mobile (resize the page in chrome as small width as it can go on desktop)
![Screen Shot 2022-09-30 at 9 50 29 AM](https://user-images.githubusercontent.com/814283/193284756-c005d04a-c242-4f0e-a7a0-440492f59b66.png)

2022-10-03 11:01 UTC, ericangeles approved these changes

2022-10-03 13:39 UTC, merged