6678 - Trigger field alignment for classic
infor-design/enterprise pull request #6835
Opened 2022-09-20 08:45 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Classic theme adjustments for trigger field

**Related github/jira issue (required)**:

Closes #6678 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: 
   - http://localhost:4000/components/datagrid/test-editable-trigger-fields.html
   - http://localhost:4000/components/datagrid/test-editable-trigger-fields.html?theme=classic
- Check each field in each row size

**Included in this Pull Request**:
- [ ] A note to the change log.

2022-09-21 14:39 UTC, tmcconechy submitted a review, later dismissed
Looks good only minor movement 👍🏻

2022-09-22 14:00 UTC, tmcconechy approved these changes

2022-09-23 09:54 UTC, ericangeles requested changes

2022-09-23 09:54 UTC, ericangeles commented on docs/CHANGELOG.md
> +- `[Typography]` Updated text link color in dark theme. ([#6807](https://github.com/infor-design/enterprise/issues/6807))
@yohannahbautista can you rearrange alphabetically and remove duplicate logs?

2022-09-26 13:59 UTC, tmcconechy approved these changes

2022-09-26 14:34 UTC, ericangeles approved these changes

2022-09-26 14:42 UTC, merged