6748 - Bar Charts Identical Arias
infor-design/enterprise pull request #6838
Opened 2022-09-21 03:07 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

...

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6748

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/bar-grouped/example-formatter.html
- Inspect element for each of the bars.
- See that they have identical aria labels.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-09-21 14:46 UTC, tmcconechy requested changes
Re-reading the issue the issue is that they all should not have the same label. Also i think having "item value" for the aria label isnt very useful. I think it would be better to put the value in there (same value in the tooltip i.e. 4.58, 2.46 ect). That way this is what the screen reader will tell you and it will tell you the bar info.

2022-09-27 14:26 UTC, tmcconechy commented
@tjamesallen15 i think its better to be an aria-label because aria-describedby would be an ID that should point to something https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-describedby

I also looked into this and i think it should be aria-label = "Schedule Adherence By Quantity 4.5" 
I.E. the legend label as well as the value for each bar.

2022-09-27 14:41 UTC, ericangeles commented
@tjamesallen15 let me know if you need help on this, let's have a quick call tomorrow.

2022-09-29 14:34 UTC, yohannahbautista approved these changes

2022-09-29 16:02 UTC, tmcconechy approved these changes

2022-09-29 16:02 UTC, merged