6773 - fix for validation breaks after enabling disabling
infor-design/enterprise pull request #6861
Opened 2022-09-28 08:30 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug in textarea where validation breaks after enabling/disabling.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6773

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/textarea/test-toggle.html
- Focus the textarea and then click anywhere outside it to remove the focus. The validation error should now should up.
- Click the `Toggle` button and confirm the textarea is disabled.
- Click the `Toggle` button again to enable the textarea.
- Start typing in the textarea and notice that the validation is now okay.

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-09-28 16:42 UTC, tmcconechy requested changes
Im not seeing it work as per the steps. It seems like pressing the button to toggle the disabled state is not working (its not getting disabled)

2022-09-28 16:42 UTC, tmcconechy commented on app/views/components/textarea/test-toggle.html
> +  $('.btn-primary').on('click', () => {
```suggestion
  $('#btn-toggle').on('click', () => {
```

Maybe need this.

2022-09-29 01:28 UTC, tjamesallen15 commented on app/views/components/textarea/test-toggle.html
> +  $('.btn-primary').on('click', () => {
> Maybe need this.

My bad. I was really sleepy when I PRed this. Thank you Tim!

2022-09-29 14:15 UTC, yohannahbautista approved these changes

2022-09-29 17:58 UTC, tmcconechy approved these changes

2022-09-29 17:59 UTC, merged