NG1363 - rich text editor breaking space dirty indicator
infor-design/enterprise pull request #6863
Opened 2022-09-28 12:55 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug in editor where breaking space doesn't render dirty indicator properly.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1363

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/editor/test-dirty-tracking.html
- Try to type a letter to the editor to make it dirty
- Delete the typed letter

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-09-28 16:56 UTC, tmcconechy requested changes
@tjamesallen15 i tried this one and it seems like the dirty tracker isnt appearing at all.

http://localhost:4000/components/editor/test-dirty-tracking.html
- type anywhere in the editor -> no dirty indicator shown

So cant complete the testing

2022-09-29 14:20 UTC, yohannahbautista approved these changes

2022-09-29 17:47 UTC, tmcconechy approved these changes

2022-09-29 18:18 UTC, ericangeles approved these changes

2022-09-29 18:18 UTC, merged