5907 - datagrid tooltip flashes continuously
infor-design/enterprise pull request #6870
Opened 2022-10-04 00:24 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug in datagrid where tooltip flashes continuously on hover.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5907

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-custom-long-tooltip.html
- Hover over cell in the "Exception" column

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-10-13 07:18 UTC, tjamesallen15 commented
Will fix the E2E after this is reviewed.

2022-10-14 14:39 UTC, ericangeles commented on src/components/datagrid/datagrid.js
> +        if ($('.grid-tooltip:hover').length > 0) {
Did you try to use `.grid-tooltip:not(.is-hidden)` class instead of :hover selector?

2022-10-17 10:48 UTC, tjamesallen15 commented on src/components/datagrid/datagrid.js
> +        if ($('.grid-tooltip:hover').length > 0) {
yes. it somehow doesn't work thats why I used the hover selector.

2022-10-17 14:59 UTC, tmcconechy requested changes
I think this works pretty good except i would test more.. I see at least one issue going through:

http://localhost:4000/components/datagrid/ (names have tooltip in them)
compare to https://main-enterprise.demo.design.infor.com/components/datagrid/

a) if i move the mouse down the column the tooltips dont show for each cell anymore.
- go to http://localhost:4000/components/datagrid/example-tooltips.html
- hover the arrow on row one and get the tooltip
- hover  the arrow on row two and i no longer get the tooltip
- compare to https://main-enterprise.demo.design.infor.com/components/datagrid/example-tooltips.html
b) same on the example with the big tooltip http://localhost:4000/components/datagrid/test-custom-long-tooltip.html moving down

2022-10-19 15:10 UTC, tmcconechy submitted a review, later dismissed

2022-10-20 13:34 UTC, tmcconechy commented
@tjamesallen15 fix looks good but the build is failing https://github.com/infor-design/enterprise/actions/runs/3287748709/jobs/5417584258#step:8:2754 maybe we need to update this one?

2022-10-20 21:05 UTC, tjamesallen15 commented
> @tjamesallen15 fix looks good but the build is failing https://github.com/infor-design/enterprise/actions/runs/3287748709/jobs/5417584258#step:8:2754 maybe we need to update this one?

Yes, yes. Will be updating today.

2022-10-21 13:33 UTC, tmcconechy submitted a review, later dismissed

2022-10-25 14:29 UTC, tmcconechy approved these changes

2022-10-25 14:29 UTC, tmcconechy approved these changes

2022-10-27 04:21 UTC, merged