6900 - Extra class test for tooltip
infor-design/enterprise pull request #6906
Opened 2022-10-19 08:11 UTC by janahintal

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

6900 - Extra class test for tooltip

**Related github/jira issue (required)**:

Closes #6900 

**Steps necessary to review your pull request (required)**:

`pull this branch
build and run the app
run npm run e2e:puppeteer datagrid
It should pass.`

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-10-19 08:24 UTC, ericangeles requested changes

2022-10-19 08:24 UTC, ericangeles commented on test/components/datagrid/datagrid.puppeteer-spec.js
> +    it.only('should show tooltip when hovered', async () => {
Please remove `only`

2022-10-19 08:24 UTC, ericangeles commented on test/components/datagrid/datagrid.puppeteer-spec.js
> +    it.only('should show tooltip when hovered', async () => {
As well in here

2022-10-19 08:25 UTC, ericangeles requested changes

2022-10-19 08:25 UTC, ericangeles commented on test/components/datagrid/datagrid.puppeteer-spec.js
> +    it.only('should show tooltip when hovered', async () => {
`should append the custom tooltip class`

2022-10-21 04:18 UTC, tjamesallen15 approved these changes

2022-10-25 02:18 UTC, ericangeles approved these changes

2022-10-25 02:19 UTC, merged