NG1365 datagrid value input field inline editor
infor-design/enterprise pull request #6909
Opened 2022-10-21 05:06 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug in datagrid where tooltip flashes continuously on hover.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1365

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to hhttp://localhost:4000/components/datagrid/test-editable-with-inline-editor.html
- Hover over cell in the `Exception` column

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-10-21 05:36 UTC, ericangeles commented
@tjamesallen15 can you also create an e2e for this?

2022-10-21 13:37 UTC, tmcconechy requested changes
only issue i see is the styling when there is an error... (clear the field). I think we need some special css for errors in inline editors.

![Screen Shot 2022-10-21 at 9 37 09 AM](https://user-images.githubusercontent.com/814283/197209211-c10f01df-ea26-4def-868d-f9f35e35e636.png)

2022-10-24 14:03 UTC, tmcconechy approved these changes

2022-10-25 02:21 UTC, ericangeles approved these changes

2022-10-25 02:22 UTC, merged