6868  - Fix icon fallout
infor-design/enterprise pull request #6935
Opened 2022-11-01 16:59 UTC by tmcconechy

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Additional fix(s) for the icon changes - may add to this as QA works

**Related github/jira issue (required)**:
#6868

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/validation/test-alert-types.html
- make sure all alerts line up with the text

2022-11-02 06:39 UTC, ericangeles submitted a review, later dismissed

2022-11-07 05:02 UTC, ericangeles commented
Open for review now @tmcconechy ?

2022-11-07 08:24 UTC, ericangeles requested changes
Everything looks good, except for error-icon position. All icons are okay in classic.

<img width="322" alt="Screen Shot 2022-11-07 at 4 22 23 PM" src="https://user-images.githubusercontent.com/8839327/200261051-a7319955-0eab-4412-8dee-ad35d57b4a00.png">

2022-11-07 21:51 UTC, tmcconechy commented
All set here. Will make beta tomorrow

2022-11-08 08:56 UTC, ericangeles approved these changes

2022-11-08 17:06 UTC, merged