6673 - Adjusted header and tab colors in themes
infor-design/enterprise pull request #6941
Opened 2022-11-03 06:41 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjusted header and tab colors in themes.

**Related github/jira issue (required)**:

Closes #6673 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: localhost:4000/components/tabs-module/example-index.html

**Included in this Pull Request**:
- [ ] A note to the change log.

2022-11-04 09:33 UTC, ericangeles commented
Fix for chrome version issue https://github.com/infor-design/enterprise/pull/6945

2022-11-07 04:12 UTC, tjamesallen15 submitted a review, later dismissed

2022-11-07 18:12 UTC, tmcconechy requested changes
@yohannahbautista this isnt quite right. the active tab color should be the same color as the header color

http://localhost:4000/components/tabs-module/example-index.html 
-both should be #0072ED

2022-11-09 06:44 UTC, ericangeles submitted a review, later dismissed

2022-11-09 14:28 UTC, tmcconechy approved these changes

2022-11-10 15:43 UTC, merged