6917 - Adjusted date and timepicker icons in datagrid filter
infor-design/enterprise pull request #6946
Opened 2022-11-07 04:04 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjusted position and sizes of date and timepicker for datagrid filter rows.

**Related github/jira issue (required)**:

Closes #6917 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- In Safari, go to: http://localhost:4000/components/datagrid/test-editable-datetime.html
- Datepicker and timepicker icons should appear in filter row

**Included in this Pull Request**:
- [ ] A note to the change log.

2022-11-07 04:59 UTC, ericangeles commented on docs/CHANGELOG.md
> +- `[Datagrid]` Adjusted date and timepicker icons in datagrid filter. ([#6917](https://github.com/infor-design/enterprise/issues/6917))
@yohannahbautista can you move this to 4.70?

2022-11-07 08:19 UTC, ericangeles commented
Looks like you need to update the visual images https://github.com/infor-design/enterprise/actions/runs/3407461002/jobs/5667118442#step:8:2406

2022-11-07 18:17 UTC, tmcconechy requested changes
Looks good for the most part @yohannahbautista but if you try 

- open safari
- go to http://localhost:4000/components/datagrid/test-editable-datetime.html?theme=new&mode=light&colors=0066D4
- change to extra small or small row height
- in those the icons still have the same issues but the other two row heights are fixed

2022-11-09 14:32 UTC, tmcconechy approved these changes

2022-11-09 14:52 UTC, tmcconechy commented
Fix looks good now @yohannahbautista - but i think some images need updates...

2022-11-10 10:15 UTC, ericangeles approved these changes

2022-11-10 15:45 UTC, tmcconechy approved these changes

2022-11-10 15:45 UTC, merged