6952 - datagrid dirty cell indicator frozen
infor-design/enterprise pull request #6962
Opened 2022-11-10 06:25 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix a bug in datagrid where clear dirty cell does not work properly in frozen columns.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6952

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-addrow-with-frozen-columns.html
- Click `Add Row`
- Enter new values for each of the columns in the new row
- Notice the dirty indicator on each cell
- Click on `Save and New`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2022-11-10 15:53 UTC, tmcconechy requested changes
See a related issue (maybe not new but looks awkward).

- Press add
- type in the product name cell -> notice the icon is missing/hidden
- press save and new -> notice the ! is missing in the icon

<img width="187" alt="Screen Shot 2022-11-10 at 10 52 21 AM" src="https://user-images.githubusercontent.com/814283/201142611-c4fa8355-978c-434f-8fc0-81bf48c7e8d4.png">

2022-11-11 14:51 UTC, tmcconechy approved these changes
Still not seeing the ! on the second column. But i think we can let that go. Unless its a quick fix as it wasnt what was reported

2022-11-11 17:03 UTC, deep7102 approved these changes

2022-11-11 18:05 UTC, tmcconechy approved these changes
I Fixed the bug with clearCellError

2022-11-11 18:05 UTC, tmcconechy approved these changes

2022-11-11 18:52 UTC, deep7102 approved these changes

2022-11-11 19:39 UTC, merged