7008 - Add ability to change the header color in datagrid
infor-design/enterprise pull request #7030
Opened 2022-12-13 13:58 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2022-12-14 08:04 UTC, tjamesallen15 approved these changes
Well I didn't see anything wrong and it looks good. I based the review on the figma.

2022-12-14 16:14 UTC, tmcconechy requested changes
Looks good but a few things..

1. try new - contrast mode - notice the borders should be the same color
<img width="478" alt="Screen Shot 2022-12-14 at 2 14 27 PM" src="https://user-images.githubusercontent.com/814283/207692141-160561b5-0085-4d23-aa84-ca899e20971e.png">
1.  in classic mode hovering the dropdowns seem to show the border but is too light (may have been like this before)

2022-12-15 02:43 UTC, yohannahbautista submitted a review, later dismissed

2022-12-15 07:36 UTC, ericangeles commented on src/components/datagrid/datagrid.js
> +      (self?.headerRowLeft?.find('th').addClass('light'), self?.headerRow?.find('th').addClass('light'), self?.headerRowRight?.find('th').addClass('light')) :
@tmcconechy `headerRowLeft` is in different table so it needs to add class there.

2022-12-15 07:45 UTC, ericangeles commented on src/components/datagrid/datagrid.js
> +      (self?.headerRowLeft?.find('th').addClass('light'), self?.headerRow?.find('th').addClass('light'), self?.headerRowRight?.find('th').addClass('light')) :
@tmcconechy I didn't change anything in the border color in classic, looking at the older version, it seems the same.

2022-12-15 15:09 UTC, tmcconechy commented on src/components/datagrid/datagrid.js
> +      (self?.headerRowLeft?.find('th').addClass('light'), self?.headerRow?.find('th').addClass('light'), self?.headerRowRight?.find('th').addClass('light')) :
Sure just looked off when testing. I would either do a quick fix or we can make an issue for later? Classic isn't really too important

2022-12-15 15:30 UTC, tmcconechy approved these changes
This is good for me now. Classic isnt important. Just need any tests you may want to fix (or skip)

2022-12-15 15:34 UTC, tmcconechy commented
Oh @ericangeles can you pr the type for the new setting in NG - they will need that 👍🏻

2022-12-15 15:57 UTC, deep7102 approved these changes

2022-12-16 11:27 UTC, ericangeles commented
@tmcconechy @deep7102 am skipping the visual tests as my docker's acting weird.

2022-12-16 14:39 UTC, tmcconechy commented
Looks like just some lint stuff.

2022-12-16 17:46 UTC, tmcconechy approved these changes

2022-12-16 20:44 UTC, merged