7000 - Icon Clipping Issue
infor-design/enterprise pull request #7077
Opened 2023-01-06 11:43 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR will fix the visibility of primary button on new design.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7000

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-card-cell.html
- Check the icon price alignment

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2023-01-06 14:27 UTC, ericangeles submitted a review, later dismissed

2023-01-06 15:07 UTC, tmcconechy requested changes
I feel like this doesnt really line up. I would include the text with it if we are going to fix

- label should line with the data text
- icon should be centered as well

<img width="307" alt="Screenshot 2023-01-06 at 10 05 36 AM" src="https://user-images.githubusercontent.com/814283/211039210-e96b62f5-e549-41c2-ac47-79a0e866af35.png">

@pwpatton how do you feel about the icon being on the other side? next to the $500?

2023-01-09 09:14 UTC, ericangeles commented
@yohannahbautista can you adjust the icon as well?

2023-01-09 09:18 UTC, ericangeles commented
Never mind, I'm on the branch where I fixed it.

2023-01-09 14:40 UTC, tmcconechy submitted a review, later dismissed

2023-01-09 16:05 UTC, merged