7108 - Fix dropdown't swatch default color in dark theme
infor-design/enterprise pull request #7151
Opened 2023-01-31 19:25 UTC by andriivarhanov

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This PR fixes dropdown's default swatch color in dark mode by removing `primary-bg-color` from dropdown's scss

**Related github/jira issue (required)**:
Closes #7108 

**Steps necessary to review your pull request (required)**:
- pull and build
- go to http://localhost:4000/components/personalize/example-color-theme-api.html?colors=0066D4&theme=new&mode=dark
- check the `Theme Colors` dropdown
- see the swatch color is theme's dark color
- open the dropdown
- see the swatch in dropdown's options has theme's dark color

**Included in this Pull Request**:
- [x] A note to the change log.

2023-01-31 19:45 UTC, tmcconechy requested changes
@andriivarhanov there is a bit more to this. i think we need to correct all themes for example

http://localhost:4000/components/personalize/example-color-theme-api.html 
- in light it should be white swatch since the header is now white
- same with contrast http://localhost:4000/components/personalize/example-color-theme-api.html?theme=new&mode=contrast

Looks like the rest are ok, but im just cycling through the dropdown for the theme and making sure the swatch matched the header.

This is not urgent anymore however, the team said we can wait on it for next release.

2023-02-01 14:44 UTC, tmcconechy commented
@andriivarhanov when you update this fix. I pushed fixes to main. This means

1. The change log goes in 4.81.0 fixes now
2. You will need node 18 now and to update all dependencies

```
nvm use
rm -rf node_modules
npm i
```

2023-02-01 14:52 UTC, andriivarhanov commented
@tmcconechy I've added colors for each theme for the swatch, ready for review. I was working on node 18 since yesterday from your 6634 branch since node 14 didn't work for me, it's great it was merged, thanks

2023-02-01 16:58 UTC, tmcconechy approved these changes

2023-02-02 15:17 UTC, deep7102 approved these changes

2023-02-02 15:19 UTC, merged