7005 - Fix on inverse colors not showing in popupmenu in masthead
infor-design/enterprise pull request #7155
Opened 2023-02-02 06:46 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Removed containerClass undefined check

**Related github/jira issue (required)**:

Closes #7005 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/popupmenu/test-masthead
- Click on "No Class"
- Click on "Has Class"
- Both popups should use inverse colors

**Included in this Pull Request**:
- [ ] A note to the change log.

2023-02-02 14:58 UTC, tmcconechy requested changes
@yohannahbautista the popup looks good now but the colors on the button are incorrect for some reason?

1. text is barely visible
2. the click state is showing the default button state - should match the darker color
3. also i see on http://localhost:4000/components/masthead/test-popups-on-each-side.html there is a little blue line on the button.
4. also on http://localhost:4000/components/masthead/test-popups-on-each-side.html the search field looks to close to the bottom

There is some styles for it on https://www.figma.com/file/ok0LLOT9PP1J0kBkPMaZ5c/IDS-Component-File-v4.6-(Draft)?node-id=119%3A148&t=GVN3StvDkRg9yOkh-0 

But i think we should try slate 01 or 02 and then white on the hover...

2023-02-03 15:53 UTC, tmcconechy commented
@yohannahbautista tested again...see a couple things..

1. On http://localhost:4000/components/popupmenu/test-masthead is the colors the same as http://localhost:4000/components/masthead/test-popups-on-each-side.html ? because they look passable on the later but the first one they dont..
2. On http://localhost:4000/components/popupmenu/test-masthead try changing theme /mode - some modes are invisible like contrast. For themes this component just stays the same and shouldn't change
3. Some alignment issues on http://localhost:4000/components/masthead/test-popups-on-each-side.html
- the button sits a bit low
- the search isnt centered 100% when expanded

2023-02-06 14:37 UTC, tmcconechy commented
- i still see the issues on http://localhost:4000/components/masthead/test-popups-on-each-side.html
- i tried to fix the change log conflict but the online git tool wasnt working. So maybe also fix the conflict locally

2023-02-07 14:49 UTC, tmcconechy approved these changes

2023-02-08 16:31 UTC, ericangeles approved these changes

2023-02-08 16:31 UTC, merged