7134 - Custom button adjustments in mobile
infor-design/enterprise pull request #7157
Opened 2023-02-03 06:53 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Additional adjustments in custom button for mobile screen width.

**Related github/jira issue (required)**:

Addresses comment: https://github.com/infor-design/enterprise/issues/7134#issuecomment-1409795239

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Change screen width to mobile
- Go to: http://localhost:4000/components/searchfield/example-buttons.html?theme=classic&mode=light
- Click on searchfield
- Type on searchfield
- Check that icons are aligned

**Included in this Pull Request**:
- [ ] A note to the change log.

2023-02-03 15:58 UTC, tmcconechy commented on docs/CHANGELOG.md
> +## v4.82.0 Fixes
4.81.0 is correct for the next version..

2023-02-03 16:00 UTC, tmcconechy requested changes
The only issue(s) i see are..

- resize to mobile
- click the search to expand
- press the collapse button -> it collapses and then expands again
- click the search to expand
- click out of the field to collapse -> what as it collapses centered then to the side (looks clunky if that can be fixed)
- also the "toolbar" text is extremely small. can you check it?

2023-02-06 14:39 UTC, tmcconechy commented
- change log conflict
- on http://localhost:4000/components/searchfield/example-buttons.html?theme=classic&mode=light i still see:
  - the icon is now cut off
  - the animation looks very clunky when collapsing

2023-02-07 14:51 UTC, tmcconechy commented
Still seeing a weird animation. Do you think its fixable @yohannahbautista ?
https://watch.screencastify.com/v/llQRSQqlfa0ex1Jr1QsN

2023-02-09 10:58 UTC, yohannahbautista commented
> Still seeing a weird animation. Do you think its fixable @yohannahbautista ? https://watch.screencastify.com/v/llQRSQqlfa0ex1Jr1QsN

@tmcconechy  @ericangeles 
Hello, the jittery animation is something that also appears in older versions: https://4660-enterprise.demo.design.infor.com/components/searchfield/example-buttons
It might have something to do with the transition when the width changes. I didn't see any changes in styling midway through it collapsing, it should change to width 34px once the focus and active classes are removed. It might take time to find a solution for it.

2023-02-09 11:14 UTC, ericangeles commented
@tmcconechy maybe we can separate this issue?

2023-02-09 15:03 UTC, tmcconechy commented
Sure if you need to ~ but it looks pretty clunky to me.

2023-02-10 17:09 UTC, tmcconechy approved these changes

2023-02-14 15:55 UTC, tmcconechy approved these changes

2023-02-15 14:24 UTC, tmcconechy approved these changes

2023-02-15 16:46 UTC, ericangeles approved these changes

2023-02-15 16:47 UTC, merged