5785 - calendar week number
infor-design/enterprise pull request #7178
Opened 2023-02-08 07:23 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add weekview number on the monthview in datepicker. Use `showWeekNumber` to enable it.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/5785

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datepicker/test-show-week-number.html
- Open datepicker
- See the week number beside

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-02-08 16:25 UTC, ericangeles requested changes

2023-02-08 16:25 UTC, ericangeles commented on src/components/monthview/monthview.js
> +    for (let i = 0; i < currentWeekCount; i++) {
In terms of performance, I suggest you to create a week number variable e.g., `weekNumbersHTML` and concatenate the week numbers to it instead of immediately appending it to `weekNumber` so it will reduce the number of DOM updates. 

E.g.,
```
  let weekNumbersHTML = '';
  for (let i = 0; i < currentWeekCount; i++) {
    weekNumbersHTML += `<tr><td><span>${week + i}</span></td></tr>`;
  }
  this.weekNumber.append(weekNumbersHTML);

```

2023-02-08 16:25 UTC, ericangeles commented on src/components/monthview/monthview.js
> +   * @param {number} month The zero based month to display
Minor -- it should be `monthNumber`?

2023-02-08 16:25 UTC, ericangeles commented on src/components/monthview/monthview.js
> +   * @param {number} month The zero based month to display
Same minor -- change `month` to `monthNumber`

2023-02-08 17:52 UTC, tmcconechy requested changes
Looks pretty good @tjamesallen15 

- border color should be B7B7BA according to the design
- and with that change for other theme/modes it should be 1 color less than the other borders (dark i think goes 1 more). For example slate04 vs slate03
- W# might be weird to translate or require translation. Can you make a new translation for it so we can put it in other languages? (put it in en-messages.js)

2023-02-09 14:52 UTC, EdwardCoyle commented
I found a couple things:

On the popups that display week numbers, if you open the Month/Year expander inside, the alignment of the separator is off (probably needs flex CSS rules):

<img width="406" alt="Screen Shot 2023-02-09 at 9 43 11 AM" src="https://user-images.githubusercontent.com/3249601/217846763-fa26b6e2-cac3-4f2a-9200-e1da3edd8683.png">

----

Additionally: I can't seem to replicate the steps 100% of the time, but there is some combination of steps that causes the Month View's `selectDay` method to error out with a `null` date at this line: https://github.com/infor-design/enterprise/blob/fa43d801e886556f59d0038fb871a13ed5d1700c/src/components/monthview/monthview.js#L2131 I triggered it by switching months forward/backward and selected random dates, disabled or otherwise:

<img width="1641" alt="Screen Shot 2023-02-09 at 9 46 24 AM" src="https://user-images.githubusercontent.com/3249601/217846700-6261e209-f6d1-4112-ac99-9f30bfd11cca.png">

2023-02-09 16:30 UTC, tmcconechy commented
My comments are resolved. Thanks @tjamesallen15 . Once the rest are i will approve.

2023-02-10 01:50 UTC, tjamesallen15 commented
I tried @EdwardCoyle steps on how to reproduce and i can't seem to reproduce on my end.

2023-02-10 17:11 UTC, tmcconechy approved these changes

2023-02-11 18:10 UTC, ericangeles approved these changes

2023-02-11 18:10 UTC, merged