6014 - Go button adjustments for flex toolbar
infor-design/enterprise pull request #7239
Opened 2023-02-20 10:43 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjustments in searchfield for go and category button in flex toolbar

**Related github/jira issue (required)**:

Closes #6014 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html
- Check that searchfield icons are aligned
- Check in versions and modes

**Included in this Pull Request**:
- [ ] A note to the change log.

2023-02-21 15:14 UTC, tmcconechy requested changes
Something seems wrong with the go button borders (in all modes) both mobile size and non mobile size.
<img width="646" alt="Screenshot 2023-02-21 at 10 13 05 AM" src="https://user-images.githubusercontent.com/814283/220383942-0c1917a8-3fc6-4a5b-82c3-1aff9fdf549d.png">
<img width="287" alt="Screenshot 2023-02-21 at 10 13 11 AM" src="https://user-images.githubusercontent.com/814283/220383945-a9feb659-6495-4751-a287-664fe57c9ed1.png">

2023-02-23 14:42 UTC, tmcconechy commented
The only think that would imporve this is if we added the hover state to the go bottom. The same as

![image](https://user-images.githubusercontent.com/814283/220939420-d41a015e-b754-4cf4-8991-17f65ac49e33.png)

2023-02-24 15:13 UTC, tmcconechy approved these changes

2023-02-24 15:53 UTC, deep7102 approved these changes

2023-02-27 05:56 UTC, ericangeles approved these changes

2023-02-27 05:56 UTC, merged