6528 - Listview Translation
infor-design/enterprise pull request #7247
Opened 2023-02-21 07:47 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add an additional translation for records selected in listview.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/6528

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/listview/example-multiselect.html
- Select an item
- It should be `Record(s) Selected) shown`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-02-21 15:44 UTC, deep7102 approved these changes

2023-02-21 15:47 UTC, tmcconechy commented on src/components/locale/cultures/en-US.js
> +    RecordsSelected: { id: 'RecordsSelected', value: 'Record(s) Selected', comment: 'text describing a selected objects' },
```suggestion
    RecordsSelected: { id: 'RecordsSelected', value: 'Record(s) Selected', comment: 'Text the number of items selected in a list component' },
```

2023-02-21 16:06 UTC, tmcconechy requested changes
@tjamesallen15 see this comment
https://github.com/infor-design/enterprise/issues/6528#issuecomment-1438727974
We will need to check the count and show the correct label based on the count.

2023-02-22 02:46 UTC, tjamesallen15 commented
> @tjamesallen15 see this comment [#6528 (comment)](https://github.com/infor-design/enterprise/issues/6528#issuecomment-1438727974) We will need to check the count and show the correct label based on the count.

copy!

2023-02-22 11:27 UTC, ericangeles submitted a review, later dismissed

2023-02-22 18:59 UTC, tmcconechy requested changes
@tjamesallen15 i think we need to use 3 strings exactly as follows:

`0 Records Selected` -> (In English, "0 Records" is plural but in most languages, 0 is singular)
`1 Record Selected`
`{0} Records Selected` -> more than one

We can't just reuse the same one because in some languages 0, 1 or multiple "things" are translated different. So expect the logic to have three things and use the right one if its 0, 1, or more.

2023-02-23 14:44 UTC, tmcconechy approved these changes

2023-02-23 14:58 UTC, ericangeles approved these changes

2023-02-23 14:58 UTC, merged