7149 - Icon adjustments in compact mode
infor-design/enterprise pull request #7248
Opened 2023-02-21 09:40 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Spinbox: I can't find the border issue in local. The issue might have been fixed or I'm missing something
Fileupload: The icon alignment looked okay though I changed the size of the X icon since it looked bigger than the file icon

**Related github/jira issue (required)**:

Closes #7149 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/form/example-compact-mode.html
- Check spinbox
- Upload a file with a long name and check icon alignment

**Included in this Pull Request**:
- [ ] A note to the change log.

2023-02-21 15:37 UTC, deep7102 submitted a review, later dismissed

2023-02-21 15:52 UTC, tmcconechy requested changes
I see some of the trigger icons are not centered vertically...like the date and time and lookup. Could maybe use an adjustment:

<img width="359" alt="image" src="https://user-images.githubusercontent.com/814283/220394111-e9e81175-b9df-4fcd-ba3e-20db9fe9863f.png">

2023-02-22 16:51 UTC, andriivarhanov commented on src/components/lookup/_lookup-new.scss
> +      margin-top: 6px;
it seems like the icons are closer to the bottom of the field now, maybe let's try 5px, here and for the similar icons

2023-02-22 16:53 UTC, andriivarhanov commented on src/components/lookup/_lookup-new.scss
> +      margin-top: 6px;
it seems like the icons are closer to the bottom of the field now, maybe let's try 5px, here and for the similar icons

2023-02-22 19:02 UTC, tmcconechy commented
@yohannahbautista while we are getting this right some small things i would be willing to skip if needed

1) the hover state isnt centered (could be a little bigger if needed)
<img width="61" alt="image" src="https://user-images.githubusercontent.com/814283/220732196-6330b119-db88-4d2d-9fd5-eec77dd7cf5d.png">
2) the file upload one has no hover state

2023-02-23 14:44 UTC, tmcconechy approved these changes

2023-02-23 15:19 UTC, andriivarhanov approved these changes

2023-02-23 15:20 UTC, merged