7264 - Icon adjustments in Safari
infor-design/enterprise pull request #7288
Opened 2023-03-03 09:32 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Icon adjustments in Safari

**Related github/jira issue (required)**:

Closes #7264 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to Safari
- Go to: http://localhost:4000/components/field-filter/example-short.html
- Hover on icons
- Icons and hover should be aligned

**Included in this Pull Request**:
- [ ] A note to the change log.

2023-03-03 14:58 UTC, tmcconechy requested changes
I notice if you click open the dropdown the dropdown icon moves...
![Screenshot 2023-03-03 at 9 57 47 AM](https://user-images.githubusercontent.com/814283/222752995-9b60cf1e-a86c-4f2f-a50b-93d2f384d775.png)

2023-03-06 13:47 UTC, ericangeles submitted a review, later dismissed

2023-03-06 14:22 UTC, tmcconechy reviewed
@yohannahbautista still see a slight shift of the icon and the top border looks 1px misaligned. Can it be improved a bit more?

2023-03-07 14:52 UTC, tmcconechy approved these changes

2023-03-08 05:56 UTC, tjamesallen15 approved these changes

2023-03-08 06:11 UTC, ericangeles approved these changes

2023-03-08 06:12 UTC, merged