7234 - Updated example page and styles
infor-design/enterprise pull request #7357
Opened 2023-03-24 07:02 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Updated example page and styles for instance count.

**Related github/jira issue (required)**:

Closes #7234 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/counts/example-hero.html
- Alert icons should have matching background with hero widget background

**Included in this Pull Request**:
- [ ] A note to the change log.

2023-03-24 13:45 UTC, tmcconechy requested changes
Looks good but maybe we should make the hero have a dynamic height. Lets do it with 32px padding on top and bottom and center the counts. Probably need to remove it from the card since the card has a fixed height.

Basically the hero is too big for the content and the content is not centered, something like:

<img width="1095" alt="Screenshot 2023-03-24 at 9 44 56 AM" src="https://user-images.githubusercontent.com/814283/227537898-af43de89-5961-40ab-b026-b0738561d85a.png">

Also watch if the scrollbar is in the wrong place after the change..

<img width="617" alt="Screenshot 2023-03-24 at 9 42 47 AM" src="https://user-images.githubusercontent.com/814283/227537976-3ac020ca-0e2e-43d3-bc63-cf55b91e951b.png">

2023-03-27 14:00 UTC, EdwardCoyle commented on app/views/components/counts/example-hero.html
> +        <div class="card count-container auto-height">
Maybe move the styles from the `<style>` tag here, and move them to an entry under `.card.auto-height` somewhere in here: https://github.com/infor-design/enterprise/blob/main/src/components/homepage/_homepage.scss#L318

2023-03-27 14:03 UTC, EdwardCoyle commented on app/views/components/counts/example-hero.html
> +    height: fit-content !important;
We should try to avoid using `!important` as much as possible, and rely on stronger CSS selectors for override behavior:

```scss
.hero-widget {
  .card.auto-height {
    height: fit-content;
    min-height: 0;
    max-height: none;
  }
}
```

2023-03-27 14:49 UTC, tmcconechy commented
@yohannahbautista to be clearer. Lets make sure:

- https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html still works
- but  for http://localhost:4000/components/counts/example-hero.html it should just be the height of the content. so maybe add a class to control "autoheight".
- the hero should never need a scroll bar In it the scrolling is at the layer above it

2023-03-28 14:39 UTC, tmcconechy submitted a review, later dismissed
Approving for now but noting that on http://localhost:4000/components/counts/example-hero.html?colors=ffffff the colors are not showing the status.

We might want to address that or need design feedback...

2023-03-29 14:39 UTC, tmcconechy submitted a review, later dismissed

2023-03-31 13:41 UTC, tmcconechy commented
<img width="874" alt="Screenshot 2023-03-31 at 9 40 34 AM" src="https://user-images.githubusercontent.com/814283/229135946-68dbc77c-c932-403c-92b8-60e5a75d4e75.png">

this looks pretty good but i think we need design here (not your fault). also the circles are not 100% centered.

@talkaboutdesign what do you think about this pattern?

2023-03-31 16:18 UTC, talkaboutdesign commented
This pattern need a lot of work in the future. The status indicators are def problematic. Nothing we need to worry about immediately. We can revisit in the future. 

Few notes on banned area: 
- It's always a fixed size 
- Content is always in a widget

<img width="1418" alt="CleanShot 2023-03-31 at 12 18 24@2x" src="https://user-images.githubusercontent.com/2926534/229175228-d08290cb-d67e-4bd7-814d-df1477a32055.png">
<img width="1427" alt="CleanShot 2023-03-31 at 12 18 16@2x" src="https://user-images.githubusercontent.com/2926534/229175240-691b2d53-3d88-4375-a693-49dac60cca3d.png">

2023-03-31 17:30 UTC, tmcconechy commented
ok @yohannahbautista based on design feedback

1) leave the colors as is
2) for this example lets keep the size fixed and put those counts in a border less card and put it in the center of the hero widget like:

https://user-images.githubusercontent.com/2926534/229175240-691b2d53-3d88-4375-a693-49dac60cca3d.png

So it looks like the actual use case. So centered in a borderless widget with a title like "Counts" and then somewhat resembling that. 

We can come back on the colors. My mistake on the dynamic size part. Sorry and thanks for the clarification @talkaboutdesign

2023-03-31 17:52 UTC, talkaboutdesign commented
@tmcconechy maybe would be helpful to get you guys an environment from Portal 2 where you can see the banner area in action so you can match it. What do you think?

2023-03-31 17:54 UTC, tmcconechy commented
Not a bad idea although we wont implement everything. Maybe for now just tell us if our size differs here https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html

Its probably separate from this exact issue

2023-03-31 18:32 UTC, talkaboutdesign commented
Banner Height: 390px (they set this as a min-height) but it's never more than that because it can only have a widget)
Margin bottom: 20px (between banner and widgets on page)
Inside banner area you have a widget thats vertically center aligned with a height of 360px (borderless)
(data vis is inside this widget)

@tmcconechy Please note that some of these values we want updated to reflect our widget card enhancements. What I am giving you here is what is currently in Ming.le Homepages. 

<img width="1145" alt="CleanShot 2023-03-31 at 14 30 32@2x" src="https://user-images.githubusercontent.com/2926534/229201512-c54f9daa-9103-4993-a987-413a58eacfb2.png">

2023-03-31 18:35 UTC, tmcconechy commented
Ok, could you make a new issue @talkaboutdesign with the "new" ones you want. I think its a seperate task.

2023-03-31 18:53 UTC, talkaboutdesign commented
Added this to the card enhancement ticket here: https://github.com/infor-design/enterprise/issues/7379

2023-04-03 13:45 UTC, tmcconechy approved these changes

2023-04-04 14:22 UTC, tmcconechy commented
@EdwardCoyle does this look ok for you now?

2023-04-05 14:06 UTC, tmcconechy submitted a review, later dismissed

2023-04-05 14:28 UTC, jbrcna requested changes
this is failing in Firefox. also button and caret hover colors are off and the page blinks when you switch/open with classic view using safari browser

2023-04-05 14:38 UTC, ericangeles commented
@jbrcna can you screenshot the issue? That would be helpful. Thanks!

2023-04-12 16:06 UTC, tmcconechy commented
@yohannahbautista @ericangeles if you just try http://localhost:4000/components/counts/example-hero.html in firefox at different sizes you can see

1. its not centered
2. scroll bars or its bleeding over the circle
3. also if you hover the view button i see what @jbrcna is saying

Alternative is we could show maybe 4 counts for the example as a lot of this is related to it not fitting.
Then fix the centering and the hover.

2023-04-13 15:35 UTC, tmcconechy submitted a review, later dismissed
Ok looks good enough for me for now. Thanks @yohannahbautista 
cc @jbrcna what do you think?

2023-04-13 16:19 UTC, jbrcna commented
widget is now aligned in Firefox. However, the button color is still off
`Light & High Contrast`  using Default color
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/56722184/231820592-5e17a797-5315-4b39-9346-4c9253cedb30.png">

`Dark`  using Alabaster color
title 'Counts Hero Widget Example' is also not readable
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/56722184/231821327-49eb3e3b-8142-4a49-a48c-f87f3c7d6bfc.png">

2023-04-14 14:25 UTC, tmcconechy approved these changes
@jbrcna can you have another look. This doesnt have to be perfect as we will come back to it after design feedback (its an odd pattern)

2023-04-17 01:49 UTC, jbrcna submitted a review, later dismissed
[example-hero.html?theme=new&mode=contrast&colors=ffffff](http://localhost:4000/components/counts/example-hero.html?theme=new&mode=contrast&colors=ffffff) - paging buttons is not visible
<img width="1628" alt="image" src="https://user-images.githubusercontent.com/56722184/232276658-2abc13c7-a7d5-4de8-95ed-89f0578e8b3b.png">


[example-hero.html?colors=ffffff&theme=classic&mode=dark](http://localhost:4000/components/counts/example-hero.html?colors=ffffff&theme=classic&mode=dark)
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/56722184/232325864-0e5fa0ed-59e9-421b-9ef6-1de7eb6a6a19.png">

2023-04-18 13:55 UTC, tmcconechy approved these changes

2023-04-19 17:26 UTC, tmcconechy approved these changes
looks good to me. what do you think @jbrcna ?

2023-04-20 14:35 UTC, merged