7130 - tooltip header placements
infor-design/enterprise pull request #7381
Opened 2023-03-29 23:54 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request fix tooltip not on top of all elements when shown and manually moved.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7130

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/dropdown/example-tooltips.html?colors=0066D4
- Open `Developer Console`
- Click an item in the dropdown
- Hover the dropdown component
- See the tooltip appended to the body

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-03-30 05:36 UTC, yohannahbautista requested changes

2023-03-30 05:36 UTC, yohannahbautista commented on src/components/tooltip/tooltip.js
> +    // return;
Remove comment

2023-03-30 05:43 UTC, yohannahbautista approved these changes

2023-03-31 14:04 UTC, tmcconechy approved these changes

2023-03-31 15:56 UTC, merged