7387 - Searchfield icon adjustments
infor-design/enterprise pull request #7392
Opened 2023-03-31 06:42 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjustments for searchfield for icons and color

**Related github/jira issue (required)**:

Closes #7387 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Check clear icon on the following:
   - http://localhost:4000/components/header/example-searchfield-full.html
   - http://localhost:4000/components/header/example-toolbar-flex-with-categories.html
   - http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html

**Included in this Pull Request**:
- [ ] A note to the change log.

2023-03-31 14:38 UTC, tmcconechy approved these changes

2023-04-03 14:11 UTC, tmcconechy requested changes
See a couple issues.

1) on http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html when expanded the search icon is missing

<img width="275" alt="Screenshot 2023-04-03 at 10 09 43 AM" src="https://user-images.githubusercontent.com/814283/229534854-debd2936-18b0-4039-835e-f8d28b2d4f00.png">

2) on http://localhost:4000/components/header/example-searchfield-full.html the x is far away from the right side
<img width="1288" alt="Screenshot 2023-04-03 at 10 10 18 AM" src="https://user-images.githubusercontent.com/814283/229535083-ce254779-a3a6-43fc-9b6f-337040f018e6.png">

3) on http://localhost:4000/components/header/example-toolbar-flex-with-categories.html the search icon is also missing and when you hover it it looks strange

<img width="266" alt="Screenshot 2023-04-03 at 10 10 52 AM" src="https://user-images.githubusercontent.com/814283/229535214-a1173069-fda4-4da1-b007-40892a70a7a8.png">

2023-04-03 14:25 UTC, deep7102 commented
Saw another addition to Tim's found. Search text gets cleared when click again to re-open search
http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html

https://user-images.githubusercontent.com/38439203/229538814-df21c4de-cb71-44d9-9286-1e3078aae2e3.mov

2023-04-04 14:28 UTC, tmcconechy approved these changes

2023-04-05 11:12 UTC, ericangeles approved these changes

2023-04-05 13:54 UTC, tmcconechy approved these changes

2023-04-05 13:54 UTC, merged