7377/7360 - Add CSS utility classes and fix centering of contents in emptymessage
infor-design/enterprise pull request #7415
Opened 2023-04-11 16:01 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR introduces a set of CSS utility classes to the library and enhances the centering of empty messages.

**Related github/jira issue (required)**:

Closes
#7377 
#7360 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app

1.) #7360 Empty Message Fix
- Go to http://localhost:4000/components/emptymessage/test-centered-content.html
- Check all the empty messages
- It should be centered on different sizes

2.) #7377 CSS Utilities
- Go to http://localhost:4000/components/utilities/example-index.html
- Check and test all CSS utility classes
- Check the documentation readme.md
- Check the _utilities.scss implementation (Open for more suggestions)

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2023-04-12 16:13 UTC, tmcconechy approved these changes
Looks good. Maybe we can call it css-utilities to be more specific.
Thats my only suggestion. This came out looking good.

Opening this for QA

2023-04-14 14:26 UTC, tmcconechy approved these changes
@jbrcna @CindyMercadoReyes can you have a quick look

2023-04-17 01:51 UTC, jbrcna commented
I already approved this request @tmcconechy . I also noted an observation that .p-left should be 80 instead of 50. Nevertheless, nothing seems to be majorly off.

2023-04-17 14:16 UTC, tmcconechy requested changes
@ericangeles i tried to fix the example page but didnt have enough time. can you check http://localhost:4000/components/utilities/example-index.html now that its all 4s the example isnt quite correct.

Also merging main will fix the lint error

2023-04-17 14:18 UTC, tmcconechy commented on docs/CHANGELOG.md
> +## v.4.83.0
```suggestion
## v4.83.0
```

2023-04-17 14:18 UTC, ericangeles commented
What's the issue then? I didn't quite understand it.

2023-04-17 15:10 UTC, tmcconechy commented
@ericangeles look at the padding example on http://localhost:4000/components/css-utilities/example-index.html
It has a whole bunch of classes that arent in 4.s that done work. i.e. you updated to use 4s but the example doesnt work now.

2023-04-18 06:53 UTC, jbrcna approved these changes

2023-04-18 13:32 UTC, glenlieorillo reviewed
QA Passed for [4770](https://github.com/infor-design/enterprise/issues/7440)

![image](https://user-images.githubusercontent.com/102151352/232793020-329f9d31-db73-42b4-89a6-35ec2fadd06b.png)

2023-04-18 13:45 UTC, tmcconechy approved these changes

2023-04-18 13:46 UTC, merged