5061. Fix on popupmenu arrow not appearing when showArrow is true
infor-design/enterprise pull request #7417
Opened 2023-04-12 03:35 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fix on popupmenu arrow not appearing when showArrow is true

**Related github/jira issue (required)**:

Closes #5061 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/popupmenu/example-icons.html
- Click on star
- Popupmenu should have arrow

**Included in this Pull Request**:
- [ ] A note to the change log.

2023-04-12 11:26 UTC, ericangeles submitted a review, later dismissed

2023-04-12 11:26 UTC, ericangeles commented on docs/CHANGELOG.md
> +- `[Popupmenu]` Fix on popupmenu arrow not appearing when showArrow is true. ([#5061](https://github.com/infor-design/enterprise/issues/5061))
Move this to 4.83.0

2023-04-12 16:29 UTC, tmcconechy requested changes
Looks like it works fine. But can i suggest a new example called "show-arrow".
That shows two buttons, one showing the arrow and one not?

2023-04-13 15:48 UTC, tmcconechy submitted a review, later dismissed

2023-04-14 05:20 UTC, ericangeles approved these changes

2023-04-14 09:34 UTC, jbrcna approved these changes
<img width="270" alt="image" src="https://user-images.githubusercontent.com/56722184/231941419-d5a82936-7845-44d4-876a-19fbbded0601.png">
<img width="251" alt="image" src="https://user-images.githubusercontent.com/56722184/231941440-bee73bf0-8cb8-4b97-bcf6-7ec43676c5de.png">

2023-04-14 14:04 UTC, tmcconechy approved these changes

2023-04-14 14:05 UTC, merged