7428 - Fix on showColumn not working properly with frozen columns
infor-design/enterprise pull request #7531
Opened 2023-05-23 08:23 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

showColumn was inserting another column in the datagrid for the given column, under the assumption that it's a hidden checkbox column. Added an additional check when assigning headerNodeCheckbox so that the Activity header in the example won't be inserted on the first column.

**Related github/jira issue (required)**:

Closes #7428 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/example-frozen-columns.html
- Click on Personalize Columns
- Deselect and select Activity so that the column will disappear and appear
- Columns should render correctly (Activity should not be pushed on the first column and values should be correct)

**Included in this Pull Request**:
- [ ] A note to the change log.

2023-05-23 09:54 UTC, ericangeles commented on docs/CHANGELOG.md
> +- `[Datagrid]` Fix on `showColumn` not working properly with frozen columns. ([#7428](https://github.com/infor-design/enterprise/issues/7428))
Fixed an issue where `showColumn` was not functioning correctly with frozen columns.

2023-05-23 14:05 UTC, tmcconechy submitted a review, later dismissed

2023-05-24 05:26 UTC, glenlieorillo requested changes
Bug already fixed. However, if you deselect the 'Activity' column the border between 'Product Name' and 'Quantity' is missing.


https://github.com/infor-design/enterprise/assets/102151352/1847a84c-44e7-4b2b-9955-e9cf03ceec4e

![image](https://github.com/infor-design/enterprise/assets/102151352/03ec3e0c-f433-480a-91aa-f8619edc887b)

2023-05-24 13:50 UTC, tmcconechy commented
@yohannahbautista can you take a look at that point by @glenlieorillo

2023-05-25 09:45 UTC, ericangeles approved these changes

2023-05-25 10:30 UTC, glenlieorillo submitted a review, later dismissed
QA Approved.


https://github.com/infor-design/enterprise/assets/102151352/b8fa3063-b99b-42d1-81bc-84de668f60ed

For Clarification:
@tmcconechy 
Upon deselecting all columns, there is a big gap between 'Product Name' and 'Button' columns. Kindly confirm if this is the correct behavior. Thanks.

![image](https://github.com/infor-design/enterprise/assets/102151352/41ce98d4-ae3f-471e-9b0b-6603b53c186a)

2023-05-25 12:10 UTC, jbrcna submitted a review, later dismissed

2023-05-25 13:16 UTC, tmcconechy commented
@glenlieorillo its probably "ok" as its an edge case and the column widths are fixed and that is the size. So unsure what else can be done. At least for future consideration

2023-05-25 13:16 UTC, merged

2023-05-25 13:33 UTC, glenlieorillo commented
> @glenlieorillo its probably "ok" as its an edge case and the column widths are fixed and that is the size. So unsure what else can be done. At least for future consideration

Thanks, @tmcconechy.