6956 - Adjusted the table's width to fill the container of the datagrid, ensuring proper alignment
infor-design/enterprise pull request #7533
Opened 2023-05-23 11:37 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the table's width to fill the container of the datagrid in firefox.

**Related github/jira issue (required)**:

Closes #6956

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Open the test page in `firefox` http://localhost:4000/components/modal/test-modal-datagrid-title-overlap.html
- Click on `Open Modal` button
- Table should filled the container of the datagrid (no whitespaces)

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2023-05-23 14:06 UTC, tmcconechy commented on src/components/datagrid/_datagrid.scss
> +    min-width: -moz-available;
This work on chrome?

2023-05-24 17:15 UTC, tmcconechy submitted a review, later dismissed

2023-05-24 17:37 UTC, deep7102 submitted a review, later dismissed

2023-05-24 18:06 UTC, janahintal requested changes
Also experiencing the unnecessary scroll bar in Chrome and FF. 
![image](https://github.com/infor-design/enterprise/assets/45757016/45187743-f491-4cce-969d-9990095d9423)

2023-05-25 11:03 UTC, ericangeles commented
I have tested it on both Chrome and Firefox in Windows, and I can confirm that both issues have been resolved. It is possible that you do not have the latest version of the code @janahintal.

2023-05-25 12:20 UTC, jbrcna reviewed
the table overflows in responsive view and landscape mobile
adjust the height to below 630 or switch to landscape mobile view
<img width="290" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/1627c5f2-d87c-436d-9bf0-8b2cd5fdb55a">

2023-05-26 15:31 UTC, s-werking commented
I am also encountering the overflow issue that @jbrcna is seeing. Otherwise I no longer see the issue, thanks!

2023-05-30 20:34 UTC, tmcconechy commented
@ericangeles can you check the last couple things. Would like to patch these

2023-05-31 16:58 UTC, tmcconechy approved these changes

2023-05-31 16:58 UTC, tmcconechy commented
look good now @janahintal ?

2023-06-01 14:38 UTC, tmcconechy commented
@s-werking this look ok enough for you folks?

2023-06-01 16:31 UTC, s-werking commented
Looks good to me, thanks!

2023-06-01 17:13 UTC, merged