7007 - Images with Click Handler
infor-design/enterprise pull request #7563
Opened 2023-05-31 09:57 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add class for images cursor pointer and make an example with click handler.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7007

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/images/test-image-click.html
- Click the image, cursor should be pointer
- Go to http://localhost:4000/components/datagrid/test-form-images-actionable.html
- Click the image on the side, cursor should be pointer and have click handler
- Alert message should be shown

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-05-31 16:18 UTC, tmcconechy requested changes
@tjamesallen15 there was another aspect of it in that this was for the image formatter

https://main-enterprise.demo.design.infor.com/components/datagrid/test-images.html

So they wanted the click events there (what you added is probably needed too) but should make the click work on there same as how https://main-enterprise.demo.design.infor.com/components/datagrid/test-form-buttons.html works.

For image formatter we could add the cursor class if a click event is added to the column so its automatic

2023-06-01 14:46 UTC, tmcconechy approved these changes

2023-06-02 07:48 UTC, ericangeles commented
FYI @infor-design/qa

2023-06-02 09:41 UTC, jbrcna approved these changes

2023-06-02 10:42 UTC, glenlieorillo approved these changes
QA Approved.


https://github.com/infor-design/enterprise/assets/102151352/eeceab52-b01c-4ca1-bff0-6ff52dfd0c05

2023-06-02 14:06 UTC, merged