7205 - lookup width constraint
infor-design/enterprise pull request #7592
Opened 2023-06-13 03:06 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix a bug in lookup width not responsive in grid system.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7205

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/lookup/test-lookup-overflow.html
- Resize the window

For Older Issue: https://github.com/infor-design/enterprise/issues/6924
- Go to http://localhost:4000/components/lookup/example-clearable.html
- Open Lookup
- Select a single item
- Field should not change size
- Open Lookup
- Select a multiple item
- Field should not change size

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-06-13 14:01 UTC, EdwardCoyle submitted a review, later dismissed

2023-06-13 16:09 UTC, tmcconechy submitted a review, later dismissed

2023-06-14 04:18 UTC, ericangeles submitted a review, later dismissed

2023-06-14 09:49 UTC, jbrcna approved these changes

2023-06-14 11:30 UTC, glenlieorillo requested changes
lookup and close button not properly aligned in Classic Version.

![image](https://github.com/infor-design/enterprise/assets/102151352/42fda91f-a922-441e-af52-78faa6c19f99)

2023-06-15 14:02 UTC, tmcconechy approved these changes
@glenlieorillo i adjusted the classic icon a bit safely. Merging due to prior approvals

2023-06-15 14:02 UTC, merged

2023-06-16 11:34 UTC, glenlieorillo reviewed
QA Approved.

![image](https://github.com/infor-design/enterprise/assets/102151352/3e491a5f-1dc5-424c-a3aa-482ee13ecf10)