7383 - Updated popupmenu color styles
infor-design/enterprise pull request #7670
Opened 2023-07-05 03:10 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Add color style for toolbar flex popupmenu button

**Related github/jira issue (required)**:

Closes #7383 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/contextualactionpanel/test-complex-toolbar-flex.html
- Open Contextual Action Panel
- Open Filter popup menu
- Filter button color should be visible when open
- Check other versions and modes

**Included in this Pull Request**:
- [ ] A note to the change log.

2023-07-06 16:18 UTC, EdwardCoyle commented on src/components/toolbar-flex/_toolbar-flex.scss
> +      &.btn-menu.is-open {
This looks good and works fine, but my only comment is that I think these rules don't belong in the base toolbar code.  There is another set of Toolbar style rules that live in the Contextual Action Panel code that drive these styles, and should probably land there: https://github.com/infor-design/enterprise/blob/main/src/components/contextualactionpanel/_contextualactionpanel.scss#L151

Otherwise this looks good 👍

2023-07-07 17:09 UTC, tmcconechy approved these changes

2023-07-10 11:30 UTC, glenlieorillo requested changes
Fix already applied. However, filter button is cut-off in mobile view.

![image](https://github.com/infor-design/enterprise/assets/102151352/947f83fe-d7f6-42c4-b831-b92ab27d63e9)

2023-07-10 13:38 UTC, jbrcna approved these changes

2023-07-10 13:41 UTC, tmcconechy commented
I think some of the icons may be cut off depending on the size of the screen. Not a ton we can do about that. So will skip that point

2023-07-10 13:41 UTC, merged