7333 - alabaster cleanup
infor-design/enterprise pull request #7674
Opened 2023-07-06 03:39 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix a alabaster design issues in headers, tabs, tab-headers, tabs-module, tabs-multi components.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7333

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to the following links below
- Module tabs -> https://localhost:4000/components/tabs-module/example-index.html
- Header -> https://localhost:4000/components/header/example-index.html
- Multi Tabs -> https://localhost:4000/components/tabs-multi/example-index.html
- Header Tabs -> https://localhost:4000/components/tabs-header/example-index.html
- Vertical Tabs -> https://localhost:4000/components/tabs-vertical/example-index.html

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-07-06 08:05 UTC, tjamesallen15 commented
Still not yet finish.

2023-07-06 08:25 UTC, ericangeles commented on src/components/personalize/personalize.styles.js
> +  border-top: 1px solid ${colors.tabBorderColor} !important;
Lets try to minimize or find a way to not use !important @tjamesallen15

2023-07-06 19:07 UTC, talkaboutdesign commented
When this is close to finish please tag me for review.

2023-07-07 17:27 UTC, tmcconechy commented
@tjamesallen15 looks good just minor details. Maybe its ready to review by @talkaboutdesign ? Let us know. For what i see its partly design related

1. http://localhost:4000/components/header/example-index.html?theme=new&mode=dark&colors=ffffff -> the bottom border seems wierd but it is in the design
2. on http://localhost:4000/components/tabs-multi/example-index.html?colors=ffffff the hover state seems very dark
<img width="196" alt="Screenshot 2023-07-07 at 1 23 21 PM" src="https://github.com/infor-design/enterprise/assets/814283/f7f22e82-d158-47a6-897f-cae38ca13ce6">
3. on http://localhost:4000/components/tabs-vertical/example-index.html?theme=new&mode=dark&colors=ffffff and in light mode if you click a tab item and use arrow up/down you can only barely see the focus state 
<img width="319" alt="Screenshot 2023-07-07 at 1 27 20 PM" src="https://github.com/infor-design/enterprise/assets/814283/fe5e5c63-dc7b-4005-8224-d1fba7a8d139">

2023-07-07 18:34 UTC, talkaboutdesign commented
@tmcconechy i'm going to pull this and check?

2023-07-07 18:35 UTC, tmcconechy commented
@talkaboutdesign i think it cant hurt to check it. seems pretty done to me.

2023-07-07 18:49 UTC, talkaboutdesign commented
> @talkaboutdesign i think it cant hurt to check it. seems pretty done to me.

Ok will do.

2023-07-11 00:32 UTC, tjamesallen15 commented
> @tjamesallen15 looks good just minor details. Maybe its ready to review by @talkaboutdesign ? Let us know by taking WIP off.
> 
> 1. http://localhost:4000/components/header/example-index.html?theme=new&mode=dark&colors=ffffff -> the bottom border seems wierd but it is in the design
> 2. on http://localhost:4000/components/tabs-multi/example-index.html?colors=ffffff the hover state seems very dark
> 
> <img alt="Screenshot 2023-07-07 at 1 23 21 PM" width="196" src="https://user-images.githubusercontent.com/814283/251812527-f7f22e82-d158-47a6-897f-cae38ca13ce6.png"> 3. on http://localhost:4000/components/tabs-vertical/example-index.html?theme=new&mode=dark&colors=ffffff and in light mode if you click a tab item and use arrow up/down you can only barely see the focus state <img alt="Screenshot 2023-07-07 at 1 27 20 PM" width="319" src="https://user-images.githubusercontent.com/814283/251812931-fe5e5c63-dc7b-4005-8224-d1fba7a8d139.png">

Yep. The No. 1 is also weird to me, i can tone it down see if it will be a passed on review.

2023-07-11 01:51 UTC, talkaboutdesign commented
@tmcconechy @tjamesallen15 will start reviewing. I know we just changed slate colors so this will take a little longer to check. 

One thing I noticed so far is that in the example the header buttons are somewhat misaligned. 

See this screenshot: 
![CleanShot 2023-07-10 at 21 49 52@2x](https://github.com/infor-design/enterprise/assets/2926534/7745c4ea-b934-4651-98b2-f0b411ac6fea)

I also noticed that some of the color values for colors don't match designs. I'll post all the instances where there is a discrepancy.

2023-07-11 18:36 UTC, tmcconechy commented
opening this up to both QA and design review

2023-07-13 10:29 UTC, janahintal requested changes
Failing in https://7333-alabaster-cleanup-enterprise.demo.design.infor.com/components/header/example-index.html?theme=classic&mode=dark&colors=ffffff
![image](https://github.com/infor-design/enterprise/assets/45757016/2a900e4b-5722-416c-b372-fccd3aabca6f)

https://7333-alabaster-cleanup-enterprise.demo.design.infor.com/components/tabs-multi/example-index.html?theme=classic&mode=dark&colors=ffffff
![image](https://github.com/infor-design/enterprise/assets/45757016/62dad86b-ed26-4bea-a3e3-487c3cb35f95)

https://7333-alabaster-cleanup-enterprise.demo.design.infor.com/components/tabs-header/example-index.html?theme=classic&mode=dark&colors=ffffff
![image](https://github.com/infor-design/enterprise/assets/45757016/548ebf29-345e-4095-b888-6b95ab037b86)

https://7333-alabaster-cleanup-enterprise.demo.design.infor.com/components/tabs-vertical/example-index.html?theme=classic&mode=dark&colors=ffffff
![image](https://github.com/infor-design/enterprise/assets/45757016/5763275d-333c-419a-806d-a9c9588f22b4)




Also noticed that the search text is not being previewed in New but it does in Classic. 
New 
![image](https://github.com/infor-design/enterprise/assets/45757016/5abadcba-5c09-4c85-a035-5ce97abca38b)

Classic 
![image](https://github.com/infor-design/enterprise/assets/45757016/846882e8-cdda-45ad-a76c-dcb58b4207fa)

2023-07-17 13:18 UTC, tmcconechy commented
@tjamesallen15 have a look at the design QA for this issue https://jira.infor.com/browse/IDS-1415 and check for the improvements you can make. For the hover state on the X icon just make it change color...

2023-07-18 08:42 UTC, tjamesallen15 commented
> @tjamesallen15 have a look at the design QA for this issue https://jira.infor.com/browse/IDS-1415 and check for the improvements you can make. For the hover state on the X icon just make it change color...

I saw comments on the classic ones but no figma design was updated for that. I just fixed the classic alabaster for now. You can cross check what I've done.

I also fix the hover. Any suggestions or it is now okay?

2023-07-18 15:32 UTC, tmcconechy commented
Some additional edge cases https://www.figma.com/file/gRpli2TgQ3scLE6GF4e2Hz/Alabaster-Clean-up?type=design&node-id=527-33769&mode=design&t=4XOwO7lK9t9fMPAN-0

2023-07-18 16:13 UTC, tmcconechy commented
@tjamesallen15 can you check https://www.figma.com/file/gRpli2TgQ3scLE6GF4e2Hz/Alabaster-Clean-up?type=design&node-id=527-33769&mode=design&t=4XOwO7lK9t9fMPAN-0

Also does not appear all of this QA is done:
https://www.figma.com/file/gRpli2TgQ3scLE6GF4e2Hz/Alabaster-Clean-up?type=design&node-id=453-31611&mode=design&t=a6iogiMwVJVZFBSN-0

module nav - hide close button, tab height ect, unselected label

Did not check them all but none seemed fixed in the first section. Can you  take a look at both and not any you didnt fix?

2023-07-21 09:28 UTC, jbrcna commented
https://7333-alabaster-cleanup-enterprise.demo.design.infor.com/components/tabs-module/example-index.html?theme=classic&mode=dark&colors=ffffff
button text not visible. When you hover the button the text is displayed.
<img width="1302" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/f2f9db5c-c335-4f50-bc69-49c0a4110d1d">



https://7333-alabaster-cleanup-enterprise.demo.design.infor.com/components/tabs-multi/example-index.html?theme=new&mode=dark&colors=ffffff
separator not clearly visible
![image](https://github.com/infor-design/enterprise/assets/56722184/9b6f64c9-52d9-4fdb-ace1-bf8e53fbfded)


https://7333-alabaster-cleanup-enterprise.demo.design.infor.com/components/tabs-header/example-index.html?theme=new&mode=dark&colors=ffffff
focus state has different edges (unselected w/ hover) 
<img width="1676" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/276f95c5-c43c-4c02-b0c0-881b68338ccc">

https://7333-alabaster-cleanup-enterprise.demo.design.infor.com/components/tabs-vertical/example-index.html?theme=new&mode=contrast&colors=ffffff
hyperlink line
<img width="980" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/682ef4d4-dbc6-4724-a797-27c689eba353">

2023-07-21 14:53 UTC, tmcconechy commented
@tjamesallen15 @jbrcna 

1. The button issue should be fixed - try pulling main on and see
2. Lets look at the edge on the tabs
3. Lets look at the seperator
4. The underline on the link in contrast mode is as designed. We should underline there

2023-07-24 14:45 UTC, EdwardCoyle approved these changes

2023-07-25 14:27 UTC, tmcconechy approved these changes
@tjamesallen15 do you have anymore fixes planned for this? I think its good enough for now.

2023-07-25 14:28 UTC, tjamesallen15 commented
> @tjamesallen15 do you have anymore fixes planned for this? I think its good enough for now.

None so far. Looks good to me now. Will probably do a quick PR if any request needed to change asap. :)

2023-07-25 14:47 UTC, merged

2023-08-09 14:43 UTC, talkaboutdesign commented
@tmcconechy this was not 100% done to design spec. 

![CleanShot 2023-08-09 at 10 43 07@2x](https://github.com/infor-design/enterprise/assets/2926534/f0895573-f9c1-4543-a930-8cf4966b15ca)

Specifically on selected elements. See above just one example between design and dev: 
![CleanShot 2023-08-09 at 10 43 26@2x](https://github.com/infor-design/enterprise/assets/2926534/f739b336-3a4b-4fc9-be34-d1409e57b8f7)

2023-08-14 15:24 UTC, tmcconechy commented
@talkaboutdesign can you make sure all the points you want addressed are added to 

https://www.figma.com/file/gRpli2TgQ3scLE6GF4e2Hz/Alabaster-Clean-up?type=design&node-id=855%3A35671&mode=design&t=Oh4kP3JmIvRkwftA-1 and we can make an other round

New Issue: https://github.com/infor-design/enterprise/issues/7803 for remaining items (lets take this there)
See Also https://jira.infor.com/browse/IDS-1415