7711 - Re fix for modal overflow issues
infor-design/enterprise pull request #7712
Opened 2023-07-13 20:18 UTC by tmcconechy

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Refixed the modal issues by adding back the css overflow. I remove the JS sizing part and added back the css. I tested all related issues and everything seems fixed.

Do check for any uses cases i might not know. @ericangeles @yohannahbautista 

**Related github/jira issue (required)**:
Fixes #7711 

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/modal/example-slider.html
- In dev tools select "surface duo" mobile emulator
- open Modal and content should scroll not break out
- test https://github.com/infor-design/enterprise/issues/7698
- test https://github.com/infor-design/enterprise/issues/7660
- test https://github.com/infor-design/enterprise/issues/6956 (For some reason can not long see it so thats good)

**Included in this Pull Request**:
- [x] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-07-14 05:26 UTC, ericangeles approved these changes

2023-07-14 20:15 UTC, EdwardCoyle approved these changes

2023-07-16 22:11 UTC, janahintal requested changes
Modal looks good in classic dark mode but the button looks off. 
https://7711-modal-overflow-enterprise.demo.design.infor.com/components/modal/example-slider.html?theme=classic&mode=dark&colors=default 
![image](https://github.com/infor-design/enterprise/assets/45757016/1538d4eb-34e1-4585-a282-30a84f579e80)

2023-07-17 11:03 UTC, jbrcna submitted a review, later dismissed

2023-07-17 11:05 UTC, jbrcna commented
> Modal looks good in classic dark mode but the button looks off. https://7711-modal-overflow-enterprise.demo.design.infor.com/components/modal/example-slider.html?theme=classic&mode=dark&colors=default ![image](https://user-images.githubusercontent.com/45757016/253829948-1538d4eb-34e1-4585-a282-30a84f579e80.png)

I encounter a similar issue in CAP. 
`classic theme dark mode`
<img width="444" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/47d7b073-9cb8-44a1-a202-c7230f78054e">

2023-07-17 13:53 UTC, tmcconechy commented
@janahintal fixed the button issue ~ even tho it was unrelated i just added to this fix

2023-07-17 19:29 UTC, merged