Allow defaultFilterOperator to be honored for date and time columns
infor-design/enterprise pull request #7767
Opened 2023-08-03 19:32 UTC by Sovia

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixes bug where defaultFilterOperator wasn't being honored for date and time columns.

**Related github/jira issue (required)**:
 "Closes #7766 "

**Steps necessary to review your pull request (required)**:
1. Pull and build the code
2. Navigate to /components/datagrid/test-filter-with-default-operator.html
3. See that the filter type for Ordered Date default to less than or equals

<img width="987" alt="image" src="https://github.com/infor-design/enterprise/assets/22107636/296d1c17-29fd-4dc4-9565-60bfe7870fdf">

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x ] A note to the change log.

2023-08-04 13:43 UTC, tmcconechy approved these changes

2023-08-07 05:25 UTC, janahintal requested changes
Unable to re-select a filter after using one. 
Video: https://app.screencast.com/jEQNMUbVyDNsF

2023-08-07 13:47 UTC, tmcconechy commented
@janahintal thats probably this issue https://github.com/infor-design/enterprise/issues/7750 which is slated to be fixed soon.

2023-08-08 06:11 UTC, ericangeles approved these changes

2023-08-10 04:52 UTC, ericangeles commented
@infor-design/qa please retest

2023-08-10 11:12 UTC, janahintal commented
Approving this as the other issue will be fixed on different ticket. 
Verified in https://7766-datagrid-default-date-filter-enterprise.demo.design.infor.com/components/datagrid/test-filter-with-default-operator.html

2023-08-10 11:12 UTC, janahintal approved these changes

2023-08-10 13:49 UTC, jbrcna approved these changes

2023-08-10 18:18 UTC, merged