7661 - Change badge size by design
infor-design/enterprise pull request #7841
Opened 2023-08-21 15:45 UTC by tmcconechy

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Based on design qa from https://github.com/infor-design/enterprise/pull/7817#issuecomment-1684626046 cc @talkaboutdesign

Made the status icon a feature with a seperate div. Made sure it was 24x24 and the icon is always 18x18

**Related github/jira issue (required)**:
Fixes #7661 

**Steps necessary to review your pull request (required)**:
-review http://localhost:4000/components/listview/example-card.html
- review http://localhost:4000/components/stats/example-index.html
- http://localhost:4000/components/icons/example-status-colors.html
- in all cases the circle is now 24x24 and the icon 18x18
- http://localhost:4000/components/tag/example-index.html  -> is now 24px height
- http://localhost:4000/components/badges/example-index.html -> is now 24px x 24px

**Included in this Pull Request**:
- [x] A note to the change log.

2023-08-22 08:39 UTC, glenlieorillo requested changes
Working as expected. However, the circle around icon is not visible in Dark Mode.

<img width="1220" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/66bcb82c-7ade-4a68-a1a8-c37900cad0c2">

<img width="1220" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/351e4d50-9602-4f69-9fae-335766f66e12">



http://localhost:4000/components/stats/example-index.html

<img width="1220" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/ce4d442a-bbed-4305-af23-401cd9d9a67b">

<img width="1220" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/148b3631-f957-40b3-b378-8222620be773">


http://localhost:4000/components/icons/example-status-colors.html

<img width="1220" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/23619dd7-bd0a-4010-9eb6-5e3920fcb6b8">


<img width="1220" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/819a366c-1441-4e11-bda1-3ac0f51b567e">

http://localhost:4000/components/listview/example-card.html

https://github.com/infor-design/enterprise/assets/102151352/8826b256-0e85-4219-803c-b535d560cebc

2023-08-22 12:14 UTC, tmcconechy commented
@glenlieorillo the problem is that color does'nt look right in dark mode. So for now we drop the outside color in dark.

2023-08-22 13:27 UTC, jbrcna approved these changes

2023-08-22 13:44 UTC, talkaboutdesign commented
No background in dark mode is needed. This is by design.

2023-08-22 18:36 UTC, talkaboutdesign commented
@tmcconechy assuming badges and tags will be updated separately. Need their height to be 24 as well. Currently they are 22.

2023-08-22 19:07 UTC, tmcconechy commented
@talkaboutdesign made that change as well. Sorry i missed that point https://github.com/infor-design/enterprise/pull/7841

2023-08-23 01:32 UTC, glenlieorillo approved these changes
**Tag**
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/2d963f00-3ea6-424a-ba6e-6c5b304d631f">

**Badges**
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/87de39ad-0b63-4c78-99c2-a10a49f2d790">

2023-08-23 06:22 UTC, jbrcna approved these changes
<img width="509" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/d7eb534f-94ff-4857-bf76-da9006000c6b">

<img width="502" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/3daad05e-bceb-4ae5-8c14-639b0091380f">

2023-08-23 10:24 UTC, ericangeles approved these changes

2023-08-23 10:25 UTC, merged