7680 - Added expanded default for expandable formatter
infor-design/enterprise pull request #7878
Opened 2023-08-31 04:12 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

A row will be expanded if there's an `expanded: true` in the dataset item.

**Related github/jira issue (required)**:

Closes #7680 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/example-expandable-row.html
- First row should be expanded

**Included in this Pull Request**:
- [ ] A note to the change log.

2023-08-31 09:29 UTC, ericangeles approved these changes

2023-08-31 10:47 UTC, glenlieorillo approved these changes
https://github.com/infor-design/enterprise/assets/102151352/cc806e1b-e7ca-4507-b2aa-03fcdabe8d14

2023-08-31 11:13 UTC, jbrcna approved these changes

2023-08-31 14:48 UTC, tmcconechy requested changes
This works great. But maybe we can use `rowExpanded` instead of `expanded` thats what i used in the web component version and that could make it easier if folks upgrade.

Also might make it more `unique`

2023-09-01 14:49 UTC, tmcconechy approved these changes
Decided this is fine for now since other apis use `expanded` they dont need to be the same

2023-09-01 14:49 UTC, merged