7832 - Adjusted position and hover color for custom button
infor-design/enterprise pull request #7895
Opened 2023-09-06 04:58 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjusted position and hover color for custom button

**Related github/jira issue (required)**:

Closes #7832 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/searchfield/example-buttons.html
- Hover on barcode, hover should not be so big
- Type in searchfield, hover on barcode, hoves should stay the same

**Included in this Pull Request**:
- [ ] A note to the change log.

2023-09-06 13:43 UTC, EdwardCoyle approved these changes
Feature looks great!  Just a note below:

2023-09-06 13:43 UTC, EdwardCoyle commented on docs/CHANGELOG.md
> +- `[Searchfield]` Adjusted position and hover color for custom button. ([#7832](https://github.com/infor-design/enterprise/issues/7832))
Very minor but I think this belongs under v4.88

2023-09-06 13:46 UTC, tmcconechy commented on docs/CHANGELOG.md
> +- `[Searchfield]` Adjusted position and hover color for custom button. ([#7832](https://github.com/infor-design/enterprise/issues/7832))
Yes on 4.88 now

2023-09-06 17:29 UTC, tmcconechy requested changes
Seems to be an issue with the component on mobile view ports.

![Screenshot 2023-09-06 at 1 27 29 PM](https://github.com/infor-design/enterprise/assets/814283/9fb5fe0a-1892-439d-887e-70d6904fd2ca)

a) the buttons are for from the right (see b)
b) the left side icon to collapse is on the wrong side
c) if you expand and then collapse it looks strange (buttons all out of place)

2023-09-08 14:14 UTC, clayinfor submitted a review, later dismissed

2023-09-11 10:50 UTC, tjamesallen15 submitted a review, later dismissed

2023-09-11 14:52 UTC, tmcconechy commented
It looks a little funny when you expand and then collapse it 

1) Leaves it in wrong place
![Screenshot 2023-09-11 at 10 52 04 AM](https://github.com/infor-design/enterprise/assets/814283/03ebd52f-029a-49f5-86d1-bbf740d0635f)
2) can animation be improved?

2023-09-13 16:46 UTC, tmcconechy approved these changes

2023-09-14 04:07 UTC, janahintal requested changes
Hello, noticed the following upon testing. 

No ellipsis when not hovered or focus
![image](https://github.com/infor-design/enterprise/assets/45757016/e5588f52-c7c4-4068-8e97-d365eb9d864a)

Focus overlaps in ellipsis in responsive view. 
![image](https://github.com/infor-design/enterprise/assets/45757016/c0c85fcc-2a9f-4c14-a880-d5f0e01936d5)

Too much space on bar code and x icon
![image](https://github.com/infor-design/enterprise/assets/45757016/d7bc9ff5-fceb-4a19-8f8c-9ba8ac21df25)

2023-09-14 04:37 UTC, jbrcna commented
the ellipsis is shown even if there still a space left for characters.
key in "the quick brown fox"
<img width="498" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/23c244f9-660a-4c11-b465-d13b8b6ea815">

in classic, bar code icon is not displayed.
<img width="451" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/cc734304-2978-43e9-bcd1-7e3be5f9012d">

2023-09-14 08:18 UTC, glenlieorillo requested changes
Tested also in BrowserStack.

https://7832-searchfield-custom-button-enterprise.demo.design.infor.com/components/searchfield/example-buttons.html

**1. The text and barcode are overlapping.**
![image](https://github.com/infor-design/enterprise/assets/102151352/1c90a772-ae45-4e90-944c-86cb5a48c279)

**2. The issue found by @tmcconechy still exists on mobile.**

Steps to reproduce:
1. Type in any text in search bar
2. Click close button
3. See error

![image](https://github.com/infor-design/enterprise/assets/102151352/740ad2a4-f914-480d-b465-e9847b217107)

**3. Barcode is not aligned properly.**
![image](https://github.com/infor-design/enterprise/assets/102151352/98356c79-0696-4610-999f-9d02a6e013d7)

**4. Too much space between barcode and close button.**
![image](https://github.com/infor-design/enterprise/assets/102151352/c37efcf6-3db2-4b89-aa3c-290adfc0e742)

2023-09-15 15:57 UTC, tmcconechy submitted a review, later dismissed
@janahintal @glenlieorillo anything else you think we need to fix here?
Note this is a minor pattern. And we should focus on the original issue

2023-09-18 10:19 UTC, ericangeles approved these changes

2023-09-18 11:25 UTC, glenlieorillo requested changes
'Sort' button is cut-off and the 'Sort' option also appears on the dropdown menu.

https://7832-searchfield-custom-button-enterprise.demo.design.infor.com/components/toolbar-flex/example-search-before-buttonset.html

![image](https://github.com/infor-design/enterprise/assets/102151352/64bcbdcd-beb8-452c-8f44-39ed8721f961)

Menu button is cut-off and it also appears on the dropdown menu.

https://7832-searchfield-custom-button-enterprise.demo.design.infor.com/components/toolbar-flex/example-searchfield-collapsible.html

![image](https://github.com/infor-design/enterprise/assets/102151352/a5b8036f-6503-46c1-8b42-d979bf998e59)

2023-09-18 13:09 UTC, jbrcna requested changes
in classic, bar code icon is not displayed.
<img width="462" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/c1adc417-6ef0-4c64-beb4-7c4b4ddc42e2">

icon not centered
<img width="396" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/4194db12-ba74-4284-848a-3f81b24133f8">
<img width="365" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/e08b6074-b704-4103-ad08-57816d9bdbce">

2023-09-18 13:43 UTC, tmcconechy commented
@yohannahbautista the issue with the button cut off is not fixable. This is how the toolbar works. It may partly cut off the button depending on the width but perhaps @yohannahbautista can look a bit at the other part(s)

2023-09-19 14:25 UTC, ericangeles commented
@jbrcna could you create a separate ticket for the second one?

2023-09-19 14:50 UTC, tmcconechy submitted a review, later dismissed

2023-09-21 15:10 UTC, tmcconechy approved these changes
Is this all done aside from future issues? I think its good enough as is. Wierd pattern not used much

2023-09-22 14:57 UTC, tmcconechy commented
@ericangeles what should we do this this one? I think maybe merge and raise new issues for anything related.

2023-09-22 15:36 UTC, ericangeles commented
@tmcconechy, yeah, let's merge this PR and create a separate issue(s) if there are any.

2023-09-22 15:37 UTC, tmcconechy approved these changes

2023-09-22 15:39 UTC, merged