7908  - Add new disabled filter styles
infor-design/enterprise pull request #7913
Opened 2023-09-07 14:46 UTC by tmcconechy

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

After recent datagrid changes the disabled filter row did not look disabled. This fixes that.

**Related github/jira issue (required)**:
Fixes #7908 

**Steps necessary to review your pull request (required)**:
- fixes http://localhost:4000/components/datagrid/test-filter-disabled.html

**Included in this Pull Request**:
- [x] A note to the change log.

2023-09-08 14:12 UTC, clayinfor approved these changes

2023-09-11 10:47 UTC, tjamesallen15 approved these changes

2023-09-12 11:46 UTC, glenlieorillo requested changes
Hello @tmcconechy, I'm a bit confused. Is this correct or it should be grayed out to look disabled?

<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/1e656a23-3bda-47de-bcf7-e00558760191">

2023-09-13 06:04 UTC, glenlieorillo commented
> @glenlieorillo good question. I think this looks ok for now. As you can see the text clearly and the field is still disabled. Lets see on other feedback but leave it for now

This is noted, @tmcconechy. Thank you!

2023-09-13 06:05 UTC, glenlieorillo approved these changes

2023-09-13 09:54 UTC, merged