7796 - Editor Text Header and Color
infor-design/enterprise pull request #7918
Opened 2023-09-11 02:14 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix editor text not changing to other font headers after changing colors.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7796

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/editor/example-index.html
- Select all the text inside the editor
- Change to `Header 1`
- Change the color of the text
- Change to `Normal Text`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-09-11 16:38 UTC, tmcconechy requested changes
@tjamesallen15 the only issue i see with the steps is if you notice the color is not changed.

- select all
- change to header 1
- change color to red
- change to normal text
- color is not red

2023-09-12 10:07 UTC, jbrcna commented
you can now changed the heading style after changing font color. However, when color is changed and you switch the heading style, the font color switches to black


https://github.com/infor-design/enterprise/assets/56722184/09aae0db-be55-4a93-bd2a-cd60d97d3306

2023-09-12 10:09 UTC, ericangeles commented
@tjamesallen15 can you take a look at @jbrcna's comment?

2023-09-12 14:12 UTC, tmcconechy commented
@tjamesallen15 @ericangeles i think me and @jbrcna are seeing the same thing. The color didnt change in some cases (or changed back)

2023-09-13 02:11 UTC, tjamesallen15 commented
Can we test this on local @jbrcna @tmcconechy,

For some reason it, my changes doesn't reflect on branch link

2023-09-13 02:12 UTC, jbrcna submitted a review, later dismissed
this is now working In local.
http://localhost:4000/components/editor/example-index.html
https://github.com/infor-design/enterprise/assets/56722184/24394b49-8c06-4959-aabf-651357167bb8

2023-09-13 13:42 UTC, ericangeles commented on docs/CHANGELOG.md
> +- `[Chart]` Fix on focus border being off in chart legend items. ([#7850](https://github.com/infor-design/enterprise/issues/7850))
Can you remove the duplicate entry log, @tjamesallen15 ? It's the #7850

2023-09-13 14:01 UTC, tmcconechy approved these changes

2023-09-13 14:55 UTC, merged

2023-09-13 14:56 UTC, tmcconechy commented
Artem is looking when the resource dont reflect its usually a resources problem on the server