Adjusted chart title for column charts.
infor-design/enterprise pull request #7920
Opened 2023-09-11 11:39 UTC by RJ-Csc

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjusted width for widget title to allow for full text chart title.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/7889

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app.
- Go to: 
  - http://localhost:4000/components/column/example-rotate.html
  - http://localhost:4000/components/column-grouped/example-axis-labels.html
  - http://localhost:4000/components/column-grouped/example-column-grouped-with-line-combined-hide-dots.html
  - http://localhost:4000/components/column-grouped/example-column-grouped-with-line-combined.html
- Chart titles should not overflow.

**Included in this Pull Request**:
- [x] A note to the change log.

2023-09-11 16:44 UTC, tmcconechy submitted a review, later dismissed

2023-09-11 16:44 UTC, tmcconechy commented on docs/CHANGELOG.md
>  - `[Tabs]` Fixed the focus alignment in tabs for RTL. ([#7772](https://github.com/infor-design/enterprise/issues/7772))
Looks good all in this issue. But note that we keep the change log in alphabetic order. So please move this up before `[Tabs]`. Thanks @RJ-Csc

2023-09-12 03:03 UTC, yohannahbautista requested changes
Same comment as Tim's

2023-09-12 09:53 UTC, jbrcna approved these changes
http://localhost:4000/components/column/example-rotate.html
<img width="869" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/bf7e853e-b5a0-4d1c-84bd-cb480125fc6e">

http://localhost:4000/components/column-grouped/example-axis-labels.html
<img width="939" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/1d34ffd4-1bba-4a41-ad86-75527375feab">

http://localhost:4000/components/column-grouped/example-column-grouped-with-line-combined-hide-dots.html
<img width="934" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/15b004c7-cfeb-446f-b0b3-37ad5d83565c">

http://localhost:4000/components/column-grouped/example-column-grouped-with-line-combined.html
<img width="886" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/5aa6e014-c7d9-4071-879f-8caca6bf4f3a">

2023-09-12 14:33 UTC, tmcconechy submitted a review, later dismissed

2023-09-12 14:34 UTC, tmcconechy approved these changes

2023-09-12 16:53 UTC, ericangeles approved these changes

2023-09-13 01:43 UTC, yohannahbautista approved these changes

2023-09-13 02:00 UTC, jbrcna approved these changes

2023-09-13 04:08 UTC, merged