7014 - Centered drilldown button within Datagrid cell.
infor-design/enterprise pull request #7969
Opened 2023-09-21 06:09 UTC by RJ-Csc

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adjusted positioning of elements within Datagrid cell to be centered. This is to fix the drilldown button not being vertically centered at medium row height.

**Related github/jira issue (required)**:

Closes https://github.com/infor-design/enterprise/issues/7014

**Steps necessary to review your pull request (required)**:

- Pull this branch, build, and run the app.
- Go to: http://localhost:4000/components/datagrid/example-drilldown?theme=new&mode=dark&colors=0066D4
- Click the "More" button and select "Medium".
- Drilldown button should be centered.

**Included in this Pull Request**:
- [x] A note to the change log.

2023-09-21 15:35 UTC, tmcconechy requested changes
@RJ-Csc this is i think a risky change because you changed the defaults of the cells for every type of cell. If you look in the example it seems like he link is now not centered but the drill down button is https://main-enterprise.demo.design.infor.com/components/datagrid/example-drilldown

Can you find a different fix that only touchs the drill down button? (class: datagrid-drilldown)

2023-09-22 15:43 UTC, tmcconechy submitted a review, later dismissed

2023-09-25 02:55 UTC, yohannahbautista commented on src/components/datagrid/_datagrid-new.scss
> +  tbody tr td .datagrid-drilldown {
Very small, if you can put this up so it looks sorted, just to make it tidier
<img width="482" alt="image" src="https://github.com/infor-design/enterprise/assets/85279127/d6ff58da-7886-4d63-bd1a-8aa7eb39c960">

2023-09-25 04:20 UTC, janahintal approved these changes
Approving 
![image](https://github.com/infor-design/enterprise/assets/45757016/6889c68d-5d48-4054-b533-237c76438e58)

2023-09-25 07:33 UTC, jbrcna approved these changes

2023-09-25 08:00 UTC, glenlieorillo approved these changes
https://github.com/infor-design/enterprise/assets/102151352/715b3bde-2d13-4abd-b459-080ae3e36477

2023-09-25 09:00 UTC, merged