7614 - Fix overlapping axis labels when bar text is lengthy
infor-design/enterprise pull request #7989
Opened 2023-09-26 08:53 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes overlapping axis labels with horizontal bar texts if it's lengthy (5 or more than characters).

**Related github/jira issue (required)**:

Closes #7614 

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/bar/test-axis-labels-with-long-bar-texts
- Axis labels specifically left and right should not overlapping the bar labels and should be visible
- Test as well the short bar text in here http://localhost:4000/components/bar/example-axis-labels.html
- Test on smaller viewports

**Included in this Pull Request**:
~~- [] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2023-09-26 14:48 UTC, tmcconechy approved these changes

2023-09-26 14:48 UTC, tmcconechy commented
Looks good but is a conflict in a file to check now 👍🏻

2023-09-27 06:56 UTC, tjamesallen15 approved these changes

2023-09-27 12:29 UTC, jbrcna requested changes
right labels is cut off in classic. firefox browser not affected.
<img width="1046" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/03cded77-0a3d-4875-9b57-c13a5794b730">
<img width="914" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/003c1228-d25e-4d8c-9a9a-9977f1ea6bbd">

**firefox**
<img width="1277" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/9243462e-ea7e-421f-8ca5-40b7baa03b4e">

RTL firefox failed in classic
<img width="1432" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/268aa862-0a59-47e0-9ef7-3589dac84b7b">

2023-09-28 05:13 UTC, ericangeles commented
@jbrcna, take a look again. Nice catch btw.

2023-09-28 10:25 UTC, jbrcna approved these changes

2023-09-28 14:14 UTC, tmcconechy approved these changes

2023-09-28 14:14 UTC, merged