7756 - searchfield no results
infor-design/enterprise pull request #8007
Opened 2023-09-29 00:25 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add a test page for column filter locale settings.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/7756

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-filter-custom-date.html
- Try to use the filter in the `Order Date`

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2023-10-02 08:16 UTC, jbrcna requested changes
the fix is working. However, in Firefox when you click the **"No results"** text, the text becomes not visible.
<img width="680" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/f4e60ec1-2fd1-4bad-b22b-d4536200c64e">

2023-10-02 10:32 UTC, glenlieorillo requested changes
"No results" text becomes invisible upon hovering in Light and High Contrast Mode. (Firefox)

https://github.com/infor-design/enterprise/assets/102151352/6b8be275-96a5-4643-ae24-378191c8b665

2023-10-02 11:38 UTC, tjamesallen15 commented
You can now retest again @jbrcna @glenlieorillo Ty

2023-10-02 12:08 UTC, glenlieorillo submitted a review, later dismissed
This is now working as expected. Thanks, @tjamesallen15!


https://github.com/infor-design/enterprise/assets/102151352/9af155c6-5e65-44cf-9aa5-999cc61f50db

2023-10-02 13:22 UTC, jbrcna approved these changes

2023-10-02 13:38 UTC, tmcconechy commented on src/components/autocomplete/autocomplete.js
> +    // eslint-disable-next-line
May not be needed?

2023-10-02 13:39 UTC, tmcconechy requested changes
I see one issue. When you type xxx in the field and then click the no-search it acts as clearing the field. I dont think it should clear, should leave the text as is in the field

2023-10-02 13:45 UTC, tjamesallen15 commented
@tmcconechy i updated the PR by your request change.

2023-10-02 13:49 UTC, tmcconechy approved these changes
Thanks! Looks good!

2023-10-02 14:44 UTC, merged

2023-10-03 05:26 UTC, glenlieorillo reviewed
This is now working as expected.

https://github.com/infor-design/enterprise/assets/102151352/a50736aa-e7b0-4e5b-b101-a6130fa61bbf