7840 - Added overnight event view when end time goes to next day
infor-design/enterprise pull request #8026
Opened 2023-10-04 04:54 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added overnight event view when end time goes to next day

**Related github/jira issue (required)**:

Closes #7840 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/week-view/test-overnight
- Overnight event (gray color, "Holiday trip") should not be in all day row and should span 22 and 23

**Included in this Pull Request**:
- [ ] A note to the change log.

2023-10-04 14:53 UTC, tmcconechy requested changes
@yohannahbautista the only problem with this is this was for the stacked example http://localhost:4000/components/week-view/example-stacked.html

So it makes it look confusing in that example because the time doesnt line up right. Can you change the new example so it shows a stacked example? Thanks!

2023-10-05 14:15 UTC, tmcconechy commented
@yohannahbautista http://localhost:4000/components/week-view/example-stacked.html looks good. Maybe we just dont need http://localhost:4000/components/week-view/test-overnight.html at all as it is confusing that the times dont line up.

If you agree just delete it and i think we are good 👍🏻

2023-10-06 05:01 UTC, ericangeles commented on docs/CHANGELOG.md
> +- `[Weekview]` Added overnight event view when end time goes to next day. ([#7840](https://github.com/infor-design/enterprise/issues/7840))
Please add this to 4.89.0 log @yohannahbautista

2023-10-06 16:05 UTC, tmcconechy submitted a review, later dismissed
Aside from the change log approving

2023-10-09 03:31 UTC, tjamesallen15 approved these changes

2023-10-10 03:03 UTC, max-hizon commented
Works on Chrome, Edge, and Firefox browsers in both New and Classic versions
<img width="264" alt="image" src="https://github.com/infor-design/enterprise/assets/79514236/ee0c40d5-14ef-49f8-95cd-c211b6cbe583">

<img width="270" alt="image" src="https://github.com/infor-design/enterprise/assets/79514236/cc226435-6d96-466a-9e67-84311befd788">

2023-10-10 05:44 UTC, glenlieorillo submitted a review, later dismissed
![image](https://github.com/infor-design/enterprise/assets/102151352/3fe0a2d8-1112-49e4-9f3a-8111ccdf809e)

![image](https://github.com/infor-design/enterprise/assets/102151352/6457412e-2df7-45d9-b39e-2bbbca5ed40f)


![image](https://github.com/infor-design/enterprise/assets/102151352/e9b08b4c-75a6-4b7e-a890-e8af8fac4c7c)

2023-10-10 07:05 UTC, janahintal approved these changes
Approving 
<img width="1344" alt="image" src="https://github.com/infor-design/enterprise/assets/45757016/d9124508-b9ba-4031-999b-8d9c9d178897">

2023-10-10 10:57 UTC, jbrcna approved these changes
<img width="1531" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/48ea7ebc-3dcb-4f06-865b-aef7098d51f1">

2023-10-10 11:05 UTC, jbrcna commented
in mobile device, overnight event is not visible (23rd date)
<img width="529" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/b6a44fa1-cbef-49ad-bc5c-3dcc3a94fb96">
<img width="429" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/0a4f8de4-a5dc-40a7-9718-c565e54e019e">

2023-10-10 13:39 UTC, merged