8071 - Fix on new row not showing error tooltip on first cell
infor-design/enterprise pull request #8150
Opened 2023-11-07 06:20 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Fix on new row not showing error tooltip on first cell. 

Note: Made test page based on the instructions given on the issue. Should also be able to replicate it via console to be sure as no stackblitz example was given.

**Related github/jira issue (required)**:

Closes #8071 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/test-newrow-error.html
- Click on Add Row
- Click on Add Error
- Hover over the error icons
- Tooltip should appear

**Included in this Pull Request**:
- [ ] A note to the change log.

2023-11-07 16:08 UTC, tmcconechy commented
cc @infor-design/qa

2023-11-07 16:11 UTC, tmcconechy requested changes
@yohannahbautista looks working but a few suggestions.

1. When showing the error the icon in the black add row status disappears
2. Can we remove all upper case text (use sentence case)
3. The position of the tooltip should be lower (arrow is 4-6px under the icon)

![Screenshot 2023-11-07 at 11 10 21 AM](https://github.com/infor-design/enterprise/assets/814283/3848e51d-bec7-4409-8971-e75e313842d8)

2023-11-08 08:04 UTC, jbrcna submitted a review, later dismissed
<img width="689" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/8a8eaea3-1e54-4620-a760-d3d4bad6468b">
<img width="615" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/c09f38f9-7e49-4b55-ba68-edabd83d24bd">

2023-11-08 08:43 UTC, ericangeles commented
Looks good! 🍌

2023-11-08 08:46 UTC, ericangeles commented on docs/CHANGELOG.md
> +- `[Datagrid]` Fix on new row not showing error tooltip on first cell. ([#8071](https://github.com/infor-design/enterprise/issues/8071))
It can be, `Fixed an issue where the new row did not display an error tooltip on the first cell.` Very minor, but it helps maintain consistency in our changlog entries by making it past tensed.

2023-11-08 09:54 UTC, glenlieorillo requested changes
Text alignment looks a bit off in Classic.

<img width="836" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/957aa809-8f34-46cc-837f-007ea1fa7687">

<img width="836" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/34027027-1a44-4497-a5f0-f4666a85c8fc">

2023-11-08 15:53 UTC, tmcconechy commented
Good for me, aside from the above comments. But can you make the tooltip sentence case (new standard). Maybe something like "Test tooltip 0" (sorry very minor)

2023-11-09 03:54 UTC, glenlieorillo approved these changes
This is now working as expected. Thanks, @yohannahbautista!


https://github.com/infor-design/enterprise/assets/102151352/fa2534fc-5dbc-4990-b673-d874af1e3a2b

2023-11-09 05:04 UTC, jbrcna approved these changes

2023-11-09 13:37 UTC, janahintal approved these changes
Working as expected 
https://www.loom.com/share/d3d07b1e9e634f1bb8f5f77835e8208d?sid=28649c7f-d5a8-4c3b-a166-1d6550b5e018

2023-11-09 16:02 UTC, tmcconechy approved these changes

2023-11-09 16:02 UTC, merged