8021 - Fixed misalignment on date cells when selected
infor-design/enterprise pull request #8163
Opened 2023-11-09 07:20 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added additional check for when setting focus on editor

**Related github/jira issue (required)**:

Closes #8021 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/datagrid/example-editable.html
- Click on a date cell with value
- Date should be seen

**Included in this Pull Request**:
- [ ] A note to the change log.

2023-11-09 16:07 UTC, tmcconechy requested changes
One related issue is when you focus the cell vs when you hover it the icon is a different size. Should be 18x18 in both cases (and in same/similar position) (also check RTL)

2023-11-10 15:03 UTC, tmcconechy approved these changes
Looks great ❤️

2023-11-13 06:06 UTC, ericangeles approved these changes

2023-11-13 06:40 UTC, max-hizon approved these changes
Works as expected


https://github.com/infor-design/enterprise/assets/79514236/6be45b5f-3c82-4486-84be-d931642a5c77

2023-11-13 14:48 UTC, tmcconechy approved these changes

2023-11-13 14:48 UTC, merged