8165 - Updated colors in colorpicker
infor-design/enterprise pull request #8185
Opened 2023-11-15 05:05 UTC by max-hizon

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
This pull request will update the color palette used in colorpicker

**Related github/jira issue (required)**:
Closes: https://github.com/infor-design/enterprise/issues/8165

**Steps necessary to review your pull request (required)**:
1. Go to http://localhost:4000/components/colorpicker/example-index.html
2. Click the color picker drop down
3. See that the color options are now updated to match current color palette. Use https://design.infor.com/code/ids-enterprise/latest/demo/components/colors/example-index?theme=uplift&variant=light as reference

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2023-11-15 16:43 UTC, tmcconechy requested changes
Looks good on the color picker changes but looks like the CHANGELOG and maybe contextual action panel are deleted/or changed by accident?

2023-11-16 01:48 UTC, max-hizon commented
> Looks good on the color picker changes but looks like the CHANGELOG and maybe contextual action panel are deleted/or changed by accident?

I think I must've accidentally worked on a different branch while using this one. Will fix.

2023-11-16 02:04 UTC, max-hizon commented
@tmcconechy After reviewing the code it seems for some reason when I edited CHANGELOG.md and contextual action panel, the edit made it so it erased its contents and replaced it with the same code along with the changes I made. For contextual action panel, it seems to have just deleted the code and replaced it with the same.

2023-11-16 06:44 UTC, yohannahbautista commented on docs/CHANGELOG.md
> -- `[Tabs-Module]` Removed padding in embedded mode. ([#8060](https://github.com/infor-design/enterprise/issues/8060))
Unless this was removed to fix sorting or it's a duplicate, please undo this

2023-11-16 14:57 UTC, tmcconechy approved these changes
Thanks @max-hizon no problem. I do that too sometimes. Just flagging it. (one tip is i like to review my own PR when i first put it in).

Cheers 👍🏻 Nice Work here

2023-11-17 01:11 UTC, jbrcna approved these changes
nice work @max-hizon . are you a dev now?
<img width="473" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/b55686a7-33ab-44a1-b5f2-085268f8da32">

2023-11-17 01:31 UTC, yohannahbautista approved these changes

2023-11-17 02:13 UTC, glenlieorillo approved these changes
<img width="750" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/6f1a639a-a4eb-444f-83cb-6c3f9ca0561c">

<img width="750" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/5893d468-ef0e-4957-abf1-1039d03bcbdf">

2023-11-17 14:57 UTC, merged