8012 - Fix datagrid's drag handle position in firefox
infor-design/enterprise pull request #8207
Opened 2023-11-23 12:30 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This PR fixes the issue of the (Datagrid) drag handle's position overlapping the header text in the Firefox.

**Related github/jira issue (required)**:

Closes #8012

**Steps necessary to review your pull request (required)**:
- Pull this branch, build, and run the app
- Open firefox browser and go to http://localhost:4000/components/datagrid/test-filter-custom-date.html
- Hover over any column (left-aligned text)
- Drag handle should not overlapping the header text

**Included in this Pull Request**:
~~- [ ] An e2e or functional test for the bug or feature.~~
- [x] A note to the change log.

2023-11-28 07:08 UTC, jbrcna approved these changes
<img width="1718" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/3de9f53c-8cda-4198-b4e1-e7768421eac1">
<img width="1705" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/007e3c92-3702-48f4-be76-a8198a353dc1">
<img width="1650" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/bcf606db-4eb4-490a-9ee9-5420344ce5f5">

2023-11-28 14:05 UTC, glenlieorillo requested changes
The issue has been resolved. However, I noticed that the searchlist icon is not properly aligned.


https://github.com/infor-design/enterprise/assets/102151352/b20f9efb-7818-4aec-87ac-561e49f1d6d8

![image](https://github.com/infor-design/enterprise/assets/102151352/dcbebf8e-0d56-4256-8612-85586cbba800)

2023-11-29 11:13 UTC, ericangeles commented
@glenlieorillo, could you hard reload the page? It seems that the CSS file isn't being read immediately, causing this flaky issue on Firefox. In this case, I don't see any way to fix this.

If you do a hard reload (which clears the cache), you'll see that it's positioned correctly.

2023-11-29 12:46 UTC, glenlieorillo approved these changes
This is all good now, I have to clear the cache. Thanks, @ericangeles!

<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/86a81ce1-affd-4bae-9269-1991a35659af">

2023-11-29 13:21 UTC, merged