8220 - Fixed wrong hover color on button
infor-design/enterprise pull request #8278
Opened 2023-12-21 06:05 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Moved hover color to datagrid expand button as it seems to be for that only.

**Related github/jira issue (required)**:

Closes #8220 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/button/example-100-percent.html
- Hover on buttons
- Hover color should be correct

**Included in this Pull Request**:
- [ ] A note to the change log.

2023-12-22 14:46 UTC, tmcconechy submitted a review, later dismissed

2023-12-22 16:16 UTC, jbrcna requested changes
hover color is correct. however, the text changes color in classic theme.
<img width="1643" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/4d7dd2ee-fb32-4a37-a762-43b7e005a91e">

2023-12-22 16:43 UTC, tmcconechy commented
@yohannahbautista can you fix the color in classic. Thanks !!

2023-12-27 10:46 UTC, ericangeles approved these changes

2023-12-27 12:35 UTC, jbrcna approved these changes
<img width="1642" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/0deedd06-a4c1-468c-b182-10b7928e442a">

2023-12-27 14:08 UTC, tmcconechy approved these changes

2023-12-27 14:08 UTC, merged