NG1605 - Searchfield Category Compact
infor-design/enterprise pull request #8330
Opened 2024-01-11 03:43 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix compact size height.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1605

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/searchfield/test-searchfield-category-compact.html
- See the compact size

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2024-01-11 18:36 UTC, tmcconechy commented
![Screenshot 2024-01-11 at 1 35 45 PM](https://github.com/infor-design/enterprise/assets/814283/e5342977-35f6-4c25-a1ac-57c510adfe99)

- we might have to make the one bigger so the X doesnt take up the whole thing or hide the X in that case with the setting
- x could be centered vertically (we can consider making it 16x16 as well for compact)

2024-01-16 16:53 UTC, tmcconechy approved these changes

2024-01-18 06:12 UTC, jbrcna requested changes
<img width="525" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/875d65b9-513d-436d-944b-a5f5800740f8">
<img width="540" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/c8bb3bee-1173-4d53-89ed-5acc5a3080c3">
<img width="433" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/33bcd8b1-b007-4c1b-885b-fbc7906e3f20">

**Failing in Firefox classic theme**
<img width="508" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/8ee8ace0-13af-4304-b5bd-79aa1d29f92a">

2024-01-19 12:47 UTC, whernebrink commented on app/views/components/searchfield/test-searchfield-category-compact.html
> +      <input id="searchfield-1" class="searchfield mp-search-input" />
Please remove `mp-search-input` on the inputs. This is a class we define and use in the experience designer, would just confuse consumers of this enterprise-ng. :)

2024-01-19 12:47 UTC, whernebrink commented on src/components/searchfield/searchfield.js
> +      console.log(targetWidthProp);
Remove log :)

2024-01-22 12:00 UTC, janahintal requested changes
Still failing on my end. 
![image](https://github.com/infor-design/enterprise/assets/45757016/a1651a51-d771-4790-8136-6ac5551aab52)
![image](https://github.com/infor-design/enterprise/assets/45757016/dc07788e-7450-4f20-9972-06cbf2aac0ad)

2024-01-22 12:49 UTC, glenlieorillo requested changes
Misaligned close button in LTR and RTL.

https://github.com/infor-design/enterprise/assets/102151352/abb4f23f-e644-4172-9b46-38d3dd0a5c8a

![image](https://github.com/infor-design/enterprise/assets/102151352/6c3e19a7-8f81-4f93-a4fd-f695be61aa6f)

2024-01-22 13:21 UTC, jbrcna requested changes
<img width="765" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/58fb9d48-b113-4a47-a5f3-63208d4a3746">

2024-01-22 23:54 UTC, tjamesallen15 commented
can you guys specify what browsers are on the screenshots? it will be helpful on my end. @infor-design/qa

2024-01-23 05:10 UTC, glenlieorillo commented
Hello @tjamesallen15, I tested this on Mac Chrome. Thanks!

2024-01-23 05:12 UTC, jbrcna commented
> Hello @tjamesallen15, I tested this on Mac Chrome. Thanks!


Mac Firefox

2024-01-23 14:25 UTC, tjamesallen15 commented
> Still failing on my end. ![image](https://private-user-images.githubusercontent.com/45757016/298578130-a1651a51-d771-4790-8136-6ac5551aab52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTk2MzMsIm5iZiI6MTcwNjAxOTMzMywicGF0aCI6Ii80NTc1NzAxNi8yOTg1NzgxMzAtYTE2NTFhNTEtZDc3MS00NzkwLTgxMzYtNmFjNTU1MWFhYjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE0MTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MzJjNjU3NDkwN2U2M2ViZTNhYWM4MWExMmNmOTM5NjJkMzVmNWI1ZjVmNDdiODljMjllODkyMDIwOGM5NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DBrSFDIFG4yLwIgsDUUdeUazZvJH01Vv5bZLOPoKFqo) ![image](https://private-user-images.githubusercontent.com/45757016/298578407-dc07788e-7450-4f20-9972-06cbf2aac0ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTk2MzMsIm5iZiI6MTcwNjAxOTMzMywicGF0aCI6Ii80NTc1NzAxNi8yOTg1Nzg0MDctZGMwNzc4OGUtNzQ1MC00ZjIwLTk5NzItMDZjYmYyYWFjMGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE0MTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNDAwM2EwNzhiOGE0MGU1OTAyM2RhZmFhMzBiYmJlYWMwMjY5YjUyYWFlYjU4ODNhYTNiZGI4N2IwOTY3MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lLeiom6YshbwTDOLCQDLVcsaD5ajvPzY5z4woMHx3tw)

May i know what browser is this?

2024-01-24 04:07 UTC, janahintal commented
> > Still failing on my end. ![image](https://private-user-images.githubusercontent.com/45757016/298578130-a1651a51-d771-4790-8136-6ac5551aab52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTk2MzMsIm5iZiI6MTcwNjAxOTMzMywicGF0aCI6Ii80NTc1NzAxNi8yOTg1NzgxMzAtYTE2NTFhNTEtZDc3MS00NzkwLTgxMzYtNmFjNTU1MWFhYjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE0MTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MzJjNjU3NDkwN2U2M2ViZTNhYWM4MWExMmNmOTM5NjJkMzVmNWI1ZjVmNDdiODljMjllODkyMDIwOGM5NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DBrSFDIFG4yLwIgsDUUdeUazZvJH01Vv5bZLOPoKFqo) ![image](https://private-user-images.githubusercontent.com/45757016/298578407-dc07788e-7450-4f20-9972-06cbf2aac0ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTk2MzMsIm5iZiI6MTcwNjAxOTMzMywicGF0aCI6Ii80NTc1NzAxNi8yOTg1Nzg0MDctZGMwNzc4OGUtNzQ1MC00ZjIwLTk5NzItMDZjYmYyYWFjMGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE0MTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNDAwM2EwNzhiOGE0MGU1OTAyM2RhZmFhMzBiYmJlYWMwMjY5YjUyYWFlYjU4ODNhYTNiZGI4N2IwOTY3MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lLeiom6YshbwTDOLCQDLVcsaD5ajvPzY5z4woMHx3tw)
> 
> May i know what browser is this?

@tjamesallen15 Chrome, Windows 10.

2024-01-24 12:49 UTC, janahintal commented
Hi @tjamesallen15 this has been retested and still failing on my end. 

Environment
Browser: All 
OS: Mac & Windows10

![image](https://github.com/infor-design/enterprise/assets/45757016/a4c08ce3-7ac3-477c-8040-4fb13e6d1d1c)

2024-01-24 13:44 UTC, tjamesallen15 commented
Done pls check again @janahintal

2024-01-24 17:53 UTC, tmcconechy approved these changes

2024-01-25 02:55 UTC, janahintal reviewed
HI @tjamesallen15, border focus still looks off on my end for all OS and Browsers. 
![image](https://github.com/infor-design/enterprise/assets/45757016/e106737b-2691-4eae-a68e-59a4c760e25c)
![image](https://github.com/infor-design/enterprise/assets/45757016/4e3d7fe0-25f2-473d-8566-457c373bae6d)

2024-01-25 03:17 UTC, jbrcna commented
**inconsistent borders**
<img width="428" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/c5aa442a-59f2-4f77-bab5-c00a48b6c281">
notice that the border below overlaps
<img width="404" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/791b790e-1918-459d-b8a0-06086112ef05">

more so  in chrome
<img width="538" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/2f611e3b-8fe2-4cb3-ab25-f9ea3c3dbc1d">


 
and misaligned in firefox
<img width="439" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/89dffe14-6b0c-495b-85a8-a3fdad131493">


**Classic theme**
**Safari**
<img width="423" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/575af5db-32e0-4401-bb69-de7be0582192">

**Firefox**
<img width="509" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/c85c0979-5102-4c1b-a150-c59b9ef05b9b">

2024-01-25 08:16 UTC, glenlieorillo approved these changes
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/9d6dd6a8-26f3-4179-8360-159fb4f54510">

<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/786866e6-5b59-4ff8-965c-02b7557764f6">

2024-01-25 10:32 UTC, janahintal approved these changes
![image](https://github.com/infor-design/enterprise/assets/45757016/4f3bb2b1-071d-48f6-803c-b5f403810f0a)
![image](https://github.com/infor-design/enterprise/assets/45757016/294b76b3-13e2-4a03-b6fb-d0d3faffa952)
![image](https://github.com/infor-design/enterprise/assets/45757016/fab2d827-ae40-4590-af53-725ee987e862)

2024-01-25 12:07 UTC, ericangeles approved these changes

2024-01-25 12:07 UTC, merged