8310/8311/8312 - Gen AI
infor-design/enterprise pull request #8370
Opened 2024-01-23 14:36 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2024-01-23 20:04 UTC, tmcconechy reviewed
Some comments:

1. See inline
2. should the editor button do anything? I see some code in the example but it doesnt do anything when i click it. Maybe at least a console message for the event when its clicked?
3. Maybe put the loading-indicator in the busy indicator folder because it looks like 2 different components. Not sure about that

2024-01-23 20:28 UTC, tmcconechy reviewed
Couple more comments I had to add.

2024-01-23 20:28 UTC, tmcconechy commented on app/views/components/loading-indicator/example-ai-loading.html
> +    <div class="ai-loading-indicator">
Maybe see that it work hides with `hidden` just in case.

2024-01-23 20:28 UTC, tmcconechy commented on app/views/components/editor/example-with-gen-ai-button.html
> +    editorElement.on('AIButtonClicked', function (e, elements) {
The animation should go in the button and be the ... one in the design. Maybe an `animationStart` and `animationEnd` function in the button? And be changed to the ... animation (details to follow)

2024-01-24 15:17 UTC, tmcconechy commented
**New Points**

- only show icon the right on tertiary (not both)
- flip icon pos on RTL
- instead of btn-gen-ai -> btn-generative
- animation uses dots (of different size) https://codepen.io/tmcconechy/pen/bGZrQjw (small icon button needs smaller dots)
- check generate icon color

2024-01-24 20:15 UTC, tmcconechy commented
Advancing this to QA but still need a couple things...So we have to work in parrallel

2024-01-25 11:10 UTC, janahintal requested changes
http://localhost:4000/components/loading-indicator/example-ai-loading.html is not working / not yet deployed. 
![image](https://github.com/infor-design/enterprise/assets/45757016/be510d74-0c56-43fd-a204-55c21aaffcb7)

2024-01-25 11:58 UTC, ericangeles commented
@janahintal it's been changed to http://localhost:4000/components/busyindicator/example-ai-loading-indicator.html

2024-01-25 12:37 UTC, janahintal requested changes
Failing on Classic mode. 

Looks off on Classic for all Modes
http://localhost:4000/components/button/example-index.html?theme=classic&mode=light&colors=default 
![image](https://github.com/infor-design/enterprise/assets/45757016/fffcf6c0-cda1-45c0-aa5c-f1746b24ab12)
![image](https://github.com/infor-design/enterprise/assets/45757016/32b03db7-7125-40a0-8f37-917b8bd3deed)
![image](https://github.com/infor-design/enterprise/assets/45757016/8076c22b-a0df-4e37-964d-97fd98916b45)


Passed on New Version only: 
![image](https://github.com/infor-design/enterprise/assets/45757016/b78e7be2-d764-4442-8415-4d047cad220f)
![image](https://github.com/infor-design/enterprise/assets/45757016/f5babb55-0942-4f74-a2ea-58ed33834207)



**Passed:**  all modes and versions
http://localhost:4000/components/busyindicator/example-ai-loading-indicator.html?theme=classic&mode=light&colors=default

2024-01-25 12:59 UTC, ericangeles commented
@janahintal, the Insight icon is only available in the 'New' version. We'll consider the classic version as minor.

2024-01-25 14:21 UTC, tmcconechy commented
Yes @janahintal wont be available in classic mode.

2024-01-25 17:08 UTC, merged