8198 - Datagrid Frozen Column Prevent Reorder
infor-design/enterprise pull request #8371
Opened 2024-01-23 15:19 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix frozen columns getting out of sync when columnReorder is set to true.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8198

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/datagrid/test-frozen-columns.html
- Open `...` on the header of the datagrid
- Click `Personalize Columns`
- See the order and click `Close`
- Try dragging `Product Id` column, it shouldn't be allowed
- Try dragging `Quantity` column to `Product Id` column, nothing happens
- Open `...` on the header of the datagrid
- Click `Personalize Columns`
- The order should be the same

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2024-01-23 15:31 UTC, tmcconechy requested changes
This works well. But can we not show the arrows if you cant drag to it? I think that should be possible.

Also please check the `lint` error. Thanks @tjamesallen15

2024-01-24 05:13 UTC, ericangeles submitted a review, later dismissed

2024-01-24 17:56 UTC, tmcconechy approved these changes

2024-01-24 18:19 UTC, ericangeles approved these changes

2024-01-25 05:25 UTC, ericangeles commented
FYI @infor-design/qa

2024-01-25 10:24 UTC, janahintal approved these changes
This is now working as expected. 
![image](https://github.com/infor-design/enterprise/assets/45757016/ae8fbf8c-d94c-4ea2-b32c-e9a60088b3ac)

2024-01-25 12:09 UTC, merged