8373 - Add dateTimestamp date format
infor-design/enterprise pull request #8435
Opened 2024-02-12 09:07 UTC by ericangeles

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

**Related github/jira issue (required)**:

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2024-02-12 14:48 UTC, tmcconechy requested changes
@ericangeles something about this isnt working when i run the command:

```
// Old one works
Soho.Locale.formatDate(new Date(2000, 10, 8, 13, 40, 30, 999), { date: 'datetimeMillis' })
// New one does not work
Soho.Locale.formatDate(new Date(2000, 10, 8, 13, 40, 30, 999), { date: 'dateTimestamp' })
```

Also once this does work we should add this to every locale file.

2024-02-13 09:26 UTC, ericangeles commented
It looks like it needs to be added to every locale file.

2024-02-13 13:44 UTC, jbrcna approved these changes
<img width="638" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/d1c76f69-0582-40d8-a9f1-b99658cd46a4">

2024-02-13 14:15 UTC, tmcconechy approved these changes

2024-02-14 12:25 UTC, merged