8294 - Tabs Add Tab Button Focus
infor-design/enterprise pull request #8474
Opened 2024-02-21 12:05 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix add tab button focus.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8294

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/tabs/example-add-tab-button.html
- Click on `+` icon
- See the focus

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2024-02-22 04:04 UTC, jbrcna submitted a review, later dismissed
main
<img width="1361" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/d17f6dba-1926-41e1-aa54-4791af4e2789">

branch<8294-tabs-add-tab-button-focus>
<img width="1448" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/2102a075-980f-4c57-8493-ced8fecdfa6a">

2024-02-22 17:20 UTC, tmcconechy requested changes
@tjamesallen15 technically we should use "hide-focus" on this button as well. So it doesnt even focus on click only on keyboard. Can try to setup the HideFocus util for it like the buttons?

2024-02-27 04:10 UTC, jbrcna approved these changes
good work 🍌

<img width="1327" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/0623d047-cb34-4b2b-ab85-e16a8916cea4">


![Large GIF (1512x724)](https://github.com/infor-design/enterprise/assets/56722184/efe1fe47-41b7-44a6-8a50-83b370948733)

2024-02-27 15:43 UTC, tmcconechy approved these changes

2024-02-27 15:43 UTC, merged