8439 - Datagrid Always on Icons
infor-design/enterprise pull request #8518
Opened 2024-03-06 04:14 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix incosistencies in border colors of events in calendar.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8439

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/calendar/test-all-colors.html
- See all the colors and border colors

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2024-03-07 05:48 UTC, glenlieorillo requested changes
Datepicker and timepicker hover state is cut-off/misaligned.

https://github.com/infor-design/enterprise/assets/102151352/5204723a-f502-46c3-bfe0-0d51156bdd7e

![image](https://github.com/infor-design/enterprise/assets/102151352/f65a7648-197f-4dfc-a1ff-4f89a9ceef2e)

![image](https://github.com/infor-design/enterprise/assets/102151352/5ddb0ea9-e131-43c2-868d-e1d98373a7c1)

2024-03-07 17:37 UTC, tmcconechy reviewed
A bunch of little problems... Ranked:

1. The rows change size when i click them
2. The icon should show the hover state (it only does when i enter the cell)
3. The time picker is missing the arrow on the popup
4. The dropdown icon changes position when opened
5. The time picker icon changes position when opened (in some rowheights)
6. Probably need to test that on all 4 row heights

2024-03-07 17:37 UTC, tmcconechy commented on src/components/datagrid/datagrid.js
> + * @param {boolean} [settings.showIcons=false] If true will always show hoverable icons.
Maybe showEditorIcons to be more specific

2024-03-08 03:14 UTC, jbrcna requested changes
no tooltip arrow
icon not centered when hovered
no hover color when mouse is placed on top. it will display when clicked and hovered
<img width="681" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/26f506cc-33e6-4f1e-a893-d94ccb21f0af">

2024-03-08 16:44 UTC, tmcconechy commented
Looking better @tjamesallen15 still:

1) Can we make the buttons show the hover state on hover, also wondering why the color is grey on hover and not azure like https://main-enterprise.demo.design.infor.com/components/button/example-index.html
2) In extra small the icons shuffle (minorly)
3) In small  the icons shuffle (minorly)
4) In medium mode some of the text is sitting too high
5) Normal mode looks 👍🏻

2024-03-11 14:42 UTC, tmcconechy commented
@tjamesallen15 still see

1. Uncentered text and icons in medium
2. No hover state on the icon when its "on"

2024-03-13 15:17 UTC, tmcconechy approved these changes

2024-03-14 15:17 UTC, tmcconechy commented
@infor-design/qa can you re-review?

2024-03-15 06:04 UTC, ericangeles approved these changes

2024-03-15 16:51 UTC, merged