8433 - Datepicker Action Args
infor-design/enterprise pull request #8543
Opened 2024-03-14 05:22 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will add guards on possible undefined objects.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8419

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/calendar/example-index.html
- Open `Developer Console`
- Try to click a cell to see the args params
- Try to click today to see the args params
- Try to use the datepicker to pick a date to see the args params

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2024-03-14 15:23 UTC, tmcconechy approved these changes

2024-03-15 06:20 UTC, janahintal requested changes
Month value is incorrect. Kindly see image below. 
The date is December 2030 but the Month returns 11 instead of 12. 
![image](https://github.com/infor-design/enterprise/assets/45757016/a4ae8026-cbab-4672-80e6-3217f6dfe0aa)

2024-03-15 07:37 UTC, tjamesallen15 commented
> Month value is incorrect. Kindly see image below. The date is December 2030 but the Month returns 11 instead of 12. ![image](https://private-user-images.githubusercontent.com/45757016/313087217-a4ae8026-cbab-4672-80e6-3217f6dfe0aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0ODg1MjMsIm5iZiI6MTcxMDQ4ODIyMywicGF0aCI6Ii80NTc1NzAxNi8zMTMwODcyMTctYTRhZTgwMjYtY2JhYi00NjcyLTgwZTYtMzIxN2Y2ZGZlMGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDA3MzcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZWY5ODBiODI2YzFjZWYwOGM4ODQ1MTE5ODFkZTU1YTNhYTY1ODdjNTYwOTQ4NWZjODNkZGU2YWE1MjYzODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LCcKNY9OPP6Nypgz0igli-_F_Fo2_jj14IzYN1LRskI)

Hello @janahintal the month is base 0 in the calendar dataset, therefore it will start at 0 = january. onwards.

2024-03-15 15:19 UTC, n-ace-ancog submitted a review, later dismissed
Working as expected.

![image](https://github.com/infor-design/enterprise/assets/156752175/a0f1e300-0928-4281-8ee4-711f694536ff)

2024-03-15 16:54 UTC, tmcconechy approved these changes

2024-03-15 16:54 UTC, merged