8381 - Added setting to disable nav switcher
infor-design/enterprise pull request #8577
Opened 2024-04-01 10:19 UTC by yohannahbautista

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added setting to disable nav switcher

**Related github/jira issue (required)**:

Closes #8381 

**Steps necessary to review your pull request (required)**:

- Pull this branch, build and run the app
- Go to: http://localhost:4000/components/module-nav/example-index.html
- Toggle `Disable switcher` checkbox
- Switcher should be disabled/enabled on check/uncheck

**Included in this Pull Request**:
- [ ] A note to the change log.

2024-04-01 13:52 UTC, tmcconechy requested changes
@yohannahbautista when its disabled can we make the style

- no background
- 20px size (same as header)

<img width="1553" alt="Screenshot 2024-04-01 at 9 52 09 AM" src="https://github.com/infor-design/enterprise/assets/814283/abec065b-4408-43c0-9d43-165f0ee76db8">

2024-04-02 05:39 UTC, ericangeles approved these changes
Add this setting to NG as well. Thanks, @yohannahbautista 🍌

2024-04-02 09:34 UTC, ericangeles commented on docs/CHANGELOG.md
> +- `[Module Nav]` Added setting `disableSwitcher` to disable nav switcher. ([#8381](https://github.com/infor-design/enterprise/issues/8381))
Lets put it on `4.95` log, @yohannahbautista

2024-04-02 09:35 UTC, ericangeles commented
Let's not merge it yet @tmcconechy once this is okay with the QA.

2024-04-02 14:14 UTC, tmcconechy approved these changes

2024-04-03 02:43 UTC, jbrcna commented
this is now working as expected
<img width="1531" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/1752c2cf-537b-4dd7-bf1e-9229035b208a">

However, in firefox the text is not centered align.
<img width="1096" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/bef630e5-15a6-4f81-b089-54cd0c5fdbfc">

2024-04-04 15:18 UTC, tmcconechy approved these changes
Made a minor tweak as per https://inforwiki.atlassian.net/browse/IDS-2135
Approved now from design

2024-04-04 23:01 UTC, jbrcna approved these changes

2024-04-05 06:56 UTC, n-ace-ancog approved these changes
Working as expected.
![Animation](https://github.com/infor-design/enterprise/assets/156752175/0752347d-b0f6-472d-a9a1-df3b4347180f)

2024-04-05 07:01 UTC, glenlieorillo approved these changes
https://github.com/infor-design/enterprise/assets/102151352/78fdbbcd-33ea-42f9-a89f-4d8469e951e1

2024-04-05 11:07 UTC, merged