Fixed dropdown keys not properly triggering when using keyboard
infor-design/enterprise pull request #8749
Opened 2024-05-24 06:34 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix dropdown keys not properly triggering when using keyboard.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8745

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/datagrid/example-filter.html
- Place focus in Product Name cell on the filter row
- Hit the Tab key to tab into Activity cell on the filter row
- Hit the Enter or Space Bar key to open the dropdown
- Hit the Up/Down keys to navigate the options in the dropdown

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2024-05-24 08:09 UTC, n-ace-ancog submitted a review, later dismissed
Working as expected.

https://github.com/infor-design/enterprise/assets/156752175/d82a8bec-65bc-4d38-ba90-6701bd0842f4

2024-05-24 08:34 UTC, glenlieorillo approved these changes
https://github.com/infor-design/enterprise/assets/102151352/ae9b40c1-08d5-4663-a678-428f2dff9bd8

2024-05-24 10:00 UTC, jbrcna requested changes
this is now working as expected.
![Large GIF (940x554)](https://github.com/infor-design/enterprise/assets/56722184/a9e1a4d7-0d69-4da8-9952-cdb6a9d6c1b8)
However, in firefox the icon is not aligned properly.
<img width="982" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/4a171c09-1115-4bfb-bb09-5fa88c10a3d3">

2024-05-24 14:38 UTC, tmcconechy commented
@tjamesallen15 when i try it sometimes it will not focus the dropdown and i cant use the keyboard or click to select. Try these steps several times in chrome and maybe you will see it too?

- reload
- click in product name
- tab
- space
- try to use arrows or click (doesnt work)

2024-05-24 15:43 UTC, janahintal requested changes
Also having alignment issues with Firefox
![image](https://github.com/infor-design/enterprise/assets/45757016/61375bc7-9c25-47bf-a759-33ba7e15b7b6)

2024-05-27 03:05 UTC, tjamesallen15 commented
> * n the

I tried in ten times I can't see it on my end. I tried it in our mac workstation, and also on my personal computer at home which is Windows.

2024-05-27 08:37 UTC, n-ace-ancog approved these changes
For the Firefox issue, seems to be fixed now.

<img width="716" alt="image" src="https://github.com/infor-design/enterprise/assets/156752175/086c1f05-5da0-4a4b-b46b-45d10d2f22f3">

Still working as expected for the tabbing scenarios.

https://github.com/infor-design/enterprise/assets/156752175/f4887e85-ea83-4481-b254-5b8491722710

2024-05-27 12:08 UTC, jbrcna approved these changes
nice fix! approving.
<img width="1153" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/1d124dab-726d-40af-a8ff-c368bcaf6e14">

2024-05-27 13:51 UTC, merged