8828 - Refix grid issue
infor-design/enterprise pull request #8829
Opened 2024-06-18 16:21 UTC by tmcconechy

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Refixes the issue https://github.com/infor-design/enterprise/pull/8738 with a different fix that doesnt break the grid.

**Related github/jira issue (required)**:
Fixes #8828

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/module-nav/test-six-columns.html?colors=fff
- resize the page around the size of the attached screen shot and smaller/bigger and make sure the fields dont touch
- go to http://localhost:4000/components/module-nav/example-index.html?colors=fff
- and inspect the .columns element and make sure the module nav doesnt add styles to it

**Included in this Pull Request**:
- [x] A note to the change log.

**Screen Shots**

![Screenshot 2024-06-18 at 12 20 29 PM](https://github.com/infor-design/enterprise/assets/814283/006ea701-5961-427f-91c7-c043b82aa69e)
![Screenshot 2024-06-18 at 12 19 47 PM](https://github.com/infor-design/enterprise/assets/814283/39d7bb62-57ed-4466-9490-3b55349de05e)

2024-06-19 09:20 UTC, ericangeles approved these changes

2024-06-20 06:49 UTC, jbrcna approved these changes
<img width="1657" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/d6786c10-924f-4807-bd14-a4bf146cc495">
<img width="828" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/83953b51-fe0f-4b81-b795-c8f600252ed3">
<img width="925" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/8a4a5a4d-e5f1-42dc-bcbb-7958458506fd">

2024-06-20 06:58 UTC, n-ace-ancog requested changes
In http://localhost:4000/components/module-nav/test-six-columns.html?colors=fff, the fields does touch each other when making the page smaller.

https://github.com/infor-design/enterprise/assets/156752175/2cf29455-0d9e-4b15-b408-aaa3485d134b

![image](https://github.com/infor-design/enterprise/assets/156752175/78322e64-8be5-4de8-8396-31cf16d6cad6)

2024-06-20 11:40 UTC, glenlieorillo requested changes
Same result with @n-ace-ancog.

https://github.com/infor-design/enterprise/assets/102151352/80a5d7eb-a768-4860-82bc-e5c11c3e4278

![image](https://github.com/infor-design/enterprise/assets/102151352/392c5698-8199-40a6-bb59-ec465ab5abbb)

2024-06-24 17:28 UTC, tmcconechy commented
@n-ace-ancog @glenlieorillo I fixed the issue as noted (wasnt fixed for "side bar" state)

2024-06-25 03:34 UTC, n-ace-ancog approved these changes
Now working on my end.

https://github.com/infor-design/enterprise/assets/156752175/84df6c8f-0547-45c2-8949-435465f12f8f

2024-06-25 05:31 UTC, glenlieorillo approved these changes
https://github.com/infor-design/enterprise/assets/102151352/4667eec0-2174-460e-b394-025d8326d86a

2024-06-25 06:13 UTC, jbrcna approved these changes
![Large GIF (1672x918)](https://github.com/infor-design/enterprise/assets/56722184/516aac7e-436b-49d6-93a1-3675b82f8d6d)

2024-06-25 13:16 UTC, merged