Prevent memory leak.
infor-design/enterprise pull request #8833
Opened 2024-06-19 02:34 UTC by henryb0119

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
On updateRow function:
Existing DOM elements were not cleaned up before replacing with new ones.
Fixes:
- Detach eventListeners.
- Remove all attributes.
- Remove all attached data.

setTimeout functions have closure errors.
- Fix: Now passing the external variables as function parameter.

eventListener functions have closure errors.
- Fix: Save external objects in the current element then retrieve them inside the event functions.

calculateTextWidth is calculating the entire list cells.
- Fix: Just calculate what is visible in the screen.

**Related github/jira issue (required)**:
None

**Steps necessary to review your pull request (required)**:
- test scenarios:
In M3 Angular application:
1. Open 2 programs then scroll down 10x
2. Scroll 10x more 
3. Check chrome task manager
    Expected: No memory leak
    Actual: Memory heap usage has reached 3gb
![memleak](https://github.com/infor-design/enterprise/assets/20462137/e49efec7-b510-4da6-b4d8-35ca04c68b3a)
![memleakTM](https://github.com/infor-design/enterprise/assets/20462137/751c8590-c8e7-4757-8d4c-242b0ec821c6)
Uploading memleak (1).mp4…
file://PHMANHBANZON01/Users/hbanzon/OneDrive%20-%20Infor/For%20Share/memleak.webm

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [ ] A note to the change log.

2024-06-19 13:27 UTC, tmcconechy reviewed
@henryb0119 Interested in this one. Do you have any info on what this actually fixes?

The only thing i dont really like is the `setTimeout` functions they seem really weird to look at. Does passing the parameter in really make any difference for memory?

What about removing or replacing some of these with `requestAnimationFrame` although that could have a bigger impact.

How much testing was done here?

NOTE: Some lint issues to resolve (`npm run lint`)

2024-06-19 13:46 UTC, tmcconechy commented
@jdilag90 @clayinfor @ericangeles -> can you give any feedback here?

2024-06-19 16:38 UTC, tmcconechy commented on src/components/datagrid/datagrid.js
> +      let rowHtAssume = 33;
@henryb0119 what is the purpose of this change?

2024-06-19 16:39 UTC, tmcconechy commented on src/components/datagrid/datagrid.js
> +      }, delay, [self, elem]); //pass the parameters (self and elem)
@henryb0119 in these cases.  does it really help by passing this in to help dispose of it

a) do we need the setTimeout
b) can we use requestAnimationFrame

2024-06-19 23:23 UTC, henryb0119 commented on src/components/datagrid/datagrid.js
> +      let rowHtAssume = 33;
Datagrid is currently calculating the width of all cells. What I did is to calculate the width of cells that can be seen in the screen. To get the starting row index, I have to know the height of each table row/cell (scrollTop/table row height = start row index).

2024-06-19 23:38 UTC, henryb0119 commented on src/components/datagrid/datagrid.js
> +      }, delay, [self, elem]); //pass the parameters (self and elem)
Anything that will work can be done. I'm just concerned in the closure error, we just need to prevent it.

2024-06-19 23:42 UTC, henryb0119 commented
> `requestAnimationFrame`

Passing a parameter in setTimeout function is normal. It is being taught [here](https://www.w3schools.com/jsref/met_win_settimeout.asp).

2024-06-20 04:19 UTC, henryb0119 commented
Hi @tmcconechy ,
    What I fixed here primarily is the detached HTML elements, which were not garbage collected in the memory heap. I have attached here a screenshot of what has been removed from the memory heap after implementing the code fixes.

Regards,
-Henry

2024-06-20 09:33 UTC, n-ace-ancog commented
Do we have an existing example page from baseline that we can compare vs in this fork? I assume the testing on our end would that data grid still works as is @tmcconechy.

2024-06-24 16:42 UTC, tmcconechy commented
@n-ace-ancog my understanding is maybe you could test the previous version https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html vs this branch and then keep pressing the addRow button

But that may not help that much. More importantly the grid should still work as before

2024-06-24 17:19 UTC, tmcconechy commented
@henryb0119 still some lint issues can you fix them and add a change log entry? Then i think we can approve this as long as QA takes a look

2024-06-25 10:38 UTC, n-ace-ancog requested changes
Editing an input seems to lead to an error.

**Steps to reproduce:**
1. Go to http://localhost:4000/components/datagrid/example-editable.html
2. Open developer's console
3. Add some character's to any editable field
4. See error

![image](https://github.com/infor-design/enterprise/assets/156752175/b97bb6d2-1c4b-4350-9ff0-ab356af3898c)

![image](https://github.com/infor-design/enterprise/assets/156752175/990efe64-f66f-40fe-bd79-b2c6062f1e97)

2024-06-25 11:42 UTC, henryb0119 commented
> Editing an input seems to lead to an error.
> 
> **Steps to reproduce:**
> 
> 1. Go to http://localhost:4000/components/datagrid/example-editable.html
> 2. Open developer's console
> 3. Add some character's to any editable field
> 4. See error
> 
> ![image](https://private-user-images.githubusercontent.com/156752175/342692041-b97bb6d2-1c4b-4350-9ff0-ab356af3898c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMTU1MDMsIm5iZiI6MTcxOTMxNTIwMywicGF0aCI6Ii8xNTY3NTIxNzUvMzQyNjkyMDQxLWI5N2JiNmQyLTFjNGItNDM1MC05ZmYwLWFiMzU2YWYzODk4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxMTMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmIzNjQ4Yzg2ZTRhOTVkOGFlOTIyMTZmYTFlZTJiOWE0OWUxYjM4NDM4M2M1MDJmOGQxYTEyN2RkNDdjMGEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RVLYVEhxCNIghZA7t1SDomXxviifK-50hU9lsdvSKFE)
> 
> ![image](https://private-user-images.githubusercontent.com/156752175/342692507-990efe64-f66f-40fe-bd79-b2c6062f1e97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMTU1MDMsIm5iZiI6MTcxOTMxNTIwMywicGF0aCI6Ii8xNTY3NTIxNzUvMzQyNjkyNTA3LTk5MGVmZTY0LWY2NmYtNDBmZS1iZDc5LWIyYzYwNjJmMWU5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxMTMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGY5MjVkOWE3NGU5MTllODk2ZDUwMGI1MmMzMDhkMWE0OGJlMjczYTMwMWFmNTc1MWI3NWUxYjBhNDkwMzhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.af_KzvHQakx2T68jWN3yDPMzV2aXrsG30dTlGIVrjV0)

I realized that passing of variable inside the event listener is complicated, so I just made the function (where _self_ variable was declared to null) to still remove the reference of event listener functions to the datagrid object.

2024-06-25 11:42 UTC, henryb0119 commented
> @henryb0119 still some lint issues can you fix them and add a change log entry? Then i think we can approve this as long as QA takes a look

Done

2024-06-25 13:22 UTC, tmcconechy commented
@henryb0119 thanks it passes now. For change log just add an entry here https://github.com/infor-design/enterprise/blob/main/docs/CHANGELOG.md please

We all qa this one. Thanks @n-ace-ancog

2024-06-26 02:57 UTC, henryb0119 commented
> @henryb0119 thanks it passes now. For change log just add an entry here https://github.com/infor-design/enterprise/blob/main/docs/CHANGELOG.md please. Also you are saying the editing error is fixed? Some screen shots look missing.
> 
> We all qa this one. Thanks @n-ace-ancog

Here my test recording:
https://github.com/infor-design/enterprise/assets/20462137/208021cd-d972-46ed-a982-f7a8041a8a3d

Thanks for giving time on this pull request. I really appreciate it.

2024-06-26 13:14 UTC, tmcconechy commented
@henryb0119 You welcome. This is close.

a) Is the issue from @n-ace-ancog about typing fixed to be clear? If not i think we cant leave this one and because this is a fork i cant help fix it.
b) Can you add an entry to the change log?

2024-06-27 02:58 UTC, henryb0119 commented
> @henryb0119 You welcome. This is close.
> 
> a) Is the issue from @n-ace-ancog about typing fixed to be clear? If not i think we cant leave this one and because this is a fork i cant help fix it. b) Can you add an entry to the change log?

a. The issue has been fixed and I atached the test recording on the previous conversation.
b. I already added the change summary in the change log document.

Regards,
-Henry

2024-06-27 03:05 UTC, henryb0119 commented
> Editing an input seems to lead to an error.
> 
> **Steps to reproduce:**
> 
> 1. Go to http://localhost:4000/components/datagrid/example-editable.html
> 2. Open developer's console
> 3. Add some character's to any editable field
> 4. See error
> 
> ![image](https://private-user-images.githubusercontent.com/156752175/342692041-b97bb6d2-1c4b-4350-9ff0-ab356af3898c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTc3NjcsIm5iZiI6MTcxOTQ1NzQ2NywicGF0aCI6Ii8xNTY3NTIxNzUvMzQyNjkyMDQxLWI5N2JiNmQyLTFjNGItNDM1MC05ZmYwLWFiMzU2YWYzODk4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QwMzA0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzE1N2Y3NjYzYTBkOTI0YTAxNDk0MWI3Yzg4MTE2NDVmZDczOWI5NGQ5ZjJlZDJjZDlkOThkMTEyY2VlNTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fdubmjQciE8iDNLE9gLMf8IAVYsD8eSkPVr7U7CFkzw)
> 
> ![image](https://private-user-images.githubusercontent.com/156752175/342692507-990efe64-f66f-40fe-bd79-b2c6062f1e97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTc3NjcsIm5iZiI6MTcxOTQ1NzQ2NywicGF0aCI6Ii8xNTY3NTIxNzUvMzQyNjkyNTA3LTk5MGVmZTY0LWY2NmYtNDBmZS1iZDc5LWIyYzYwNjJmMWU5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QwMzA0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWQ3ZjJiNTU0NTk2YWFlYjk0ZWZhNWJlMjQwMjA3OTMwMDhjYjI1YWJlNDlhMmM3NDI1ZTllNzIzY2FkZDAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mKihpt6l1ammopwSqEMn05MhzrZWcKaLdpJrnP1qF98)

Hi @n-ace-ancog ,

This is fixed already.

Thanks,
-Henry

2024-06-27 07:42 UTC, n-ace-ancog reviewed
Seems the error when editing fields is now fixed. I quickly checked the other data grid example and found no errors when interacting with them.

https://github.com/infor-design/enterprise/assets/156752175/83c74fd2-065f-4beb-970a-a422e65cfe97

2024-06-27 09:28 UTC, glenlieorillo submitted a review, later dismissed
https://github.com/infor-design/enterprise/assets/102151352/20e2a48f-810c-4dd7-9018-e786dc6abbad

![image](https://github.com/infor-design/enterprise/assets/102151352/41027fbc-0d02-44db-b963-bb342e7bd017)

2024-06-27 10:41 UTC, jbrcna submitted a review, later dismissed
<img width="1701" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/89cae058-b8e4-4514-a2be-23c134d4e2cf">

2024-06-27 14:59 UTC, tmcconechy commented
@n-ace-ancog you ok with this one?

2024-06-27 15:00 UTC, tmcconechy approved these changes

2024-06-28 00:52 UTC, n-ace-ancog submitted a review, later dismissed

2024-06-28 14:56 UTC, merged