1689 - Allow checkboxes to be disabled for selection
infor-design/enterprise pull request #8882
Opened 2024-07-09 16:44 UTC by tmcconechy

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Allows isEditable checkboxes to disable rows selections. Also pushed incorrect initial count in some examples

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise-ng/issues/1689

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/datagrid/example-disabled-selection-checkbox.html
- clicking the disable checkboxes should not select a row
- clicking the last 2 will select a row
- repeat test with keyboard / space key should only select non editable rows
- note click to select is off so clicking anywhere but the checkbox column will not select the row

**Included in this Pull Request**:
- [x] A test for the bug or feature.
- [x] A note to the change log.

2024-07-09 17:32 UTC, sami1riaz commented on app/views/components/datagrid/example-disabled-selection-checkbox.html
> +      let isEditable = false;
Can we not use the disabled attribute on the column to disable the checkbox? I believe we can use that attribute on the  Soho.Formatters.Button and Soho.Formatters.Checkbox to disable them. But not with Soho.Formatters.SelectionCheckbox

2024-07-09 18:13 UTC, tmcconechy commented on app/views/components/datagrid/example-disabled-selection-checkbox.html
> +      let isEditable = false;
Do you mean instead of isEditable? https://github.com/infor-design/enterprise/pull/8882/files#diff-871e1d2fe997e8998bc13fc9cab16588e521845c6f79bf10073567f1836e6139R108

Use disabled function as well? I think we can do that.

2024-07-09 18:20 UTC, tmcconechy commented on app/views/components/datagrid/example-disabled-selection-checkbox.html
> +      let isEditable = false;
Update: I do not see any disabled setting on the column. Only `isReadonly` or `isEditable`

You cant set it right on the checkbox as its dynamic from the column data.

2024-07-10 03:55 UTC, glenlieorillo requested changes
Using the spacebar to click the checkbox in the disabled row is still possible.

https://github.com/infor-design/enterprise/assets/102151352/9d46e6d4-fb60-4603-b2c5-bdbfbec5c4f1

2024-07-10 05:01 UTC, jbrcna requested changes
<img width="1363" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/0a01166d-669f-4b60-ac3a-c4e7c43ba932">

2024-07-10 13:40 UTC, sami1riaz commented on app/views/components/datagrid/example-disabled-selection-checkbox.html
> +      let isEditable = false;
Ok, i was under the impression that the disabled setting could be set for selectionCheckboxes as well, the way we do it for buttons.

2024-07-10 13:46 UTC, tmcconechy commented on app/views/components/datagrid/example-disabled-selection-checkbox.html
> +      let isEditable = false;
Do you have an example of that? Just to make sure im not missing something else?

2024-07-10 18:53 UTC, tmcconechy commented
@sami1riaz OK i see what you mean now. Was missing examples for this so i didnt see it.

I updated the selection checkbox to work on `disabled` as well. Note that you will have to reverse your logic (false vs true) and then i used the checkbox style but didnt make the column readonly. I think this might be what you want.

Please try and confirm

2024-07-10 19:28 UTC, sami1riaz commented
@tmcconechy, thanks! Yes this is what we need. Looks good.

2024-07-10 19:35 UTC, tmcconechy commented
ok @sami1riaz we will patch once QA looks and the tests pass 👍🏻

2024-07-11 05:31 UTC, janahintal approved these changes
Now working as expected on my end. Thanks!
Test Data: [screen-capture (1).webm](https://github.com/infor-design/enterprise/assets/45757016/bbb01a4d-7855-41c5-bbd6-9e47a2e0b093)

2024-07-11 05:50 UTC, glenlieorillo approved these changes
https://github.com/infor-design/enterprise/assets/102151352/1b91611c-cf5d-4b01-ae27-bf44c6e32113

2024-07-11 06:15 UTC, jbrcna approved these changes
great work!
<img width="1357" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/a5d3fd01-7278-4faf-8a6b-ab05f2cd404b">

2024-07-11 14:17 UTC, merged

2024-07-18 13:45 UTC, sami1riaz commented
Hi @tmcconechy, @jbrcna, I just tested the fix and it is not working with the selectAll checkbox or with selecting the parent row in a tree grid:

![image](https://github.com/user-attachments/assets/37bda484-e413-4a7d-bc39-d6627779175a)

You can see in the screenshot that the disabled row is also being selected. Can this be fixed as well please?

2024-07-19 02:00 UTC, jbrcna commented
@sami1riaz what link did you use for testing? 
I tried it on main and it's working. https://main-enterprise.demo.design.infor.com/components/datagrid/example-disabled-selection-checkbox.html

2024-07-19 17:16 UTC, tmcconechy commented
@jbrcna we just missed something in the context of the disabled rows. I will fix and flag on a new pull request

2024-07-22 03:16 UTC, jbrcna commented
thanks for clarifying @tmcconechy