8893 - Widget Button Disabled
infor-design/enterprise pull request #8907
Opened 2024-07-19 07:24 UTC by tjamesallen15

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

This pull request will fix a bug where disabled button are not properly rendered in widgets.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise/issues/8893

**Steps necessary to review your pull request (required)**:
- Pull this git repository, build, and run the app
- Go to http://localhost:4000/components/cards/example-workspace-widgets.html
- Look for `Badge (5)` Widget
- See the search button is now properly disabled

**Included in this Pull Request**:
- [ ] An e2e or functional test for the bug or feature.
- [x] A note to the change log.

2024-07-19 09:25 UTC, jbrcna submitted a review, later dismissed
<img width="1260" alt="image" src="https://github.com/user-attachments/assets/ac0144ad-ac63-4db1-b455-b79085edfe49">

2024-07-19 10:06 UTC, glenlieorillo submitted a review, later dismissed
This is now working as expected.

https://github.com/user-attachments/assets/eec1e379-fd99-440c-af57-56c512fccaf9

2024-07-19 11:32 UTC, janahintal approved these changes
[screen-capture (4).webm](https://github.com/user-attachments/assets/a2f5cc41-e49c-448a-b223-88d76e7fed4d)

2024-07-19 14:01 UTC, tmcconechy requested changes
@yohannahbautista can you make a new variable and set it to opacity (.4.) that should be the correct disabled color. 

Like https://main-enterprise.demo.design.infor.com/components/button/example-index.html so same color text but opacity: 0.4

2024-07-25 05:47 UTC, glenlieorillo approved these changes
![image](https://github.com/user-attachments/assets/d2f4f49a-b738-4ba4-81e8-2328bdf6c321)

2024-07-25 06:29 UTC, jbrcna approved these changes
<img width="1403" alt="image" src="https://github.com/user-attachments/assets/744bf201-d054-4229-a6a3-21789406ed37">

2024-07-25 13:59 UTC, tmcconechy approved these changes

2024-07-25 13:59 UTC, merged