Misc - Fix child selection and demo app example
infor-design/enterprise pull request #8922
Opened 2024-07-29 17:35 UTC by tmcconechy

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Adds to a previous issue so checkboxes can be disabled and have it work with tree view.
Fixes the example page to show dragging

**Related github/jira issue (required)**:
Fixes https://github.com/infor-design/enterprise/issues/8915
Fixes https://github.com/infor-design/enterprise/issues/8920

**Steps necessary to review your pull request (required)**:
- go to http://localhost:4000/components/datagrid/example-tree-disabled-selection-checkbox.html
- try to select the disabled rows (should not able to)
- try to click a parent row where children are disabled (child rows should not be selected)
- go to http://localhost:4000/components/datagrid/example-indedx.html
- should be able to drag columns and drag them in the personalization dialog

**Included in this Pull Request**:
- [x] A test for the bug or feature.
- [x] A note to the change log.

2024-07-30 10:16 UTC, n-ace-ancog requested changes
Disabled rows are still being selected when:
1. via select all
![image](https://github.com/user-attachments/assets/eb820324-2238-45b0-be1a-dd3cdd73eea0)

2. via selecting the row of a child

https://github.com/user-attachments/assets/3d6f1f7f-0513-49b4-9746-e672574dc136

Dragging of rows in personalized column works.

https://github.com/user-attachments/assets/cda19528-b3e4-46bd-9391-ad395bff1f31

2024-07-30 18:04 UTC, merged

2024-07-31 06:24 UTC, jbrcna reviewed
<img width="1549" alt="image" src="https://github.com/user-attachments/assets/a9a5131c-8bac-4285-a13a-3c41a845ae49">

2024-07-31 12:37 UTC, tmcconechy commented
@jbrcna did you notice an issue? Can you add the steps?

2024-08-01 07:46 UTC, jbrcna commented
@tmcconechy I was able to select the first row which is disabled. by clicking 2nd column` 'Follow up action with HMM Global'`
<img width="354" alt="image" src="https://github.com/user-attachments/assets/c2bc2a17-525b-48c1-b332-9b50cf88a3d5">

2024-08-01 14:30 UTC, tmcconechy commented
@jbrcna good catch. I fixed on https://main-enterprise.demo.design.infor.com/components/datagrid/example-tree-disabled-selection-checkbox.html (may take a while to update).

The example needs `clickToSelect` on it

2024-08-02 01:24 UTC, jbrcna commented
Confirmed. thanks @tmcconechy  great work! 
![Large GIF (1372x764)](https://github.com/user-attachments/assets/e4d22b96-deb3-4e86-86a7-df266f70b9a7)