fFxed text misaligned in action dropdown
infor-design/enterprise pull request #8958
Opened 2024-08-10 07:29 UTC by rishang14

**Explain the _details_ for making this change. What existing problem does the pull request solve?**
 
Fixed text misaligned in action dropdown

**Related github/jira issue (required)**:
 
Fixes #8957 

**Steps necessary to review your pull request (required)**:

**Included in this Pull Request**:

- [✔️ ] A note to the change log.

2024-08-12 07:04 UTC, jbrcna requested changes
<img width="1352" alt="image" src="https://github.com/user-attachments/assets/f0c19667-afec-42da-883c-356785224654">

in firefox, the text is not centered
<img width="1314" alt="image" src="https://github.com/user-attachments/assets/37499795-e96e-4eaa-868e-842a052397ff">

2024-08-12 09:24 UTC, glenlieorillo requested changes
The alignment still needs to adjust to the center in Mac Firefox.

Mac - Firefox 
![image](https://github.com/user-attachments/assets/5f67ccdd-94fb-480a-9b61-9972b2de8424)

Mac - Chrome
![image](https://github.com/user-attachments/assets/1345557f-eddd-40fb-bd76-14ef4e88bf85)

Mac - Edge
![image](https://github.com/user-attachments/assets/c0959edb-6514-4626-803e-c5607c8b0e7e)

Safari
![image](https://github.com/user-attachments/assets/b60fb549-a328-461f-bbaa-c786ac4f5c57)

2024-08-12 13:44 UTC, tmcconechy commented on src/components/dropdown/_dropdown.scss
> +    // padding: 7px 0;
Also we prefer to remove code rather than leave it in commented out?

2024-08-12 13:46 UTC, tmcconechy commented
@rishang14 be sure to test:

http://localhost:4000/components/dropdown/example-index.html
http://localhost:4000/components/multiselect/example-index.html

As i think this is effecting there. Might need this fix isolated in datagrid.scss

2024-08-13 15:34 UTC, tmcconechy commented
@rishang14 can you follow up with some of the updates suggested and fix the lint issues? thanks for your contribution!

2024-08-15 14:06 UTC, tmcconechy submitted a review, later dismissed

2024-08-15 15:52 UTC, ericangeles approved these changes

2024-08-19 11:06 UTC, jbrcna approved these changes
<img width="1233" alt="image" src="https://github.com/user-attachments/assets/4f5d81ef-90c7-44de-aec5-36cf4aa4df52">

2024-08-19 14:28 UTC, merged