1791 - Add guards on tooltip
infor-design/enterprise pull request #9009
Opened 2024-09-05 18:10 UTC by tmcconechy

**Explain the _details_ for making this change. What existing problem does the pull request solve?**

Added some protection for error situations in Angular as noted on the issue. Issue did not have a clear way to reproduce.

**Related github/jira issue (required)**:
Closes https://github.com/infor-design/enterprise-ng/issues/1791

**Steps necessary to review your pull request (required)**:
- test data grid filters and try and provoke an error
- check logic in the PR

**Included in this Pull Request**:
- [ ] A test for the bug or feature.
- [x] A note to the change log.

2024-09-06 01:23 UTC, yohannahbautista requested changes

2024-09-06 01:23 UTC, yohannahbautista commented on docs/CHANGELOG.md
> -- `[Datagrid]` Fixed a bug in compact mode where datagrid filters doesn't extend all throughout the parents width. ([#8900](https://github.com/infor-design/enterprise-/issues/8900))
I think this was deleted by mistake

2024-09-06 14:05 UTC, ericangeles approved these changes

2024-09-09 02:58 UTC, yohannahbautista approved these changes

2024-09-09 14:04 UTC, tmcconechy commented
@n-ace-ancog yeah sorry with this one the issue is an app we dont have a clear example for it. Will just merge

2024-09-09 14:04 UTC, merged